(function(g){var window=this;'use strict';var rw=function(Z){Z.publish("autonavvisibility")},szr=function(Z,k){g.A7(Z,"onAutonavCoundownStarted",k)},CS=function(Z){return Z.isBackground()&&Z.i9()},AZB=function(Z,k){k=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
Z.O=k?.navigationEndpoint;k=k?.trackingParams;Z.playButton&&k&&Z.S.setTrackingParams(Z.playButton.element,k)},AS=function(Z){const k=mq(Z);
var N=Math,a=N.min;var T=Z.j?Date.now()-Z.j:0;N=a.call(N,T,k);sz(Z,Math.ceil((k-N)/1E3));k-N<=500&&Z.V()?Z.select(!0):Z.V()&&Z.N.start()},PL=function(Z){var k=Z.S.Sd(!0,Z.S.isFullscreen());
g.D(Z.container.element,"ytp-autonav-endscreen-small-mode",Z.bV(k));g.D(Z.container.element,"ytp-autonav-endscreen-is-premium",!!Z.suggestion&&!!Z.suggestion.jj);g.D(Z.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!Z.S.Gc());g.D(Z.S.getRootNode(),"countdown-running",Z.V());g.D(Z.container.element,"ytp-player-content",Z.S.Gc());g.ij(Z.overlay.element,{width:`${k.width}px`});if(!Z.V()){Z.S.Gc()?sz(Z,Math.round(mq(Z)/1E3)):sz(Z);k=!!Z.suggestion&&!!Z.suggestion.V9;const N=Z.S.Gc()||!k;g.D(Z.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!N&&k);g.D(Z.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",N&&!k);Z.G.In(Z.S.Gc())}},sz=function(Z,k=-1){Z=Z.Y.Lp("ytp-autonav-endscreen-upnext-header");
g.Qp(Z);if(k>=0){k=String(k);const N="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],a="Up next in $SECONDS".indexOf(N);if(a>=0){Z.appendChild(g.K1("Up next in $SECONDS".slice(0,a)));const T=g.TU("span");g.nj(T,"ytp-autonav-endscreen-upnext-header-countdown-number");g.m_(T,k);Z.appendChild(T);Z.appendChild(g.K1("Up next in $SECONDS".slice(a+N.length)));return}}g.m_(Z,"Up next")},mq=function(Z){return Z.S.isFullscreen()?(Z=Z.S.getVideoData()?.nD,Z===-1||Z===void 0?8E3:Z):Z.S.PB()>=0?Z.S.PB():
g.Q5(Z.S.X().experiments,"autoplay_time")||1E4},cL=function(Z,k){k=Pzr(Z,k);
var N=Math,a=N.min;var T=(0,g.z)()-Z.j;N=a.call(N,T,k);k=k===0?1:Math.min(N/k,1);Z.FS.setAttribute("stroke-dashoffset",`${-211*(k+1)}`);k>=1&&Z.V()&&Z.api.getPresentingPlayerType()!==3?Z.select(!0):Z.V()&&Z.Y.start()},Pzr=function(Z,k){return k?k:Z.api.isFullscreen()?(Z=Z.api.getVideoData()?.nD,Z===-1||Z===void 0?8E3:Z):Z.api.PB()>=0?Z.api.PB():g.Q5(Z.api.X().experiments,"autoplay_time")||1E4},HL=function(Z){const k=Z.Gc();
k!==Z.j&&(Z.j=k,rw(Z.player),Z.j?(Z.U!==Z.V&&Z.U.hide(),Z.table.hide()):(Z.U!==Z.V&&Z.U.show(),Z.table.show()))},dw=function(Z){return g.xn(Z.player)&&Z.Y()&&!Z.L},XA=function(Z){const k=Z.Gc();
k!==Z.N&&(Z.N=k,rw(Z.player))},LS=function(Z){return g.xn(Z.player)&&Z.Y()&&!Z.G},VN=function(Z){const k=Z.Gc();
k!==Z.zt&&(Z.zt=k,rw(Z.player))},cZr=function(Z){Z=Z.X();
return Z.bq&&!Z.j9&&!Z.disableOrganicUi},H_i=function(Z){const k=Z.player.getVideoData();
if(!k||Z.V===k.gV&&Z.U===k.pF)return!1;Z.V=k.gV;Z.U=k.pF;return!0},d7T=function(Z){Z.player.jl("endscreen");
var k=Z.player.getVideoData();k=new g.pe(Math.max((k.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const N=new g.pe(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});Z.player.f8([k,N])};
g.cH.prototype.PB=g.ay(9,function(){return this.app.PB()});
g.aw.prototype.PB=g.ay(8,function(){return this.getVideoData().bL});
g.PH.prototype.bM=g.ay(7,function(Z){this.jK().bM(Z)});
g.iL.prototype.bM=g.ay(6,function(Z){this.Yf!==Z&&(this.Yf=Z,this.kh())});
var X4B=class extends g.E{constructor(Z){const k=Z.X(),N=k.Y;super({J:"a",Z:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:N?k.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},A:[{J:"div",BD:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},A:[{J:"div",W:{"aria-label":"{{timestamp}}"},BD:["ytp-autonav-timestamp"],Da:"{{duration}}"},
{J:"div",BD:["ytp-autonav-live-stamp"],Da:"Live"},{J:"div",BD:["ytp-autonav-upcoming-stamp"],Da:"Upcoming"},{J:"div",Z:"ytp-autonav-list-overlay",A:[{J:"div",Z:"ytp-autonav-mix-text",Da:"Mix"},{J:"div",Z:"ytp-autonav-mix-icon"}]}]},{J:"div",BD:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Da:"{{title}}"},{J:"div",BD:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Da:"{{author}}"},{J:"div",BD:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
Da:"{{views_and_publish_time}}"}]});this.S=Z;this.suggestion=null;this.V=N;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.S.CP(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.wH||void 0)&&this.S.logClick(this.element)}onClick(Z){g.IC(Z,this.S,this.V,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(Z){switch(Z.keyCode){case 13:case 32:Z.defaultPrevented||(this.select(),Z.preventDefault())}}};var FA=class extends g.E{constructor(Z,k=!1){super({J:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});this.FS=k;this.cancelCommand=this.O=void 0;this.j=0;this.container=new g.E({J:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.u(this,this.container);this.container.HD(this.element);k=Z.X();const N=k.Y;this.S=Z;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.K(Z,"videodatachange",this.onVideoDataChange);this.Y=new g.E({J:"div",Z:"ytp-autonav-endscreen-upnext-container",
W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},A:[{J:"div",Z:"ytp-autonav-endscreen-upnext-header"},{J:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",Da:"{{autoplayAlternativeHeader}}"},{J:"a",Z:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:N?k.N:""},A:[{J:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},A:[{J:"div",W:{"aria-label":"{{timestamp}}"},
BD:["ytp-autonav-timestamp"],Da:"{{duration}}"},{J:"div",BD:["ytp-autonav-live-stamp"],Da:"Live"},{J:"div",BD:["ytp-autonav-upcoming-stamp"],Da:"Upcoming"}]},{J:"div",Z:"ytp-autonav-endscreen-video-info",A:[{J:"div",Z:"ytp-autonav-endscreen-premium-badge"},{J:"div",Z:"ytp-autonav-endscreen-upnext-title",Da:"{{title}}"},{J:"div",Z:"ytp-autonav-endscreen-upnext-author",Da:"{{author}}"},{J:"div",Z:"ytp-autonav-view-and-date",Da:"{{views_and_publish_time}}"},{J:"div",Z:"ytp-autonav-author-and-view",Da:"{{author_and_views}}"}]}]}]});
g.u(this,this.Y);this.Y.HD(this.container.element);N||this.K(this.Y.Lp("ytp-autonav-endscreen-link-container"),"click",this.xW);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.Y.Lp("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.E({J:"div",Z:"ytp-autonav-overlay"});g.u(this,this.overlay);this.overlay.HD(this.container.element);this.G=new g.E({J:"div",Z:"ytp-autonav-endscreen-button-container"});g.u(this,this.G);this.G.HD(this.container.element);
this.cancelButton=new g.E({J:"button",BD:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],W:{"aria-label":"Cancel auto-play"},Da:"Cancel"});g.u(this,this.cancelButton);this.cancelButton.HD(this.G.element);this.cancelButton.listen("click",this.dA,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.E({J:"a",BD:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},Da:"Play now"});g.u(this,this.playButton);this.playButton.HD(this.G.element);this.playButton.listen("click",this.xW,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(k=this.S.getVideoData())&&AZB(this,k);this.N=new g.Uc(()=>{AS(this)},500);
g.u(this,this.N);this.zt();this.K(Z,"autonavvisibility",this.zt)}C(Z){this.suggestion!==Z&&(this.suggestion=Z,g.fY(this.Y,Z),this.playButton.updateValue("url",this.suggestion.Qg()),PL(this))}V(){return this.j>0}L(){this.V()||(this.j=Date.now(),AS(this),szr(this.S,mq(this)),g.D(this.S.getRootNode(),"countdown-running",this.V()))}D(){this.U();AS(this);const Z=this.Y.Lp("ytp-autonav-endscreen-upnext-header");Z&&g.m_(Z,"Up next")}U(){this.V()&&(this.N.stop(),this.j=0)}select(Z=!1){this.S.nextVideo(!1,
Z);this.U()}xW(Z){g.IC(Z,this.S)&&(Z.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):Z.currentTarget===this.Y.Lp("ytp-autonav-endscreen-link-container")&&(Z=this.Y.Lp("ytp-autonav-endscreen-link-container"),this.S.logVisibility(Z,!0),this.S.logClick(Z)),this.O?(g.A7(this.S,"innertubeCommand",this.O),this.U()):this.select())}dA(){this.S.logClick(this.cancelButton.element);g.B3(this.S,!0);this.cancelCommand&&g.A7(this.S,"innertubeCommand",this.cancelCommand)}onVideoDataChange(Z,
k){AZB(this,k);this.cancelCommand=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}zt(){const Z=this.S.Gc();this.FS&&this.LF!==Z&&this.In(Z);PL(this);this.S.logVisibility(this.container.element,Z);this.S.logVisibility(this.cancelButton.element,Z);this.S.logVisibility(this.Y.Lp("ytp-autonav-endscreen-link-container"),Z);this.S.logVisibility(this.playButton.element,Z)}bV(Z){return Z.width<400||Z.height<459}};var tS=class extends g.E{constructor(Z,k){super({J:"div",BD:["html5-endscreen","ytp-player-content",k||"base-endscreen"]});this.created=!1;this.player=Z}create(){this.created=!0}destroy(){this.created=!1}Y(){return!1}Gc(){return!1}O(){return!1}};var hS=class extends g.E{constructor(Z){super({J:"div",BD:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},A:[{J:"div",Z:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{J:"span",Z:"ytp-upnext-top",A:[{J:"span",Z:"ytp-upnext-header",Da:"Up Next"},{J:"span",Z:"ytp-upnext-title",Da:"{{title}}"},{J:"span",Z:"ytp-upnext-author",Da:"{{author}}"}]},{J:"a",Z:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},A:[{J:"svg",W:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},A:[{J:"circle",Z:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{J:"circle",Z:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{J:"path",Z:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{J:"span",Z:"ytp-upnext-bottom",A:[{J:"span",Z:"ytp-upnext-cancel"},
{J:"span",Z:"ytp-upnext-paused",Da:"Auto-play is paused"}]}]});this.api=Z;this.cancelButton=null;this.FS=this.Lp("ytp-svg-autoplay-ring");this.N=this.notification=this.Y=this.suggestion=null;this.O=new g.Uc(this.G,5E3,this);this.j=0;var k=this.Lp("ytp-upnext-cancel");this.cancelButton=new g.E({J:"button",BD:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel auto-play"},Da:"Cancel"});g.u(this,this.cancelButton);this.cancelButton.listen("click",this.xW,this);this.cancelButton.HD(k);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.u(this,this.O);this.api.createClientVe(this.element,this,18788);k=this.Lp("ytp-upnext-autoplay-icon");this.K(k,"click",this.dA);this.api.createClientVe(k,this,115130);this.zt();this.K(Z,"autonavvisibility",this.zt);this.K(Z,"mdxnowautoplaying",this.vD);this.K(Z,"mdxautoplaycanceled",this.Sm);g.D(this.element,"ytp-upnext-mobile",this.api.X().U)}G(){this.notification&&(this.O.stop(),this.Ce(this.N),this.N=null,this.notification.close(),
this.notification=null)}C(Z){this.suggestion=Z;g.fY(this,Z,"hqdefault.jpg")}zt(){this.In(this.api.Gc());this.api.logVisibility(this.element,this.api.Gc());this.api.logVisibility(this.Lp("ytp-upnext-autoplay-icon"),this.api.Gc());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Gc())}Rq(){window.focus();this.G()}L(Z){this.V()||(g.nR("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.j=(0,g.z)(),this.Y=new g.Uc(()=>{cL(this,Z)},25),cL(this,Z),szr(this.api,Pzr(this,
Z)));
g.Wp(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}V(){return!!this.Y}D(){this.U();this.j=(0,g.z)();cL(this);g.jX(this.element,"ytp-upnext-autoplay-paused")}U(){this.V()&&(this.Y.dispose(),this.Y=null)}select(Z=!1){if(this.api.X().B("autonav_notifications")&&Z&&window.Notification&&typeof document.hasFocus==="function"){const k=Notification.permission;k==="default"?Notification.requestPermission():k!=="granted"||document.hasFocus()||(this.G(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.v9()}),this.N=this.K(this.notification,"click",this.Rq),this.O.start())}this.U();this.api.nextVideo(!1,Z)}dA(Z){!g.C1(this.cancelButton.element,Z.target)&&g.IC(Z,this.api)&&(this.api.Gc()&&this.api.logClick(this.Lp("ytp-upnext-autoplay-icon")),this.select())}xW(){this.api.Gc()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.B3(this.api,!0)}vD(Z){this.api.getPresentingPlayerType();this.show();this.L(Z)}Sm(){this.api.getPresentingPlayerType();
this.U();this.hide()}YW(){this.U();this.G();super.YW()}};var VCa=class extends tS{constructor(Z){super(Z,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.E({J:"div",Z:"ytp-suggestion-panel",A:[{J:"div",BD:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Da:"More videos"}]});this.N=new g.E({J:"div",Z:"ytp-suggestions-container"});this.videos=[];this.D=null;this.j=this.C=!1;this.U=new FA(this.player);g.u(this,this.U);this.U.HD(this.element);Z.getVideoData().pF?this.V=this.U:(this.V=new hS(Z),g.$n(this.player,
this.V.element,4),g.u(this,this.V));this.overlay=new g.E({J:"div",Z:"ytp-autonav-overlay-cancelled-state"});g.u(this,this.overlay);this.overlay.HD(this.element);this.L=new g.tt(this);g.u(this,this.L);g.u(this,this.table);this.table.HD(this.element);this.table.show();g.u(this,this.N);this.N.HD(this.table.element);this.hide()}create(){super.create();this.L.K(this.player,"appresize",this.G);this.L.K(this.player,"onVideoAreaChange",this.G);this.L.K(this.player,"videodatachange",this.onVideoDataChange);
this.L.K(this.player,"autonavchange",this.zt);this.L.K(this.player,"onAutonavCancelled",this.xW);this.onVideoDataChange()}show(){super.show();(this.C||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.B3(this.player,!1);g.xn(this.player)&&this.Y()&&!this.D?(HL(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||CS(this.player.CN())&&this.player.B("web_player_pip_logging_fix")?this.V.select(!0):this.V.L():this.videoData.autonavState===3&&this.V.D()):(g.B3(this.player,
!0),HL(this));this.G()}hide(){super.hide();this.V.D();HL(this)}G(){var Z=this.player.Sd(!0,this.player.isFullscreen());HL(this);PL(this.U);g.D(this.element,"ytp-autonav-cancelled-small-mode",this.bV(Z));g.D(this.element,"ytp-autonav-cancelled-tiny-mode",this.HO(Z));g.D(this.element,"ytp-autonav-cancelled-mini-mode",Z.width<=400||Z.height<=360);this.overlay&&g.ij(this.overlay.element,{width:`${Z.width}px`});if(!this.j)for(Z=0;Z<this.videos.length;Z++)g.D(this.videos[Z].element,"ytp-suggestion-card-with-margin",
Z%2===1)}onVideoDataChange(){var Z=this.player.getVideoData();if(this.videoData!==Z&&Z){this.videoData=Z;Z=this.videoData.suggestions;var k=this.videoData.N();k&&(this.V.C(k),this.V!==this.U&&this.U.C(k));if(Z&&Z.length)for(let a=0;a<LcK.length;++a){var N=LcK[a];Z&&Z[N]&&(this.videos[a]=new X4B(this.player),k=this.videos[a],N=Z[N],k.suggestion!==N&&(k.suggestion=N,g.fY(k,N)),g.u(this,this.videos[a]),this.videos[a].HD(this.N.element))}this.G()}}zt(Z){Z===1?(this.C=!1,this.D=this.videoData.clientPlaybackNonce,
this.V.U(),this.LF&&this.G()):(this.C=!0,this.Gc()&&(Z===2?this.V.L():Z===3&&this.V.D()))}xW(Z){Z?this.zt(1):(this.D=null,this.C=!1)}Y(){return this.videoData.autonavState!==1}bV(Z){return(Z.width<910||Z.height<459)&&!this.HO(Z)&&!(Z.width<=400||Z.height<=360)}HO(Z){return Z.width<800&&!(Z.width<=400||Z.height<=360)}Gc(){return this.LF&&g.xn(this.player)&&this.Y()&&!this.D}},LcK=[1,3,2,4];var Fce=class extends tS{constructor(Z){super(Z,"videowall-endscreen");this.S=Z;this.stills=[];this.L=this.videoData=null;this.G=this.N=!1;this.zt=null;g.jX(this.element,"modern-videowall-endscreen");this.U=new g.tt(this);g.u(this,this.U);this.j=new g.Uc(()=>{g.jX(this.element,"ytp-show-tiles")},0);
g.u(this,this.j);this.table=new g.JO({J:"div",Z:"ytp-modern-endscreen-content"});g.u(this,this.table);this.table.HD(this.element);Z.getVideoData().pF?this.V=new FA(Z,!0):this.V=new hS(Z);g.u(this,this.V);g.$n(this.player,this.V.element,4);Z.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var Z=this.player.getVideoData();Z&&(this.videoData=Z);this.D();this.U.K(this.player,"appresize",this.D);this.U.K(this.player,"onVideoAreaChange",this.D);this.U.K(this.player,"videodatachange",
this.onVideoDataChange);this.U.K(this.player,"autonavchange",this.C);this.U.K(this.player,"onAutonavCancelled",this.xW);Z=this.videoData.autonavState;Z!==this.zt&&this.C(Z);this.U.K(this.element,"transitionend",this.dA)}destroy(){this.U.U();g.Il(this.stills);this.stills=[];super.destroy();g.Wp(this.element,"ytp-show-tiles");this.j.stop();this.zt=this.videoData.autonavState}Y(){return this.videoData.autonavState!==1}show(){const Z=this.LF;super.show();g.Wp(this.element,"ytp-show-tiles");this.player.X().U?
g.b6(this.j):this.j.start();(this.G||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.B3(this.player,!1);dw(this)?(XA(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||CS(this.player.CN())&&this.player.B("web_player_pip_logging_fix")?this.V.select(!0):this.V.L():this.videoData.autonavState===3&&this.V.D()):(g.B3(this.player,!0),XA(this));Z!==this.LF&&this.player.logVisibility(this.element,!0)}hide(){const Z=this.LF;super.hide();this.V.D();XA(this);Z!==this.LF&&this.player.logVisibility(this.element,
!1)}dA(Z){Z.target===this.element&&this.D()}D(){const Z=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.N()];if(Z.length){var k=this.S.Sd(!0,this.S.isFullscreen()),N=Math.floor((k.width-64+16)/(g.u0(k.width*.27,250,450)+16));k=Math.min(3,Math.floor((k.height-64)/((k.width-64-(N-1)*16)/N*.5625+70)));g.Y3(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.jX(this.element,`ytp-modern-endscreen-limit-rows-${k}`);
g.D(this.element,"ytp-modern-endscreen-single-item",N===1);g.D(this.element,"ytp-modern-endscreen-row-0",k===0);N=this.table.element;N.ariaLive="polite";this.V.C(this.videoData.N());this.V instanceof FA&&PL(this.V);g.D(this.element,"ytp-endscreen-takeover",dw(this));XA(this);k=0;N.ariaBusy="true";var a=Z.length;for(let T=0;T<a;T++){const K=T%a;let y=this.stills[T];y||(y=new g.Shi(this.player),this.stills[T]=y,N.appendChild(y.element));g.dly(y,Z[K]);k++}this.stills.length=k}}onVideoDataChange(){const Z=
this.player.getVideoData({playerType:1});this.videoData!==Z&&(Z?.N()?(this.videoData=Z,this.D()):this.player.U6("missg",{vid:Z?.videoId||"",cpn:Z?.clientPlaybackNonce||""}))}O(){return this.V.V()}C(Z){Z===1?(this.G=!1,this.L=this.videoData.clientPlaybackNonce,this.V.U(),this.LF&&this.D()):(this.G=!0,this.LF&&dw(this)&&(Z===2?this.V.L():Z===3&&this.V.D()))}xW(Z){if(Z){for(Z=0;Z<this.stills.length;Z++)this.S.logVisibility(this.stills[Z].element,!0);this.C(1)}else this.L=null,this.G=!1;this.D()}Gc(){return this.LF&&
dw(this)}};var tC_=class extends tS{constructor(Z){super(Z,"subscribecard-endscreen");this.V=new g.E({J:"div",Z:"ytp-subscribe-card",A:[{J:"img",Z:"ytp-author-image",W:{src:"{{profilePicture}}"}},{J:"div",Z:"ytp-subscribe-card-right",A:[{J:"div",Z:"ytp-author-name",Da:"{{author}}"},{J:"div",Z:"html5-subscribe-button-container"}]}]});g.u(this,this.V);this.V.HD(this.element);const k=Z.getVideoData();this.subscribeButton=new g.Lz("Subscribe",null,"Unsubscribe",null,!0,!1,k.WZ,k.subscribed,"trailer-endscreen",null,
Z,!1);g.u(this,this.subscribeButton);this.subscribeButton.HD(this.V.Lp("html5-subscribe-button-container"));this.K(Z,"videodatachange",this.aq);this.aq();this.hide()}aq(){const Z=this.player.getVideoData();this.V.update({profilePicture:Z.profilePicture,author:Z.author});this.subscribeButton.channelId=Z.WZ;var k=this.subscribeButton;Z.subscribed?k.V():k.U()}};var hyc=class extends g.E{constructor(Z){const k=Z.X(),N=g.Cf||g.vQ?{style:"will-change: opacity"}:void 0,a=k.Y,T=["ytp-videowall-still"];k.U&&T.push("ytp-videowall-show-text");super({J:"a",BD:T,W:{href:"{{url}}",target:a?k.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},A:[{J:"div",Z:"ytp-videowall-still-image",W:{style:"{{background}}"}},{J:"span",Z:"ytp-videowall-still-info",W:{"aria-hidden":"true"},A:[{J:"span",Z:"ytp-videowall-still-info-bg",
A:[{J:"span",Z:"ytp-videowall-still-info-content",W:N,A:[{J:"span",Z:"ytp-videowall-still-info-title",Da:"{{title}}"},{J:"span",Z:"ytp-videowall-still-info-author",Da:"{{author_and_views}}"},{J:"span",Z:"ytp-videowall-still-info-live",Da:"Live"},{J:"span",Z:"ytp-videowall-still-info-duration",Da:"{{duration}}"}]}]}]},{J:"span",BD:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},A:[{J:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{J:"span",
Z:"ytp-videowall-still-listlabel-length",A:[" (",{J:"span",Da:"{{playlist_length}}"},")"]}]},{J:"span",BD:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},A:[{J:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",Z:"ytp-videowall-still-listlabel-length",Da:" (50+)"}]}]});this.suggestion=null;this.U=a;this.api=Z;this.V=new g.tt(this);g.u(this,this.V);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.V.K(Z,"videodatachange",
this.onVideoDataChange);Z.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.CP(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.wH||void 0)&&this.api.logClick(this.element)}onClick(Z){if(g.PQ(this.api.X())&&this.api.B("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let k=this.suggestion.Qg();const N={};g.ia(this.api,N);k=g.mW(k,N);g.jY(k,this.api,Z)}else g.IC(Z,this.api,
this.U,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(Z){switch(Z.keyCode){case 13:case 32:Z.defaultPrevented||(this.select(),Z.preventDefault())}}onVideoDataChange(){const Z=this.api.getVideoData(),k=this.api.X();this.U=Z.o4?!1:k.Y}};var u9i=class extends tS{constructor(Z){super(Z,"videowall-endscreen");this.S=Z;this.L=0;this.stills=[];this.G=this.videoData=null;this.j=this.zt=!1;this.xW=null;this.D=new g.tt(this);g.u(this,this.D);this.C=new g.Uc(()=>{g.jX(this.element,"ytp-show-tiles")},0);
g.u(this,this.C);var k=new g.E({J:"button",BD:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},A:[g.N4()]});g.u(this,k);k.HD(this.element);k.listen("click",this.vD,this);this.table=new g.JO({J:"div",Z:"ytp-endscreen-content"});g.u(this,this.table);this.table.HD(this.element);k=new g.E({J:"button",BD:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},A:[g.aJ()]});g.u(this,k);k.HD(this.element);k.listen("click",this.FS,this);Z.getVideoData().pF?this.V=new FA(Z,!0):this.V=
new hS(Z);g.u(this,this.V);g.$n(this.player,this.V.element,4);Z.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var Z=this.player.getVideoData();Z&&(this.videoData=Z);this.U();this.D.K(this.player,"appresize",this.U);this.D.K(this.player,"onVideoAreaChange",this.U);this.D.K(this.player,"videodatachange",this.onVideoDataChange);this.D.K(this.player,"autonavchange",this.N);this.D.K(this.player,"onAutonavCancelled",this.dA);Z=this.videoData.autonavState;Z!==this.xW&&this.N(Z);
this.D.K(this.element,"transitionend",this.Sm)}destroy(){this.D.U();g.Il(this.stills);this.stills=[];super.destroy();g.Wp(this.element,"ytp-show-tiles");this.C.stop();this.xW=this.videoData.autonavState}Y(){return this.videoData.autonavState!==1}show(){const Z=this.LF;super.show();g.Wp(this.element,"ytp-show-tiles");this.player.X().U?g.b6(this.C):this.C.start();(this.j||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.B3(this.player,!1);LS(this)?(VN(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||CS(this.player.CN())&&this.player.B("web_player_pip_logging_fix")?this.V.select(!0):this.V.L():this.videoData.autonavState===3&&this.V.D()):(g.B3(this.player,!0),VN(this));Z!==this.LF&&this.player.logVisibility(this.element,!0)}hide(){const Z=this.LF;super.hide();this.V.D();VN(this);Z!==this.LF&&this.player.logVisibility(this.element,!1)}Sm(Z){Z.target===this.element&&this.U()}U(){var Z=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.N()];if(Z.length){g.jX(this.element,
"ytp-endscreen-paginate");var k=this.S.Sd(!0,this.S.isFullscreen()),N=g.Vn(this.S);N&&(N=N.dQ()?48:32,k.width-=N*2);var a=k.width/k.height,T=96/54,K=N=2,y=Math.max(k.width/96,2),Q=Math.max(k.height/54,2),q=Z.length;var r=q*4;for(r-=4;r>0&&(N<y||K<Q);){var C=N/2,m=K/2,A=N<=y-2&&r>=m*4,P=K<=Q-2&&r>=C*4;if((C+1)/m*T/a>a/(C/(m+1)*T)&&P)r-=C*4,K+=2;else if(A)r-=m*4,N+=2;else if(P)r-=C*4,K+=2;else break}T=!1;r>=12&&q*4-r<=6&&(K>=4||N>=4)&&(T=!0);r=N*96;y=K*54;a=r/y<a?k.height/y:k.width/r;a=Math.min(a,2);
r=Math.floor(Math.min(k.width,r*a));y=Math.floor(Math.min(k.height,y*a));k=this.table.element;k.ariaLive="polite";g.n1(k,r,y);g.ij(k,{marginLeft:`${r/-2}px`,marginTop:`${y/-2}px`});this.V.C(this.videoData.N());this.V instanceof FA&&PL(this.V);g.D(this.element,"ytp-endscreen-takeover",LS(this));VN(this);r+=4;y+=4;a=0;k.ariaBusy="true";for(Q=0;Q<N;Q++)for(C=0;C<K;C++)if(A=a,P=0,T&&Q>=N-2&&C>=K-2?P=1:C%2===0&&Q%2===0&&(C<2&&Q<2?C===0&&Q===0&&(P=2):P=2),A=g.l0(A+this.L,q),P!==0){m=this.stills[a];m||(m=
new hyc(this.player),this.stills[a]=m,k.appendChild(m.element));var d=Math.floor(y*C/K);const h=Math.floor(r*Q/N),B=Math.floor(y*(C+P)/K)-d-4,v=Math.floor(r*(Q+P)/N)-h-4;g.o4(m.element,h,d);g.n1(m.element,v,B);g.ij(m.element,"transitionDelay",(C+Q)/20+"s");g.D(m.element,"ytp-videowall-still-mini",P===1);g.D(m.element,"ytp-videowall-still-large",P>2);P=Math.max(v,B);g.D(m.element,"ytp-videowall-still-round-large",P>=256);g.D(m.element,"ytp-videowall-still-round-medium",P>96&&P<256);g.D(m.element,"ytp-videowall-still-round-small",
P<=96);A=Z[A];m.suggestion!==A&&(m.suggestion=A,P=m.api.X(),d=g.I3(m.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.fY(m,A,d),g.PQ(P)&&!m.api.B("web_player_log_click_before_generating_ve_conversion_params")&&(P=A.Qg(),d={},g.H3(m.api,"addEmbedsConversionTrackingParams",[d]),P=g.mW(P,d),m.updateValue("url",P)),(A=(A=A.sessionData)&&A.itct)&&m.api.setTrackingParams(m.element,A));a++}k.ariaBusy="false";g.D(this.element,"ytp-endscreen-paginate",a<q);for(Z=this.stills.length-1;Z>=
a;Z--)N=this.stills[Z],g.rM(N.element),g.nM(N);this.stills.length=a}}onVideoDataChange(){const Z=this.player.getVideoData({playerType:1});this.videoData!==Z&&(Z?.N()?(this.L=0,this.videoData=Z,this.U()):this.player.U6("missg",{vid:Z?.videoId||"",cpn:Z?.clientPlaybackNonce||""}))}FS(){this.L+=this.stills.length;this.U()}vD(){this.L-=this.stills.length;this.U()}O(){return this.V.V()}N(Z){Z===1?(this.j=!1,this.G=this.videoData.clientPlaybackNonce,this.V.U(),this.LF&&this.U()):(this.j=!0,this.LF&&LS(this)&&
(Z===2?this.V.L():Z===3&&this.V.D()))}dA(Z){if(Z){for(Z=0;Z<this.stills.length;Z++)this.S.logVisibility(this.stills[Z].element,!0);this.N(1)}else this.G=null,this.j=!1;this.U()}Gc(){return this.LF&&LS(this)}};var lZc=class extends g.E{constructor(Z){super({J:"button",BD:["ytp-watch-on-youtube-button","ytp-button"],Da:"{{content}}"});this.S=Z;this.buttonType=this.buttonType=1;this.V();this.buttonType===2&&g.jX(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.V);this.In(!0)}V(){let Z,k;switch(this.buttonType){case 1:Z="Watch again on YouTube";k=156915;break;case 2:Z="Continue watching on YouTube";k=156942;break;default:Z="Continue watching on YouTube",
k=156942}this.update({content:Z});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,k)}onClick(Z){this.S.B("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.jY(this.getVideoUrl(),this.S,Z);this.S.B("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)}getVideoUrl(){var Z=!0;switch(this.buttonType){case 1:Z=!0;break;case 2:Z=!1}Z=this.S.getVideoUrl(Z,!1,!1,!0);const k=
this.S.X();if(g.PQ(k)){const N={};g.PQ(k)&&g.H3(this.S,"addEmbedsConversionTrackingParams",[N]);Z=g.mW(Z,N)}return Z}logVisibility(){this.S.logVisibility(this.element,this.LF&&this.Vz)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Df(Z){super.Df(Z);this.logVisibility()}};var fZe=class extends tS{constructor(Z){super(Z,"watch-again-on-youtube-endscreen");this.watchButton=new lZc(Z);g.u(this,this.watchButton);this.watchButton.HD(this.element);g.ahb(Z)&&(this.V=new g.L_F(Z),g.u(this,this.V),this.U=new g.E({J:"div",BD:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},A:[this.V]}),g.u(this,this.U),this.V.HD(this.U.element),this.U.HD(this.element));Z.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.V?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const k=this.U;if(k){var Z=this.V.hasSuggestions();g.D(this.element,"ytp-shorts-branded-ui",Z);Z?k.show():k.hide()}g.Vn(this.player)?.bM(!0);this.player.logVisibility(this.element,!0);this.watchButton.Df(!0)}}hide(){super.hide();g.Vn(this.player)?.bM(!1);this.player.logVisibility(this.element,!1);this.watchButton.Df(!1)}};g.o1("endscreen",class extends g.oS{constructor(Z){super(Z);this.endScreen=null;this.V=this.U=this.D=!1;this.listeners=new g.tt(this);g.u(this,this.listeners);const k=Z.X();Z.isEmbedsShortsMode()?this.endScreen=new fZe(Z):cZr(Z)?(this.D=!0,H_i(this),this.V?this.endScreen=new VCa(Z):k.B("delhi_modern_endscreen")?this.endScreen=new Fce(Z):this.endScreen=new u9i(Z)):k.j9?this.endScreen=new tC_(Z):this.endScreen=new tS(Z);g.u(this,this.endScreen);g.$n(Z,this.endScreen.element,4);d7T(this);this.listeners.K(Z,
"videodatachange",this.onVideoDataChange,this);this.listeners.K(Z,g.te("endscreen"),N=>{this.onCueRangeEnter(N)});
this.listeners.K(Z,g.he("endscreen"),N=>{this.onCueRangeExit(N)})}a8(){var Z=this.player.getVideoData();
const k=Z.mutedAutoplay&&(Z.limitedPlaybackDurationInSeconds>0||Z.endSeconds>0||Z.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!k)return!0;var N=!(!Z?.N()&&!Z?.suggestions?.length);N=!cZr(this.player)||N;Z=Z.m1;const a=this.player.h4();return N&&!Z&&!a&&!k}Gc(){return this.endScreen.Gc()}un(){return this.Gc()?this.endScreen.O():!1}YW(){this.player.jl("endscreen");super.YW()}load(){{const N=this.player.getVideoData(),a=N.transitionEndpointAtEndOfStream;if(a&&a.videoId){var Z=
this.player.GZ().Es.get("heartbeat");var k=N.N();!k||a.videoId!==k.videoId||N.us?(this.player.CP(a.videoId,void 0,void 0,!0,!0,a),Z&&Z.uK("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),Z=!0):Z=!1}else Z=!1}Z||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(Z){this.a8()&&(this.endScreen.created||this.endScreen.create(),Z.getId()==="load"&&this.load())}onCueRangeExit(Z){Z.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){d7T(this);this.D&&H_i(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.V?this.endScreen=new VCa(this.player):this.endScreen=new u9i(this.player),g.u(this,this.endScreen),g.$n(this.player,this.endScreen.element,4))}});})(_yt_player);
