(function(g){var window=this;'use strict';var tr=function(Z){Z.publish("cardstatechange",Z.pm()&&Z.hh()?1:0)},hr=function(Z,k){var N=g.uf(k);
const a=N?k:arguments;for(N=N?0:1;N<a.length;N++){if(Z==null)return;Z=Z[a[N]]}return Z},VAr=function(Z){const k=g.zU(Z);
Z=g.I4(Z);return new g.DJ(k.x,k.y,Z.width,Z.height)},F_i=function(Z,k,N){let a;
return a=g.R6(Z,k,function(){g.nE(a);N.apply(Z,arguments)},{})},fT=function(Z){Z=g.By(Z);
delete ug[Z];g.ze(ug)&&lg&&lg.stop()},hMF=function(){lg||(lg=new g.Uc(function(){tAn()},20));
const Z=lg;Z.isActive()||Z.start()},tAn=function(){var Z=g.vy();
g.BB(ug,function(k){uMB(k,Z)});
g.ze(ug)||hMF()},BN=function(Z,k,N,a){g.kN.call(this);
if(!Array.isArray(Z)||!Array.isArray(k))throw Error("Start and end parameters must be arrays");if(Z.length!=k.length)throw Error("Start and end points must be the same length");this.U=Z;this.j=k;this.duration=N;this.L=a;this.coords=[];this.progress=this.G=0;this.Y=null},uMB=function(Z,k){k<Z.startTime&&(Z.endTime=k+Z.endTime-Z.startTime,Z.startTime=k);
Z.progress=(k-Z.startTime)/(Z.endTime-Z.startTime);Z.progress>1&&(Z.progress=1);Z.G=1E3/(k-Z.Y);Z.Y=k;lJa(Z,Z.progress);Z.progress==1?(Z.V=0,fT(Z),Z.onFinish(),Z.zU()):Z.isPlaying()&&Z.IA()},lJa=function(Z,k){typeof Z.L==="function"&&(k=Z.L(k));
Z.coords=Array(Z.U.length);for(let N=0;N<Z.U.length;N++)Z.coords[N]=(Z.j[N]-Z.U[N])*k+Z.U[N]},fJi=function(Z,k){g.kE.call(this,Z);
this.coords=k.coords;this.x=k.coords[0];this.y=k.coords[1];this.z=k.coords[2];this.duration=k.duration;this.progress=k.progress;this.fps=k.G;this.state=k.V},Dg=function(Z,k,N,a,T){BN.call(this,k,N,a,T);
this.element=Z},O4=function(Z,k,N,a,T){if(k.length!=2||N.length!=2)throw Error("Start and end points must be 2D");
Dg.call(this,Z,k,N,a,T)},BMB=function(Z){return Math.pow(Z,3)},DiT=function(Z){return 3*Z*Z-2*Z*Z*Z},vN=function(Z){return Z.baseUrl||null},ig=function(Z,k){return g.Ry(g.ni(Z,k),N=>!!N)},O1c=function(Z,k,N){function a(hy){var zf=hy.hovercardButton;
if(!zf)return null;zf=zf.subscribeButtonRenderer;if(!zf)return null;const MR=K(zf.unsubscribedButtonText),OD=K(zf.subscribedButtonText);let Ur,tg;zf.subscribed?(Ur=K(zf.subscriberCountWithUnsubscribeText),tg=K(zf.subscriberCountText)):(Ur=K(zf.subscriberCountText),tg=K(zf.subscriberCountWithSubscribeText));let b0=null;return hy.signinEndpoint&&((b0=hr(hy,"signinEndpoint","webNavigationEndpointData","url"))||(b0=g.J(zf.signInEndpoint?.commandMetadata,g.f4)?.url),!b0)?null:MR&&(OD||b0)?{subscribed:zf.subscribed,
subscribeText:MR,subscribeCount:Ur,unsubscribeText:OD,unsubscribeCount:tg,enabled:zf.enabled,signinUrl:b0,classic:hy.useClassicSubscribeButton}:null}
function T(hy){if(hy){var zf=[],MR=hy.videoId;MR&&zf.push("v="+MR);(MR=hy.playlistId)&&zf.push("list="+MR);(hy=hy.startTimeSeconds)&&zf.push("t="+hy);return"/watch?"+zf.join("&")}}
function K(hy){if(!hy)return null;const zf=hy.simpleText;return zf?zf:hy.runs?g.ni(hy.runs,MR=>MR.text).join(""):null}
k=k.endscreenElementRenderer;if(!k)return null;const y=k.style,Q=k.endpoint||{};let q=null;var r=null,C=!1;let m=null,A=null,P=null,d=null;var h=!1;let B=null,v=null;var O=null;let x=null,e=null,Ki=null;if(y==="VIDEO")g.J(Q,g.Fh)?q=g.J(Q,g.Fh).url:(Ki=g.J(Q,g.d9),q=T(Ki)),r=!1,m=Z,k.thumbnailOverlays?(C=k.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,A=K(C.text),C=C.style==="LIVE"):A=K(k.videoDuration);else if(y==="PLAYLIST")g.J(Q,g.Fh)?q=g.J(Q,g.Fh).url:(Ki=g.J(Q,g.d9),q=T(Ki)),r=!1,m=
Z,P=K(k.playlistLength);else if(y==="CHANNEL"){if(h=hr(Q,"browseEndpoint","browseId"))d=h,q=`/channel/${d}`;r=!1;m="new";(h=!!k.isSubscribe)?B=a(k):v=K(k.subscribersText)}else y==="WEBSITE"?((O=hr(Q,"urlEndpoint","url"))&&(q=O),r=!0,m="new",O=k.icon.thumbnails[0].url):y==="CREATOR_MERCHANDISE"&&(k.productPrice&&(x=K(k.productPrice)),k.additionalFeesText&&(e=K(k.additionalFeesText)),(r=hr(Q,"urlEndpoint","url"))&&(q=r),r=!0,m="new");Z=hr(k,"title","accessibility","accessibilityData","label");const yf=
k.endpoint?k.endpoint.clickTrackingParams:null;let Jy="";if(k.metadata){const hy=K(k.metadata);hy&&(Jy=hy)}return{id:`element-${N}`,type:y,title:K(k.title),metadata:Jy,callToAction:K(k.callToAction),O_:k.image,iconUrl:O,left:Number(k.left),width:Number(k.width),top:Number(k.top),aspectRatio:Number(k.aspectRatio),startMs:Math.floor(Number(k.startMs)),endMs:Math.floor(Number(k.endMs)),videoDuration:A,rK:C,playlistLength:P,channelId:d,subscribeButton:B,subscribersText:v,isSubscribe:h,targetUrl:q||null,
wX:r,sessionData:yf?{itct:yf}:null,wO:m,NO:Z?Z:null,isPlaceholder:k.isPlaceholder,impressionUrls:ig(k.impressionUrls||[],vN),tG:ig(k.hovercardShowUrls||[],vN),clickUrls:ig(Q.loggingUrls||[],vN),visualElement:g.yz(k.trackingParams),productPrice:x,additionalFeesText:e,watchEndpoint:Ki||null}},gD=function(Z,k){const N={startMs:Math.floor(Number(Z.startMs)),
impressionUrls:ig(Z.impressionUrls||[],vN),elements:ig(Z.elements||[],(a,T)=>O1c(k,a,T))};
Z.trackingParams&&(N.visualElement=g.yz(Z.trackingParams));return N},wD=function(Z){return Z.player.X().playerStyle==="creator-endscreen-editor"},v1r=function(Z){return Z.player.getVideoData().o4?"current":Z.N?"new":"current"},$D=function(Z,k,N=!0){Z.player.jl("creatorendscreen");
Z.D&&(Z.D.dispose(),Z.D=null,Z.L.dispose(),Z.L=null);for(var a of Object.values(Z.U))a.dispose();Z.U={};Z.G={};Z.C.length>0&&(Z.C.forEach(T=>{T.dispose()}),Z.C.length=0);
Z.V&&(g.Wp(Z.V,"ytp-ce-element-show"),Z.V.setAttribute("aria-hidden","true"));Z.j=0;if((Z.endscreen=k)&&k.elements){N&&i1c(Z);N=[];a=new g.pe(k.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});N.push(a);Z.player.X().U||(Z.D=new g.E({J:"div",Z:"ytp-ce-shadow"}),g.$n(Z.player,Z.D.element,4),Z.L=new g.ML(Z.D,200));for(a=0;a<k.elements.length;++a){const T=k.elements[a],K=g1D(Z,T);if(!K){g.L9(new g.jD("buildEndscreenElement null",T));continue}Z.U[T.id]=K;Z.G[T.id]=T;g.$n(Z.player,
K.element,4);const y=new g.pe(T.startMs,T.endMs,{id:"ytp-ce-element-"+T.id,namespace:"creatorendscreen"});N.push(y);wKH(Z,K,T)}Z.player.f8(N);Z.qx()}},$iT=function(Z){var k=Z.player.getVideoData(),N=k.videoId;
Z.Y&&Z.Y.abort();N={method:"POST",onFinish:T=>{var K=Z.Y=null;T.status===200&&(T=T.responseText,T.substring(0,3)===")]}"&&(T=T.substring(3),K=JSON.parse(T),K=gD(K,v1r(Z))));$D(Z,K)},
urlParams:{v:N},withCredentials:!0};Z.N&&(N.urlParams.ptype="embedded");const a=k.NT;a&&(N.postParams={ad_tracking:a});if(k=g.EBy(k))if(k=g.GI(k),k=g.gI(k))Z.Y=g.SD(k,N)},i1c=function(Z){const k=g.rl(),N=g.C9();
N&&k&&Z.endscreen.visualElement&&g.ai(g.wl)(void 0,N,k,Z.endscreen.visualElement)},g1D=function(Z,k){var N=null;
switch(k.type){case "VIDEO":Z={J:"div",BD:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":k.NO||"","aria-hidden":"true"},A:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-covering-image",W:xD(k)},{J:"div",Z:"ytp-ce-covering-shadow-top"},{J:"a",Z:"ytp-ce-covering-overlay",W:{href:G6(Z,k.targetUrl),tabindex:"-1"},A:[{J:"div",BD:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.rQ(k.title||"")},Da:k.title},{J:"div",Z:k.rK?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Da:k.videoDuration||void 0}]}]};N=new g.E(Z);break;case "PLAYLIST":Z={J:"div",BD:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":k.NO||"","aria-hidden":"true"},A:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-covering-image",W:xD(k)},{J:"div",Z:"ytp-ce-covering-shadow-top"},{J:"a",Z:"ytp-ce-covering-overlay",W:{href:G6(Z,k.targetUrl),tabindex:"-1"},A:[{J:"div",BD:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.rQ(k.title||"")},Da:k.title},{J:"div",Z:"ytp-ce-playlist-count",
A:[{J:"div",Z:"ytp-ce-playlist-icon"},{J:"div",Z:"ytp-ce-playlist-count-text",Da:k.playlistLength||void 0}]}]}]};N=new g.E(Z);break;case "CHANNEL":N={J:"div",BD:["ytp-ce-element","ytp-ce-channel",k.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":k.NO||"","aria-hidden":"true"},A:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",A:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",
A:[{J:"div",Z:"ytp-ce-expanding-overlay-body",A:[{J:"div",Z:"ytp-ce-expanding-overlay-body-padding",A:[{J:"a",BD:["ytp-ce-channel-title","ytp-ce-link"],W:{href:G6(Z,k.targetUrl),target:"_blank",tabindex:"-1",dir:g.rQ(k.title||"")},Da:k.title},k.subscribeButton?{J:"div",Z:"ytp-ce-subscribe-container",A:[{J:"div",Z:"ytp-ce-channel-subscribe"}]}:"",k.subscribersText?{J:"div",Z:"ytp-ce-channel-subscribers-text",Da:k.subscribersText}:"",k.metadata?{J:"div",BD:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Da:k.metadata}:""]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",W:xD(k)}]};N=new g.E(N);const T=g.Rk(document,"div","ytp-ce-channel-subscribe",N.element)[0];if(k.subscribeButton&&k.channelId){g.jX(T,"ytp-ce-subscribe-button");let K;if(Z.player.X().U){var a=null;K=k.sessionData.itct}else a="endscreen",K=null;a=new g.Lz(k.subscribeButton.subscribeText,k.subscribeButton.subscribeCount,k.subscribeButton.unsubscribeText,k.subscribeButton.unsubscribeCount,!!k.subscribeButton.enabled,!!k.subscribeButton.classic,
k.channelId,!!k.subscribeButton.subscribed,a,K,Z.player,!1);T.appendChild(a.element);Z.C.push(a)}break;case "WEBSITE":Z={J:"div",BD:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":k.NO||"","aria-hidden":"true"},A:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",A:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",A:[{J:"div",Z:"ytp-ce-expanding-overlay-body",A:[{J:"div",
Z:"ytp-ce-expanding-overlay-body-padding",A:[{J:"div",Z:"ytp-ce-website-title",W:{dir:g.rQ(k.title||"")},Da:k.title},{J:"div",Z:"ytp-ce-website-metadata",Da:k.metadata},{J:"a",BD:["ytp-ce-website-goto","ytp-ce-link"],W:{href:G6(Z,k.targetUrl),target:"_blank",tabindex:"-1"},Da:k.callToAction}]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",W:xD(k)},{J:"div",Z:"ytp-ce-expanding-icon",W:xiJ(k.iconUrl)}]};N=new g.E(Z);break;case "CREATOR_MERCHANDISE":N="",k.productPrice&&(N={J:"div",Z:"ytp-ce-merchandise-price-container",
A:[{J:"div",Z:"ytp-ce-merchandise-price",Da:k.productPrice}]},k.additionalFeesText&&N.A.push({J:"div",Z:"ytp-ce-merchandise-additional-fees",Da:k.additionalFeesText})),Z={J:"div",BD:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":k.NO||"","aria-hidden":"true"},A:[{J:"div",Z:"ytp-ce-element-shadow"},{J:"div",Z:"ytp-ce-expanding-overlay",A:[{J:"div",Z:"ytp-ce-expanding-overlay-hider"},{J:"div",Z:"ytp-ce-expanding-overlay-background"},{J:"div",Z:"ytp-ce-expanding-overlay-content",
A:[{J:"div",Z:"ytp-ce-expanding-overlay-body",A:[{J:"div",Z:"ytp-ce-expanding-overlay-body-padding",A:[{J:"div",Z:"ytp-ce-merchandise-title",W:{dir:g.rQ(k.title||"")},Da:k.title},N,{J:"div",Z:"ytp-ce-merchandise-metadata",Da:k.metadata},{J:"a",BD:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:G6(Z,k.targetUrl),target:"_blank",tabindex:"-1"},Da:k.callToAction}]}]}]}]},{J:"div",Z:"ytp-ce-expanding-image",W:xD(k)},{J:"div",Z:"ytp-ce-merchandise-invideo-cta-container",A:[{J:"div",Z:"ytp-ce-merchandise-invideo-cta",
Da:k.callToAction||void 0}]}]},N=new g.E(Z)}k.isPlaceholder&&g.jX(N.element,"ytp-ce-placeholder");return N},wKH=function(Z,k,N){function a(){y(1)}
function T(){y(-1)}
k.listen("mouseenter",()=>{S8(Z,k,N)});
k.listen("mouseleave",()=>{e8(Z,k,N)});
Z.player.X().U||k.listen("click",()=>{g.jX(k.element,"ytp-ce-element-hover")});
k.listen("click",Q=>{GUD(Z,N,Q)});
k.listen("keypress",Q=>{GUD(Z,N,Q)});
k.listen("focus",()=>{S8(Z,k,N)});
k.listen("blur",()=>{e8(Z,k,N)});
k.listen("touchstart",()=>{S8(Z,k,N)});
var K=g.Mc("ytp-ce-expanding-overlay-hider",k.element);K&&k.K(K,"touchstart",Q=>{Q.stopPropagation();g.Wp(k.element,"ytp-ce-element-hover");g.Wp(k.element,"ytp-ce-force-expand")});
k.listen("keydown",Q=>{Z.Vz=Q.keyCode===9&&!Q.shiftKey});
const y=Q=>{Z.j+=Q;Z.j>0?(g.jX(k.element,"ytp-ce-force-expand"),ow(Z,N.id,!0)):(g.Wp(k.element,"ytp-ce-force-expand"),g.Wp(k.element,"ytp-ce-element-hover"),ow(Z,N.id,!1))};
K=Q=>{Q&&(k.listen("blur",()=>{Q.style.display!="none"&&Z.Vz&&Q.focus()}),k.K(Q,"focus",a),k.K(Q,"blur",T))};
K(g.Mc("ytp-sb-subscribe",k.element));K(g.Mc("ytp-sb-unsubscribe",k.element));k.listen("focus",a);k.listen("blur",T)},Jr=function(Z,k,N){function a(){K||(T++,T===k.length&&(y.stop(),N&&N()))}
if(!k||k.length===0||wD(Z))N&&N();else{k=SQJ(Z,k);var T=0,K=!1,y=new g.Uc(()=>{K=!0;N&&N()},1E3,Z);
y.start();for(Z=0;Z<k.length;Z++)g.iv(k[Z],a)}},xD=function(Z){let k;
Z.O_&&(k=Z.O_.thumbnails);return xiJ(k?k[k.length-1].url:null)},G6=function(Z,k){Z=Z.player.X();
if(k){if(k.startsWith("//"))return Z.protocol+":"+k;if(k.startsWith("/"))return g.$2(Z)+k}else return"";return k},xiJ=function(Z){return Z?{style:"background-image: url("+Z+")"}:{}},S8=function(Z,k,N){g.I3(k.element,"ytp-ce-element-hover")||(N.type==="VIDEO"||N.type==="PLAYLIST"?g.jX(k.element,"ytp-ce-element-hover"):Z.player.X().U?(new g.Uc(()=>{g.jX(k.element,"ytp-ce-element-hover")},200)).start():g.jX(k.element,"ytp-ce-element-hover"),Jr(Z,N.tG),ow(Z,N.id,!0))},e8=function(Z,k,N){g.Wp(k.element,
"ytp-ce-element-hover");
g.Wp(k.element,"ytp-ce-force-expand");ow(Z,N.id,!1)},GUD=function(Z,k,N){if(k.targetUrl&&(!N||N.type!=="keypress"||N.keyCode===13)){for(var a=N.target;a&&!g.I3(a,"ytp-ce-element");){g.I3(a,"subscribe-label")&&z6(Z,k);
if(g.I3(a,"ytp-ce-channel-subscribe"))return;a=a.parentElement||null}if(!a||g.I3(a,"ytp-ce-element-hover")){N.preventDefault();N.stopPropagation();if(a=Z.U[k.id])e8(Z,a,k),a.element.blur();if(N.ctrlKey||N.metaKey||k.wO==="new")z6(Z,k),Z.player.sendVideoStatsEngageEvent(17,void 0),Z.player.pauseVideo(),N=g.GI(G6(Z,k.targetUrl)),N=g.gI(N),g.RJ(N,void 0,k.sessionData);else{const T=g.fQ(Z.player.X())||Z.player.getVideoData().o4,K=()=>{var y=G6(Z,k.targetUrl),Q=k.sessionData,q=k.watchEndpoint;const r=
g.mm(y);T&&r&&(r.v||r.list)?Z.player.CP(r.v,Q,r.list,!1,void 0,q||void 0):g.pZ(y,Q)};
z6(Z,k,()=>{Z.player.sendVideoStatsEngageEvent(17,K)})}}}},ow=function(Z,k,N){Z.D&&(N?Z.L.show():Z.L.hide());
for(const a of Object.keys(Z.U))a!==k&&g.D(Z.U[a].element,"ytp-ce-element-shadow-show",N)},z6=function(Z,k,N){Jr(Z,k.clickUrls,N);
(Z=g.C9())&&k.wX&&g.p9(Z,k.visualElement)},SQJ=function(Z,k){var N=Z.player.getVideoData().clientPlaybackNonce;
Z=Z.player.getCurrentTime().toFixed(2);N={CPN:N,AD_CPN:N,MT:Z};Z=[];for(let a=0;a<k.length;a++)Z.push(eMH(k[a],N));return Z},eMH=function(Z,k){return Z.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,N=>{let a=unescape(N);
a=a.substring(1,a.length-1);return k[a]?escape(k[a]):N})},o1H=function(Z){return typeof Z==="string"?Z:""},U4=function(Z,k,N){for(const a in k)if(k[a]===Z)return Z;
return N},bg=function(Z){if(!Z)return null;
var k=g.GI(o1H(Z.value));k=g.gI(k);if(!k)return null;const N=U4(Z.target,JIe,"current");if(N==null)Z=null;else{var a=Z.show_link_icon;Z=new zMa(k,N,a==="true"||a==="false"?a==="true":!0,Z.pause_on_navigation!=null?Z.pause_on_navigation:!0)}return Z},RMe=function(Z){if(!Z)return null;
const k=U4(Z.type,Uih),N=U4(Z.trigger,b1e);Z=Z.url;Z=Array.isArray(Z)&&Z.length?Z[0]:Z;Z=bg(Z?Z:null);return k?new pKH(k,N,Z):null},MAJ=function(Z,k){return g.ZD(Z.action,k)},pT=function(Z,k){Z="background-image: url("+Z+");";
const N=[];k&&N.push(k);return{J:"div",Z:"iv-card-image",W:{style:Z},A:N}},Mb=function(Z){return Z.customMessage?Rw("div","iv-card-message",Z.customMessage):""},nT=function(Z){if(!Z.metaInfo||Z.metaInfo.length===0)return"";
const k=[];for(const N of Z.metaInfo)k.push(Rw("li","",N));return{J:"ul",Z:"iv-card-meta-info",A:k}},Iw=function(Z,k,N,a){if(a)for(const T of k)Z.V(T,a,N.id,N.sessionData,N.DI.click,5)},Rw=function(Z,k,N){k?typeof k==="string"?k={"class":k}:Array.isArray(k)&&(k={"class":k.join(" ")}):k={};
k.dir=g.rQ(N);return{J:Z,W:k,Da:N}},n1B=function(Z){if(!Z.customMessage)return"";
const k=["iv-card-action","iv-card-primary-link"],N={};Z.zl&&(k.push("iv-card-action-icon"),N.style="background-image: url("+Z.zl+");");N.dir=g.rQ(Z.customMessage);const a=[{J:"span",Da:Z.customMessage}];Z.showLinkIcon&&(a.push("\u00a0"),a.push({J:"span",Z:"iv-card-link-icon"}));return{J:"div",BD:k,W:N,A:a}},IJi=function(Z){var k;
(k=Z)&&!(k=Z.length>1?Z.charAt(0)==="/"&&Z.charAt(1)!=="/":Z==="/")&&(k=Z.replace(/^(https?:)?\/\//,"").split("/",1),k=!k||k.length<1||!k[0]?[]:k[0].toLowerCase().split(".").reverse(),k=k[0]==="com"&&k[1]==="youtube"||k[0]==="be"&&k[1]==="youtu");return k?Z.indexOf("/redirect?")===-1:!1},j4B=function(Z,k){return k?k:IJi(Z)?"current":"new"},j8=function(Z,k,N,a,T,K,y){Z.context.V.listen(k,"click",Q=>{Z.Kp(N,a,T,K||[],y||0,Q)});
Z.context.V.listen(k,"touchstart",()=>{Z.O6=!1});
Z.context.V.listen(k,"touchmove",()=>{Z.O6=!0})},E1H=function(Z){if(g.J(Z,g.Fh)?.url)return g.J(Z,g.Fh).url;
if((Z=g.J(Z,g.d9))&&Z.videoId){let k="/watch?v="+Z.videoId;Z.playlistId&&(k+="&list="+Z.playlistId);Z.index&&(k+="&index="+Z.index);Z.startTimeSeconds&&(k+="&t="+Z.startTimeSeconds);return k}return null},E4=function(Z,k,N){return{S1:(Z.impressionLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
click:(N.loggingUrls||[]).map(a=>a.baseUrl||""),
close:(k.dismissLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
Zu:(k.impressionLoggingUrlsV2s||[]).map(a=>a.baseUrl||""),
eS:(k.clickLoggingUrlsV2s||[]).map(a=>a.baseUrl||"")}},k0=function(Z,k){if(k.onClickCommand&&g.J(k.onClickCommand,g.jwf)?.targetId==="engagement-panel-error-corrections"){Z.O=k;
var N=!0}else N=!1;if(!N||W_n(Z,k))if(N=YQH(Z,k)){var a={ib:k,iJ:N.element,Y6:!1};if(k.onClickCommand)Z.S.B("web_infocards_teaser_show_logging_fix")&&(Z.xl||kWD(Z),WN(Z,k.id),N=Z.findLastIndex(a),g.dH(Z.cards,N,0,a));else{Z.isInitialized||Zlc(Z);WN(Z,k.id);const T=Z.findLastIndex(a);g.dH(Z.cards,T,0,a);N.HD(Z.U,T);Z.FS()}k.autoOpen?Z.addCueRange(k.startMs,0x8000000000000,k.id,()=>{Z.D||(Z.V=a,YD(Z),NPa(Z,a),ZP(Z,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(N=Z.context.S.getCurrentTime()*1E3,N<5E3&&N>k.startMs&&
atK(Z,a),Z.addCueRange(k.startMs,k.startMs+1,k.id,()=>{atK(Z,a)}),YD(Z))}},N5=function(Z){Z.D&&(Z.hq.hide(),Z.tq.U(),g.Wp(Z.context.S.getRootNode(),g.Cs.IV_DRAWER_OPEN),Z.D=!1,tr(Z.S),Z.G&&Z.G.stop(),Z.G=new g.Uc(()=>{Z.Sm&&(Z.Sm.focus(),Z.Sm=null)},330),Z.G.start())},TPi=function(Z,k){k=k.data;
k.autoOpenMs&&Z.addCueRange(k.autoOpenMs,0x8000000000000,"",()=>{ZP(Z,"YOUTUBE_DRAWER_AUTO_OPEN")});
k.autoCloseMs&&Z.addCueRange(k.autoCloseMs,0x8000000000000,"",()=>{N5(Z)});
const N=k.headerText;g.m_(Z.pF,N);Z.L&&(Z.S.B("player_tooltip_data_title_killswitch")?Z.L.setAttribute("title",N):Z.L.setAttribute("data-tooltip-title",N));k.eventId&&(Z.eventId=k.eventId);Z.vD=g.yz(k.trackingParams);Z.C=g.yz(k.closeTrackingParams);Z.NR=g.yz(k.iconTrackingParams)},aM=function(Z,k,N){let a=-1,T=-1;
for(let K=0;K<Z.length;K++){if(Z[K].height===k||Z[K].width===N)return Z[K];((Z[K].height||0)<k||(Z[K].width||0)<N)&&(a<0||(Z[a].height||0)<(Z[K].height||0)||(Z[a].width||0)<(Z[K].width||0))?a=K:((Z[K].height||0)>=k||(Z[K].width||0)>=N)&&(T<0||(Z[T].height||0)>(Z[K].height||0)||(Z[T].width||0)>(Z[K].width||0))&&(T=K)}return Z[T>=0?T:a]},TE=function(Z,k,N,a){return{feature:N.feature?N.feature:"cards",
src_vid:Z.context.videoData.videoId,annotation_id:k,ei:Z.context.videoData.eventId||"",itct:a.trackingParams||""}},K1i=function(Z,k){const N=k.cardId?k.cardId:`cr:${Z.j}`;
var a=Z.S.X().experiments.yz("enable_error_corrections_infocard_web_client");if(!k.content&&k.teaser.simpleCardTeaserRenderer&&a){a=k.teaser.simpleCardTeaserRenderer;var T=k.icon?k.icon.infoCardIconRenderer:null;if(a.channelAvatar&&a.channelAvatar.thumbnails&&a.channelAvatar.thumbnails.length>0)var K=aM(a.channelAvatar.thumbnails,22,22).url;k={id:N,timestamp:Z.j,type:"simple",teaserText:g.YL(a.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),
autoOpen:!!k.autoOpen,sessionData:{},sponsored:!1,DI:{},Th:null,nX:a.trackingParams?g.yz(a.trackingParams):null,NR:T&&T.trackingParams?g.yz(T.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,zl:null,title:"",customMessage:"",url:null,onClickCommand:a.onTapCommand||null,hJ:K};k0(Z,k)}else if(k.content?.simpleCardContentRenderer){if(!k.cueRanges.length)return;K=k.content?.simpleCardContentRenderer;a=k.teaser.simpleCardTeaserRenderer;T=k.icon?k.icon.infoCardIconRenderer:null;k={id:N,
timestamp:Z.j,type:"simple",teaserText:g.YL(a.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:TE(Z,N,k,K),sponsored:!1,DI:E4(K,a,K.command),Th:K.trackingParams?g.yz(K.trackingParams):null,nX:a.trackingParams?g.yz(a.trackingParams):null,NR:T&&T.trackingParams?g.yz(T.trackingParams):null,imageUrl:aM(K.image.thumbnails,290,290).url,displayDomain:K.displayDomain?g.YL(K.displayDomain):null,showLinkIcon:!!K.showLinkIcon,
zl:null,title:K.title?g.YL(K.title):"",customMessage:K.callToAction?g.YL(K.callToAction):"",url:g.J(K.command,g.Fh).url?bg({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:g.J(K.command,g.Fh).url}):null,onClickCommand:null};k0(Z,k)}else if(k.content?.collaboratorInfoCardContentRenderer){if(!k.cueRanges.length)return;K=k.content?.collaboratorInfoCardContentRenderer;a=k.teaser.simpleCardTeaserRenderer;T=k.icon?k.icon.infoCardIconRenderer:null;k={id:N,timestamp:Z.j,type:"collaborator",
teaserText:g.YL(a.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:TE(Z,N,k,K),sponsored:!1,DI:E4(K,a,K.endpoint),Th:K.trackingParams?g.yz(K.trackingParams):null,nX:a.trackingParams?g.yz(a.trackingParams):null,NR:T&&T.trackingParams?g.yz(T.trackingParams):null,channelId:g.J(K.endpoint,g.HZ).browseId,customMessage:K.customText?g.YL(K.customText):null,profileImageUrl:aM(K.channelAvatar.thumbnails,290,
290).url,title:K.channelName?g.YL(K.channelName):"",metaInfo:[K.subscriberCountText?g.YL(K.subscriberCountText):""],url:bg({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:g.J(K.endpoint,g.HZ).canonicalBaseUrl?g.J(K.endpoint,g.HZ).canonicalBaseUrl:`/channel/${g.J(K.endpoint,g.HZ).browseId}`}),onClickCommand:null};k0(Z,k)}else if(k.content?.playlistInfoCardContentRenderer){if(!k.cueRanges.length)return;K=k.content?.playlistInfoCardContentRenderer;a=k.teaser.simpleCardTeaserRenderer;
T=k.icon?k.icon.infoCardIconRenderer:null;k={id:N,timestamp:Z.j,type:"playlist",teaserText:g.YL(a.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:TE(Z,N,k,K),sponsored:!1,DI:E4(K,a,K.action),Th:K.trackingParams?g.yz(K.trackingParams):null,nX:a.trackingParams?g.yz(a.trackingParams):null,NR:T&&T.trackingParams?g.yz(T.trackingParams):null,n7:aM(K.playlistThumbnail.thumbnails,258,290).url,customMessage:K.customMessage?
g.YL(K.customMessage):null,playlistVideoCount:g.YL(K.playlistVideoCount),title:K.playlistTitle?g.YL(K.playlistTitle):"",metaInfo:[K.channelName?g.YL(K.channelName):"",K.videoCountText?g.YL(K.videoCountText):""],url:bg({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:E1H(K.action)}),onClickCommand:null};k0(Z,k)}else if(k.content?.videoInfoCardContentRenderer){if(!k.cueRanges.length)return;K=k.content?.videoInfoCardContentRenderer;a=k.teaser.simpleCardTeaserRenderer;T=k.icon?
k.icon.infoCardIconRenderer:null;k={id:N,timestamp:Z.j,type:"video",teaserText:g.YL(a.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:TE(Z,N,k,K),sponsored:!1,DI:E4(K,a,K.action),Th:K.trackingParams?g.yz(K.trackingParams):null,nX:a.trackingParams?g.yz(a.trackingParams):null,NR:T&&T.trackingParams?g.yz(T.trackingParams):null,n7:aM(K.videoThumbnail.thumbnails,258,290).url,videoDuration:K.lengthString?
g.YL(K.lengthString):null,customMessage:K.customMessage?g.YL(K.customMessage):null,title:K.videoTitle?g.YL(K.videoTitle):"",metaInfo:[K.channelName?g.YL(K.channelName):"",K.viewCountText?g.YL(K.viewCountText):""],isLiveNow:!!K.badge,url:bg({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:E1H(K.action)}),onClickCommand:null};k0(Z,k)}Z.j++},yx_=function(Z,k){return g.ZD(Z.cards,N=>N.ib.id===k)},YD=function(Z){g.D(Z.S.getRootNode(),"ytp-cards-shopping-active",QIr(Z))},WN=function(Z,
k){if(k=yx_(Z,k))k===Z.V&&(Z.V=null),Z.S.removeCueRange(k.ib.id),g.rM(k.iJ),g.qF(Z.cards,k),Z.FS(),YD(Z)},ZP=function(Z,k,N){if(!Z.D){Z.hq.show();
Z.MX=new g.Uc(()=>{g.jX(Z.context.S.getRootNode(),g.Cs.IV_DRAWER_OPEN)},0);
Z.MX.start();Z.tq.K(Z.U,"mousewheel",T=>{Z.dA.start();T.preventDefault();T=T||window.event;let K=0;T.type=="MozMousePixelScroll"?K=0==(T.axis==T.HORIZONTAL_AXIS)?T.detail:0:window.opera?K=T.detail:K=T.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?T.wheelDeltaY/-30:T.wheelDeltaY/-1.2:T.wheelDelta/-1.6:T.wheelDeltaY/-3;if(T=K)Z.U.scrollTop+=T});
Z.D=!0;var a=g.C9();a&&Z.vD&&Z.C&&g.U5(a,[Z.vD,Z.C]);k={TRIGGER_TYPE:k};for(const T of Z.cards)T.Y6||(T.Y6=!0,qmH(Z.context.logger,T.ib.DI.S1,k)),a&&g.U5(a,[T.ib.Th]);tr(Z.S);N&&(Z.G=new g.Uc(()=>{Z.Sm=Z.L;Z.qX.focus()},330),Z.G.start())}},Zlc=function(Z){g.Ec(Z.lq(),[g.Cs.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$n(Z.S,Z.Y,5);Z.YI();Z.L=g.Mc("ytp-cards-button",Z.S.getRootNode());Z.qX=g.Mc("iv-drawer-close-button",Z.Y);Z.isInitialized=!0},kWD=function(Z){Z.Vz.push(g.Rj("iv-teaser-shown",Z.jY,Z));
Z.Vz.push(g.Rj("iv-teaser-hidden",Z.ov,Z));Z.Vz.push(g.Rj("iv-teaser-clicked",Z.HA,Z));Z.xl=!0},W_n=function(Z,k){Z.O=k;
var N=Z.S.getVideoData();if(!N)return!1;N=g.Zk(N);if(N?.markersMap)for(let T=0;N?.markersMap.length>T;T++){var a=N?.markersMap[T];if(a.key==="ERROR_CORRECTION_MARKERS"&&(a=a.value?.markers)&&a.length>0)return k.startMs=g.J(a[0],g.dpf)?.timeRangeStartMillis||0,Z.O=null,!0}return!1},YQH=function(Z,k){switch(k.type){case "simple":Z=Z.xW;
var N=k.displayDomain?{J:"div",Z:"iv-card-image-text",Da:k.displayDomain}:void 0;var a=n1B(k);N={J:"div",BD:["iv-card"],A:[{J:"a",Z:"iv-click-target",W:{href:k.url?k.url.V()||"":""},A:[pT(k.imageUrl,N),{J:"div",Z:"iv-card-content",A:[Rw("h2",void 0,k.title),a]}]}]};N=new g.E(N);Iw(Z,g.pg("iv-click-target",N.element),k,k.url);k=N;break;case "collaborator":Z=Z.xW;N={J:"div",BD:["iv-card","iv-card-channel"],A:[{J:"a",BD:["iv-click-target"],W:{href:k.url.V()||"","data-ytid":k.channelId},A:[pT(k.profileImageUrl),
{J:"div",Z:"iv-card-content",A:[Mb(k),{J:"h2",Z:"iv-card-primary-link",Da:k.title},nT(k)]}]}]};N=new g.E(N);Iw(Z,g.pg("iv-click-target",N.element),k,k.url);k=N;break;case "playlist":Z=Z.xW;N={J:"div",BD:["iv-card","iv-card-playlist"],A:[{J:"a",Z:"iv-click-target",W:{href:k.url.V()||""},A:[pT(k.n7,{J:"div",Z:"iv-card-image-overlay",A:[{J:"span",Z:"iv-card-playlist-video-count",Da:k.playlistVideoCount}]}),{J:"div",Z:"iv-card-content",A:[Mb(k),Rw("h2","iv-card-primary-link",k.title),nT(k)]}]}]};N=new g.E(N);
Iw(Z,g.pg("iv-click-target",N.element),k,k.url);k=N;break;case "productListing":Z=Z.xW;var T=k.offers.length!=0;N=["iv-card"];a="";var K=n1B(k);T&&(N.push("iv-card-product-listing"),a="iv-card-primary-link",K=k.offers[0],T=[],K.price&&T.push({J:"div",Z:"iv-card-offer-price",Da:K.price}),K.merchant&&T.push({J:"div",Z:"iv-card-offer-merchant",Da:K.merchant}),K={J:"div",A:T});T=k.url?k.url.V()||"":"";N={J:"div",BD:N,W:{tabindex:"0"},A:[{J:"a",BD:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
k.imageUrl+");",href:T,"aria-hidden":"true",tabindex:"-1"}},{J:"div",Z:"iv-card-content",A:[k.sponsored?{J:"div",Z:"iv-card-sponsored",A:["Sponsored",{J:"div",Z:"iv-ad-info-container",A:[{J:"div",Z:"iv-ad-info",Da:"{{adInfo}}"},{J:"div",Z:"iv-ad-info-icon-container",A:[{J:"div",Z:"iv-ad-info-icon"},{J:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{J:"a",Z:"iv-click-target",W:{href:T},A:[Rw("h2",a,k.title),K]}]}]};N=new g.E(N);a=g.TU("span");g.m_(a,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
N.setContent(a,"adInfo");Iw(Z,g.pg("iv-click-target",N.element),k,k.url);k=N;break;case "video":Z=Z.xW;N=k.isLiveNow?{J:"span",BD:["yt-badge","yt-badge-live"],Da:"LIVE NOW"}:null;N={J:"div",BD:["iv-card","iv-card-video"],A:[{J:"a",Z:"iv-click-target",W:{href:k.url?.V()||""},A:[pT(k.n7,k.videoDuration?{J:"span",Z:"iv-card-video-duration",Da:k.videoDuration}:void 0),{J:"div",Z:"iv-card-content",A:[Mb(k),Rw("h2","iv-card-primary-link",k.title),nT(k),N]}]}]};N=new g.E(N);Iw(Z,g.pg("iv-click-target",N.element),
k,k.url);k=N;break;default:return null}return k},atK=function(Z,k){if(!g.I3(Z.S.getRootNode(),"ytp-cards-teaser-shown")){if(Z.V!==k){var N=g.C9(),a=Z.V?Z.V.ib.NR:Z.NR;
N&&a&&g.bA(N,[a]);Z.V=k;YD(Z)}(N=Z.isInitialized&&Z.lq().style.display=="none")||(N=Z.context.S.getPlayerState(),a=N===0&&Z.context.S.getCurrentTime()===0,N=!(N===1||N===3||a));N||k.ib.teaserDurationMs&&Z.S.r3(!0,{teaserText:k.ib.teaserText,durationMs:k.ib.teaserDurationMs,onClickCommand:k.ib.onClickCommand,hJ:k.ib.hJ??null});Z.Tt.isActive()||((!Z.D||!Z.dA.isActive()&&Z.Rq)&&NPa(Z,k),Z.Tt.start(910+k.ib.teaserDurationMs))}},QIr=function(Z){return Z.V?Z.V.ib.type==="productListing":Z.S.B("enable_wn_infocards")?
!!Z.cards?.length&&g.Wy(Z.cards,k=>k.ib.type==="productListing"):g.Wy(Z.cards,k=>k.ib.type==="productListing")},NPa=function(Z,k){Z.N.LF?(k=new BN([0,
Z.U.scrollTop],[0,k.iJ.offsetTop],600,DiT),Z.context.D.listen(k,"animate",N=>{Z.U.scrollTop=N.y}),Z.context.D.listen(k,"finish",N=>{Z.U.scrollTop=N.y}),k.play()):(Z.N.In(!0),Z.U.scrollTop=k.iJ.offsetTop,Z.N.In(!1))},K2=function(Z){return Z.V&&Z.V.ib?Z.V.ib:Z.cards[0]&&Z.cards[0].ib?Z.cards[0].ib:null},rxa=function(Z){const k=Z.annotation.data;
"start_ms"in k&&"end_ms"in k&&Z.addCueRange(Number(k.start_ms),Number(k.end_ms),Z.annotation.id,()=>{Z.show()},()=>{Z.hide()})},CKi=function(Z,k){var N=VAr(k).width;
g.o4(k,N);N=new O4(k,[N,k.offsetTop],[N-N,k.offsetTop],200,BMB);g.u(Z,N);Z.context.D.listen(N,"begin",()=>{g.jA(k,!0)});
N.play()},Qt=function(Z,k,N){N.stopPropagation();
m3h(Z);sIJ(Z,k);Z.V.focus()},Axi=function(Z){const k=Z.annotation.data;
if(Z.annotation.style==="cta")var N=6;else if(Z.annotation.style==="video"||Z.annotation.style==="playlist")N=7;Z.G=k.collapsedelay_ms||Z.G;const a=["iv-promo","iv-promo-inactive"];Z.lq().setAttribute("aria-hidden","true");Z.lq().setAttribute("aria-label","Promotion");Z.lq().tabIndex=0;const T=Z.annotation.mH();let K;var y=k.image_url;y&&(K=Z.createElement({J:"div",BD:["iv-promo-img","iv-click-target"]}),y=Z.createElement({J:"img",W:{src:y,"aria-hidden":"true"}}),K.appendChild(y),k.video_duration&&
!k.is_live?(y=Z.createElement({J:"span",Z:"iv-promo-video-duration",Da:k.video_duration}),K.appendChild(y)):k.playlist_length&&(y=Z.createElement({J:"span",Z:"iv-promo-playlist-length",Da:k.playlist_length.toString()}),K.appendChild(y)),T&&j8(Z,K,T,Z.annotation.id,k.session_data,void 0,N));T?(y=Z.createElement({J:"a",Z:"iv-promo-txt"}),g.o2(y,T.V()),Z.V=y):Z.V=Z.createElement({J:"div",Z:"iv-promo-txt"});let Q,q,r,C;switch(Z.annotation.style){case "cta":case "website":Q=Z.createElement({J:"p",A:[{J:"strong",
Da:k.text_line_1}]});q=Z.createElement({J:"p",A:[{J:"span",Z:"iv-promo-link",Da:k.text_line_2}]});if(y=k.text_line_3)a.push("iv-promo-website-card-cta-redesign"),r=Z.createElement({J:"button",BD:["iv-promo-round-expand-icon","ytp-button"]}),y=Z.createElement({J:"button",BD:["iv-button","iv-promo-button"],A:[{J:"span",Z:"iv-button-content",Da:y}]}),C=Z.createElement({J:"div",Z:"iv-promo-button-container"}),C.appendChild(y),T&&j8(Z,Z.lq(),T,Z.annotation.id,k.session_data,void 0,N);g.jX(Z.V,"iv-click-target");
T&&j8(Z,Z.V,T,Z.annotation.id,k.session_data,void 0,N);break;case "playlist":case "video":Q=Z.createElement({J:"p",A:[{J:"span",Da:k.text_line_1}]}),q=Z.createElement({J:"p",A:[{J:"strong",Da:k.text_line_2}]}),k.is_live&&(Q=q,q=Z.createElement({J:"span",BD:["yt-badge","iv-promo-badge-live"],Da:"LIVE NOW"})),g.jX(Z.V,"iv-click-target"),T&&j8(Z,Z.V,T,Z.annotation.id,k.session_data,void 0,N),a.push("iv-promo-video")}Q&&Z.V.appendChild(Q);q&&Z.V.appendChild(q);Z.j.appendChild(Z.V);C&&Z.j.appendChild(C);
N=Z.createElement({J:"div",Z:"iv-promo-actions"});Z.U=Z.createElement({J:"button",BD:["iv-promo-expand","ytp-button"]});Z.U.title="Expand";Z.context.V.listen(Z.U,"click",m=>{Qt(Z,5E3,m)});
N.appendChild(Z.U);g.jA(Z.U,!1);Z.context.V.listen(Z.lq(),"mouseover",Z.dA,Z);Z.context.V.listen(Z.lq(),"mouseout",Z.xW,Z);Z.context.V.listen(Z.lq(),"touchend",m=>{Qt(Z,5E3,m)});
Z.D=Z.createElement({J:"button",BD:["iv-promo-close","ytp-button"]});Z.D.title="Close";Z.context.V.listen(Z.D,"click",Z.annotation.style==="cta"&&k.text_line_3?Z.O:Z.Vz,Z);N.appendChild(Z.D);g.Ec(Z.lq(),a);K&&(g.yp(Z.lq(),K),r&&K.appendChild(r));g.yp(Z.lq(),Z.j);g.yp(Z.lq(),N)},q5=function(Z){Z.Y&&(g.dX.clearTimeout(Z.Y),Z.Y=null)},m3h=function(Z){Z.L.stop();
Z.isCollapsed&&(g.Y3(Z.lq(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),Z.isCollapsed=!1,Z.V&&Z.V.removeAttribute("aria-hidden"),g.jA(Z.U,!1),g.jA(Z.D,!0))},sIJ=function(Z,k){Z.Y||(Z.Y=g.W2(function(){q5(this);
PKa(this)},k,Z))},PKa=function(Z){Z.isCollapsed||Z.C||Z.Y||(g.jX(Z.lq(),"iv-promo-collapsed"),Z.isCollapsed=!0,Z.L.start())},qmH=function(Z,k,N){k&&(N?rG(Z,k.map(a=>g.hm(a,N))):rG(Z,k))},rG=function(Z,k,N,a){let T=1,K=void 0,y=-1;
if(N){let Q=!1;K=()=>{T--;T||Q||(clearTimeout(y),Q=!0,N())};
y=setTimeout(()=>{Q=!0;N()},1E3)}for(const Q of k||[])T++,g.iv(Q,K);
a&&(T++,a!==0&&Z.S.sendVideoStatsEngageEvent(a,K))},cxJ=function(Z){return Z==="annotation-editor"||Z==="live-dashboard"},Hln=function(Z){Z.Y&&(Z.player.removeEventListener("videodatachange",Z.Y),Z.Y=null)},d3H=function(Z){Z=Z.createElement({J:"div",
BD:["annotation","annotation-type-custom"]});g.jA(Z,!1);return Z},mI=function(Z,k){var N=!1,a=k.getElementsByTagName("annotations");
if(a&&!(a.length<1)&&(a=a[0].getAttribute("itct"))){var T=g.C9();if(T){var K=g.rl();K&&g.ai(g.gl)(void 0,T,K,[g.yz(a)])}}k=k.getElementsByTagName("annotation");for(a=0;a<k.length;a++){var y=XFK(Z,k[a]);T=null;try{a:{if(!y){T=null;break a}var Q=y.id;K=/.+/;const P=typeof Q==="string"&&K!=null&&Q!=null&&Q.match(K)?Q:"",d=U4(y.type,L1e),h=U4(y.style,VvK),B=o1H(y.data),v=B.length!==0?JSON.parse(B):{};b:{var q=y.action;K=RMe;if(q==null){var r=null;break b}if(g.uf(q)){y=[];for(const x of q){const e=K(x);
e&&y.push(e)}r=y;break b}const O=K(q);r=O?[O]:[]}K=r;T=P&&d?new F1h(P,d,h,K,v):null}}catch(P){}if(T)if(T.type==="branding"||T.type==="promotion"){K=Z;y=T;var C=d3H(K),m=null;switch(y.type){case "branding":if(K.player.X().Ap)break;K.player.B("web_player_overlay_positioned_layout")?(C.setAttribute("data-overlay-order","11"),K.player.B0(C,4,!0)):K.U.element.appendChild(C);m=new tvc(C,C2(K),y);break;case "promotion":g.$n(K.player,C,4),m=new hNK(C,C2(K),y)}m&&m.zt();if(K=m)g.u(Z,K),Z.G[T.id]=K}else if(T.type===
"card"||T.type==="drawer"){Z.V||(Z.V=urH(Z),g.u(Z,Z.V));if(T.type==="card"){C=Z.V;var A=(N=T)&&N.data&&N.data.card_type;T=N.data;if(A)switch(K=T.tracking||{},K={S1:K.impression,click:K.click,close:K.close,Zu:K.teaser_impression,eS:K.teaser_click},y=T.tracking_params||{},m=null,A){case "collaborator":N={id:N.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||
!1,DI:K,Th:y.card?g.yz(y.card):null,nX:y.teaser?g.yz(y.teaser):null,NR:y.icon?g.yz(y.icon):null,channelId:T.channel_id,customMessage:T.custom_message?T.custom_message:null,profileImageUrl:T.image_url,title:T.title,metaInfo:T.meta_info,url:bg({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};k0(C,N);break;case "playlist":N={id:N.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,
autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,DI:K,Th:y.card?g.yz(y.card):null,nX:y.teaser?g.yz(y.teaser):null,NR:y.icon?g.yz(y.icon):null,n7:T.image_url,playlistVideoCount:T.playlist_video_count,customMessage:T.custom_message?T.custom_message:null,title:T.title,metaInfo:T.meta_info,url:bg({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};k0(C,N);break;case "productListing":T.signin_url&&(m=bg({target:"current",
value:T.signin_url}));A=[];const P=T.offers||[];for(let d=0;d<P.length;d++)A.push(new lte(g.qc(P[d].merchant),g.qc(P[d].price)));N={id:N.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,DI:K,Th:y.card?g.yz(y.card):null,nX:y.teaser?g.yz(y.teaser):null,NR:y.icon?g.yz(y.icon):null,imageUrl:T.image_url,displayDomain:T.display_domain?T.display_domain:
null,showLinkIcon:!!T.show_link_icon,zl:T.button_icon_url?T.button_icon_url:null,title:T.title,customMessage:T.custom_message?T.custom_message:null,url:bg({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),MOX:m,iN3:T.signin_title?T.signin_title:void 0,CxR:T.signin_message?T.signin_message:void 0,offers:A,onClickCommand:null};k0(C,N);break;case "simple":N={id:N.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,
startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,DI:K,Th:y.card?g.yz(y.card):null,nX:y.teaser?g.yz(y.teaser):null,NR:y.icon?g.yz(y.icon):null,imageUrl:T.image_url,displayDomain:T.display_domain?T.display_domain:null,showLinkIcon:!!T.show_link_icon,zl:T.button_icon_url?T.button_icon_url:null,title:T.title,customMessage:T.custom_message?T.custom_message:null,url:bg({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};
k0(C,N);break;case "video":N={id:N.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,DI:K,Th:y.card?g.yz(y.card):null,nX:y.teaser?g.yz(y.teaser):null,NR:y.icon?g.yz(y.icon):null,n7:T.image_url,videoDuration:T.video_duration||null,customMessage:T.custom_message?T.custom_message:null,title:T.title,metaInfo:T.meta_info,isLiveNow:!!T.is_live_now,
url:bg({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null},k0(C,N)}}else TPi(Z.V,T);N=!0}}N&&(tr(Z.player),Z.N())},ftB=function(Z){const k=Z.player.X();
Z=Z.player.getVideoData();return(k.annotationsLoadPolicy||Z.annotationsLoadPolicy)===1&&!Z.rB||k.vD.get(Z.videoId)||Z.l9()||g.kn(Z)?!0:!1},BPr=function(Z,k){k=!k.isCued()&&!k.V(1024);
Z.U.In(k);Z.D.In(k)},ilc=function(Z,k){const N=k.videoId;
var a=K=>{var y=Z.loadNumber;Z.j=null;Z.loaded&&Z.loadNumber===y&&Z.player.getVideoData().videoId===N&&(K=g.li(K)&&K.responseXML?K.responseXML:null)&&(mI(Z,K),g.jX(Z.player.getRootNode(),"iv-module-loaded"))};
g.XI()&&(a=D3D(Z,a));const T={format:"XML",onFinish:a,onError:()=>{Z.j=null},
urlParams:{}};k.isPharma&&(T.urlParams.pharma="1");T.method="POST";T.withCredentials=!0;(a=Z.player.X().vD.get(N))&&OlJ(T,a);a=a&&a.a7;if(!k.EB||a)Z.Y=()=>{if(!Z.O)Z.onVideoDataChange(T);const K=Z.player.getVideoData();K?.j9()&&!Z.Vz&&v9a(Z,K)},Z.player.addEventListener("videodatachange",Z.Y)},Ap=function(Z,k){var N=!1;
Z.V||(Z.V=urH(Z),g.u(Z,Z.V));for(var a of k.cards||[])a.cardRenderer&&(K1i(Z.V,a.cardRenderer),N=!0);N&&(Z.player.getVideoData()?.j9()||(N=Z.V,a=k.headerText?g.YL(k.headerText):"",g.m_(N.pF,a),N.L&&(N.S.B("player_tooltip_data_title_killswitch")?N.L.setAttribute("title",a):N.L.setAttribute("data-tooltip-title",a)),N.context.videoData.eventId&&(N.eventId=N.context.videoData.eventId),N.vD=k.trackingParams?g.yz(k.trackingParams):null,N.C=k.closeButton.infoCardIconRenderer.trackingParams?g.yz(k.closeButton.infoCardIconRenderer.trackingParams):
null,N.NR=k.icon.infoCardIconRenderer.trackingParams?g.yz(k.icon.infoCardIconRenderer.trackingParams):null,Z.N()),tr(Z.player))},v9a=function(Z,k){if(k=k.getWatchNextResponse()?.cards?.cardCollectionRenderer)Z.Vz=!0,Ap(Z,k),k.headerText&&Z.Mj&&(k=g.YL(k.headerText),Z.player.B("player_tooltip_data_title_killswitch")?Z.Mj.setAttribute("title",k):Z.Mj.setAttribute("data-tooltip-title",k))},D3D=function(Z,k){return(...N)=>{Z.jm()||Z.zt.push(g.g3.IU(()=>{k(...N)}))}},OlJ=function(Z,k){Z.method="POST";
Z.postParams=Z.postParams||{};k.a7&&(Z.postParams.ic_coll=k.a7);k.IG&&(Z.postParams.ic_track=k.IG)},XFK=function(Z,k){const N={};
for(var a of k.attributes)N[a.name]=a.nodeValue;for(a=0;a<k.childNodes.length;a++){var T=k.childNodes[a];if(!g.lf(T)||T.nodeType!=1)continue;var K=void 0;if(N[T.tagName])K=N[T.tagName];else if(T.tagName==="data"){T.childNodes.length>0&&(K=T.childNodes[0].nodeValue,N[T.tagName]=typeof K==="string"?K.trim():K);continue}else K=[],N[T.tagName]=K;T&&T.tagName==="TEXT"?T.childNodes.length===1&&T.childNodes[0].nodeType===3?K.push(T.childNodes[0].nodeValue):K.push(""):T&&K.push(XFK(Z,T))}return N},C2=function(Z){if(!Z.C){const k=
new g9c(Z);
g.u(Z,k);const N=new g.Nv(Z);g.u(Z,N);Z.C=new wFB(k,N,Z.player.X(),Z.player.getVideoData(),Z.logger,Z.player,Z.Ke)}return Z.C},$3T=function(Z){const k=Z.player.getVideoData();
if(k.fI){var N=Z.player.X().vD.get(k.videoId);if(N){var a={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(T,K,y)=>{T=Z.loadNumber;K=k.videoId;Z.loaded&&Z.loadNumber===T&&Z.player.getVideoData().videoId===K&&(y=g.li(y)&&y.responseXML?y.responseXML:null)&&mI(Z,y)}};
g.XI()&&(a.onFinish=D3D(Z,a.onFinish));a.postParams={ic_only:"1"};OlJ(a,N);Z.O=!0;g.SD(k.fI,a)}}},urH=function(Z){const k=new g.E({J:"div"});
g.jA(k.element,!1);const N=new x3e(Z.player,k.element,C2(Z));g.u(N,k);k.HD(Z.U.element);N.zt();return N},GWe=function(Z,k,N,a,T){if(!Z.player.X().Ap){var K=[];
k.navigationEndpoint&&g.J(k.navigationEndpoint,g.HZ)&&g.J(k.navigationEndpoint,g.HZ).browseId&&K.push(new pKH("openUrl","click",new zMa(`/channel/${g.J(k.navigationEndpoint,g.HZ).browseId}`,"new",!0,!0)));var y=k.watermark.thumbnails[0];a={channel_name:k.channelName,end_ms:k.endTimeMs,image_height:y.height,image_type:1,image_url:y.url,image_width:y.width,is_mobile:!1,session_data:{annotation_id:N,ei:T,feature:"iv",itct:k.trackingParams,src_vid:a},start_ms:k.startTimeMs};if(k.subscribeButton&&g.J(k.subscribeButton,
g.Dk)){a.channel_id=g.J(k.subscribeButton,g.Dk).channelId;k=g.J(k.subscribeButton,g.Dk);y=T=null;k.subscribed?(k.subscriberCountWithUnsubscribeText&&(T=g.YL(k.subscriberCountWithUnsubscribeText)),k.subscriberCountText&&(y=g.YL(k.subscriberCountText))):(k.subscriberCountText&&(T=g.YL(k.subscriberCountText)),k.subscriberCountWithSubscribeText&&(y=g.YL(k.subscriberCountWithSubscribeText)));const Q=g.J(k.signInEndpoint?.commandMetadata,g.f4)?.url||"";k={subscribeText:g.YL(k.unsubscribedButtonText),subscribeCount:T||
"",unsubscribeText:g.YL(k.subscribedButtonText),unsubscribeCount:y||"",enabled:k.enabled||!1,classic:!1,subscribed:k.subscribed||!1,feature:"iv",signInUrl:Q};a.standalone_subscribe_button_data=k}K=new F1h(N,"branding","branding",K,a);a=d3H(Z);Z.player.B("web_player_overlay_positioned_layout")?(a.setAttribute("data-overlay-order","11"),Z.player.B0(a,4,!0)):Z.U.element.appendChild(a);K=new tvc(a,C2(Z),K);K.zt();g.u(K,K);Z.G[N]=K}};
g.cH.prototype.r3=g.ay(36,function(Z,k){const N=g.R1(this.GZ());N&&N.r3(Z,k)});
var ug={},lg=null;g.$b(BN,g.kN);g.t=BN.prototype;g.t.getDuration=function(){return this.duration};
g.t.play=function(Z){if(Z||this.V==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;fT(this);this.startTime=Z=g.vy();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.D3();this.Xq("play");this.isPaused()&&this.Xq("resume");this.V=1;const k=g.By(this);k in ug||(ug[k]=this);hMF();uMB(this,Z);return!0};
g.t.stop=function(Z){fT(this);this.V=0;Z&&(this.progress=1);lJa(this,this.progress);this.onStop();this.zU()};
g.t.pause=function(){this.isPlaying()&&(fT(this),this.V=-1,this.Xq("pause"))};
g.t.YW=function(){this.V==0||this.stop(!1);this.Xq("destroy");BN.n8.YW.call(this)};
g.t.destroy=function(){this.dispose()};
g.t.IA=function(){this.Xq("animate")};
g.t.Xq=function(Z){this.dispatchEvent(new fJi(Z,this))};
g.$b(fJi,g.kE);g.$b(Dg,BN);Dg.prototype.D=function(){};
Dg.prototype.IA=function(){this.D();Dg.n8.IA.call(this)};
Dg.prototype.zU=function(){this.D();Dg.n8.zU.call(this)};
Dg.prototype.D3=function(){this.D();Dg.n8.D3.call(this)};
g.$b(O4,Dg);O4.prototype.D=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var g9c=class extends g.jR{constructor(Z){super();this.U=Z||window;this.V=[]}listen(Z,k,N,a){N=(0,g.Dj)(N,a||this.U);Z=g.R6(Z,k,N);this.V.push(Z);return Z}TG(Z,k,N,a){N=(0,g.Dj)(N,a||this.U);Z=F_i(Z,k,N);this.V.push(Z);return Z}Ce(Z){g.nE(Z);g.qF(this.V,Z)}removeAll(){g.nE(this.V);this.V.length=0}YW(){this.removeAll();super.YW()}};var zNe=class extends g.oS{constructor(Z){super(Z);this.Y=this.endscreen=null;this.U={};this.G={};this.L=this.D=null;this.C=[];this.V=null;this.Vz=!0;this.j=0;Z=Z.X();this.N=g.s$(Z)||g.HQ(Z);this.events=new g.tt(this);g.u(this,this.events);this.events.K(this.player,g.te("creatorendscreen"),this.onCueRangeEnter);this.events.K(this.player,g.he("creatorendscreen"),this.onCueRangeExit);this.events.K(this.player,"resize",this.qx);this.events.K(window,"focus",this.O);this.load();const k=g.TU("STYLE");(g.Uf("HEAD")[0]||
document.body).appendChild(k);this.addOnDisposeCallback(()=>{g.rM(k)});
k.sheet&&(k.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),k.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!wD(this)){var Z=g.Wki(this.player.getVideoData());Z?(Z=gD(Z,v1r(this)),$D(this,Z,!1)):$iT(this)}}unload(){$D(this,null);this.Y&&(this.Y.abort(),this.Y=null);super.unload()}kd(Z,k){return wD(this)?Z==="loadCustomEndscreenRenderer"?(Z=gD(k,"new"),$D(this,Z),!0):null:null}getOptions(){return wD(this)?["loadCustomEndscreenRenderer"]:[]}qx(){if(this.endscreen&&this.endscreen.elements){var Z=this.player.getVideoContentRect();if(Z&&Z.width!==0&&Z.height!==0){var k=this.player.getPlayerSize();
if(k&&k.width!==0&&k.height!==0){var N=Z.width/Z.height;var a=0;var T=-1;for(var K=0;K<SmJ.length;K++){var y=Math.abs(k.width-SmJ[K]);if(T===-1||a>=y)T=K,a=y}a=eNK[T];this.D&&g.ij(this.D.element,"outline-width",Math.max(k.width,k.height)+"px");for(k=0;k<this.endscreen.elements.length;++k){K=this.endscreen.elements[k].id;T=this.U[K];y=this.G[K];if(!T||!y)continue;const q=y.width*N/y.aspectRatio;var Q=Math.round(y.width*Z.width);K=Math.round(q*Z.height);const r=Z.left+Math.round(y.left*Z.width),C=Z.top+
Math.round(y.top*Z.height);g.n1(T.element,Q,K);g.o4(T.element,r,C);g.Y3(T.element,o9H);Q>256||K>256?g.jX(T.element,"ytp-ce-large-round"):Q>96||K>96?g.jX(T.element,"ytp-ce-medium-round"):g.jX(T.element,"ytp-ce-small-round");g.Y3(T.element,Jxe);Q=y.left+y.width/2;y=y.top+q/2;g.jX(T.element,Q<=.5&&y<=.5?"ytp-ce-top-left-quad":Q>.5&&y<=.5?"ytp-ce-top-right-quad":Q<=.5&&y>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Y3(T.element,eNK);g.jX(T.element,a);(T=g.Rk(document,"div","ytp-ce-expanding-overlay-body",
T.element)[0])&&g.ij(T,"height",`${K}px`)}}}}}onCueRangeEnter(Z){if(this.endscreen)if(Z.getId()==="ytp-ce-in-endscreen")Jr(this,this.endscreen.impressionUrls),(Z=g.C9())&&this.endscreen.visualElement&&g.zO(Z,this.endscreen.visualElement),this.V&&(g.jX(this.V,"ytp-ce-element-show"),this.V.removeAttribute("aria-hidden"),this.player.pm()?g.jX(this.V,"ytp-ce-hide-button-lower"):g.Wp(this.V,"ytp-ce-hide-button-lower"));else{Z=Z.getId().substring(15);var k=this.U[Z],N=this.G[Z];g.jX(k.element,"ytp-ce-element-show");
k.element.removeAttribute("aria-hidden");k=this.player.getRootNode();g.jX(k,"ytp-ce-shown");Jr(this,N.impressionUrls);(k=g.C9())&&g.zO(k,N.visualElement);this.player.X().C&&g.A7(this.player,"endscreenelementshown",Z)}}onCueRangeExit(Z){if(Z.getId()==="ytp-ce-in-endscreen")this.V&&(g.Wp(this.V,"ytp-ce-element-show"),this.V.setAttribute("aria-hidden","true"));else{Z=Z.getId().substring(15);var k=this.U[Z];g.Wp(k.element,"ytp-ce-element-show");k.element.setAttribute("aria-hidden","true");k=this.player.getRootNode();
g.Wp(k,"ytp-ce-shown");this.player.X().C&&g.A7(this.player,"endscreenelementhidden",Z)}}O(Z){Z.target===window&&(new g.Uc(()=>{for(const k of Object.values(this.U))g.Y3(k.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}In(Z){for(const k of Object.values(this.U))Z?k.element.setAttribute("hidden",""):k.element.removeAttribute("hidden")}vk(Z){this.V&&this.player.getRootNode().removeChild(this.V);
Z&&(g.jX(Z,"ytp-ce-hide-button-container"),this.V=Z,g.$n(this.player,this.V,4))}},SmJ=[346,426,470,506,570,640,853,1280,1920],eNK="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Jxe=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],o9H=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var zMa=class{constructor(Z,k,N,a){this.value=Z;this.target=k;this.showLinkIcon=N;this.U=a}V(){return this.value?this.value:null}},JIe={ZY:"current",CO:"new"};var pKH=class{constructor(Z,k,N){this.type=Z;this.trigger=k;this.url=N}},Uih={CLOSE:"close",sZ:"openUrl",SUBSCRIBE:"subscribe"},b1e={U5:"click",CLOSE:"close",wT:"hidden",Aqa:"rollOut",NAW:"rollOver",pAp:"shown"};var F1h=class{constructor(Z,k,N,a,T){this.id=Z;this.type=k;this.style=N;this.data=T;this.action=a||[]}mH(){const Z=MAJ(this,k=>k.type==="openUrl"&&k.url!=null);
return Z?Z.url:null}},VvK={xM:"anchored",cH:"branding",CHANNEL:"channel",jc:"cta",N1:"highlightText",aZ:"label",PLAYLIST:"playlist",POPUP:"popup",lFz:"speech",SUBSCRIBE:"subscribe",ZFp:"title",VIDEO:"video",xWX:"website"},L1e={cH:"branding",nG:"card",w1:"drawer",At:"highlight",zw:"marker",oWW:"promotion",TEXT:"text",svW:"widget"};var U3K=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
blB=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var pFc=class{constructor(Z,k){this.context=Z;this.V=k}};var lte=class{constructor(Z,k){this.merchant=Z;this.price=k}};var RNe=class extends g.jR{constructor(Z,k){super();this.element=Z;this.context=k;this.O6=!1;this.Qz=new Map;this.s6=new Map;this.context.S.addEventListener(g.te("annotations_module"),N=>{(N=this.Qz.get(N))&&N.apply(this)});
this.context.S.addEventListener(g.he("annotations_module"),N=>{(N=this.s6.get(N))&&N.apply(this)})}addCueRange(Z,k,N,a,T){Z=new g.pe(Z,k,{id:N,
namespace:"annotations_module"});a&&this.Qz.set(Z,a);T&&this.s6.set(Z,T);this.context.S.f8([Z],1)}zt(){this.context.U.subscribe("resize",this.FS,this)}lq(){return this.element}Kp(Z,k,N,a,T,K){if(this.O6)return!1;K&&(K.stopPropagation(),K.preventDefault());this.navigate(Z,N,a,T);return!1}show(){}hide(){}destroy(){g.rM(this.lq())}FS(){}navigate(Z,k,N,a){const T=Z.V();if(T){var K=j4B(T,Z.target),y=()=>{Z.U&&this.context.S.pauseVideo();const Q=this.context.videoData.o4||!1,q=g.mm(T||"");Q&&q&&(q.v||q.list)?
this.context.S.CP(q.v,k,q.list,!1):g.RJ(T||"",K==="current"?"_top":void 0,k)};
K==="new"&&(y(),y=null);rG(this.context.logger,N,y,a);IJi(T)||(N=g.C9(),a=k.itct,N&&a&&g.p9(N,g.yz(a)))}}YW(){this.Qz.clear();this.s6.clear();super.YW()}createElement(Z){Z=new g.E(Z);g.u(this,Z);return Z.element}};var x3e=class extends RNe{constructor(Z,k,N){super(k,N);this.S=Z;this.eventId=null;this.xl=this.Rq=this.r5=this.D=this.isInitialized=!1;this.cards=[];this.qX=this.L=this.Sm=this.G=this.MX=this.V=null;this.Vz=[];this.O=this.C=this.NR=this.vD=null;this.j=0;this.dA=new g.Uc(()=>{},N.kW.fN?4E3:3E3);
g.u(this,this.dA);this.Tt=new g.Uc(()=>{});
g.u(this,this.Tt);this.xW=new pFc(N,(a,T,K,y,Q,q)=>{j8(this,a,T,K,y,Q,q)});
this.N=new g.E({J:"div",Z:"iv-drawer",W:{id:"iv-drawer"},A:[{J:"div",Z:"iv-drawer-header",W:{"aria-role":"heading"},A:[{J:"span",Z:"iv-drawer-header-text"},{J:"button",BD:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{J:"div",Z:"iv-drawer-content"}]});g.u(this,this.N);this.Y=this.N.element;this.hq=new g.ML(this.N,330);g.u(this,this.hq);this.pF=g.Mc("iv-drawer-header-text",this.Y);this.U=g.Mc("iv-drawer-content",this.Y);this.addCueRange(0,N.videoData.lengthSeconds*
1E3,"",()=>{this.r5&&ZP(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.r5=this.D)&&N5(this)});
this.tq=new g.tt(this);g.u(this,this.tq);this.S.addEventListener("videodatachange",this.FX.bind(this))}FX(){this.O&&k0(this,this.O)}isAvailable(){var Z;if(Z=!!this.cards.length)(Z=this.S.getRootNode())?(Z=g.I4(Z),Z=173<Z.width&&173<Z.height):Z=!1;return Z}FS(){const Z=this.isAvailable();g.jA(this.lq(),Z);g.D(this.context.S.getRootNode(),g.Cs.IV_DRAWER_ENABLED,Z);tr(this.S)}destroy(){this.S.r3(!1);try{this.S.getRootNode().removeChild(this.Y)}catch(Z){}g.M6(this.Vz);this.tq.U();this.MX&&this.MX.dispose();
this.G&&this.G.dispose();super.destroy()}YI(){this.context.V.listen(g.Mc("iv-drawer-close-button",this.Y),"click",this.iq,this);this.context.V.listen(this.U,"touchend",()=>{this.dA.start()});
this.context.V.listen(this.U,"scroll",this.hp,this);this.context.U.subscribe("onHideControls",()=>{this.Rq=!0});
this.context.U.subscribe("onShowControls",()=>{this.Rq=!1});
this.context.U.subscribe("onVideoAreaChange",()=>{this.Rq=g.I3(this.S.getRootNode(),"ytp-autohide")});
this.Vz.push(g.Rj("iv-button-shown",this.Ap,this));this.Vz.push(g.Rj("iv-button-hidden",this.bq,this));kWD(this)}findLastIndex(Z){if(this.cards.length===0)return 0;const k=g.NF(this.cards,N=>Z.ib.startMs>N.ib.startMs||Z.ib.startMs===N.ib.startMs&&Z.ib.timestamp>=N.ib.timestamp?!0:!1);
return k===-1?0:k+1}iq(){if(this.D){rG(this.context.logger,K2(this).DI.close);var Z=g.C9();Z&&this.C&&g.p9(Z,this.C);N5(this)}}hp(){g.D(this.Y,"iv-drawer-scrolled",this.U.scrollTop>0)}Ap(){const Z=g.C9();var k=K2(this);k=k?k.NR:this.NR;Z&&k&&g.U5(Z,[k])}bq(){const Z=g.C9();var k=K2(this);k=k?k.NR:this.NR;Z&&k&&g.bA(Z,[k])}jY(){const Z=K2(this);rG(this.context.logger,Z.DI.Zu);const k=g.C9();if(k&&Z)if(this.S.B("web_infocards_teaser_show_logging_fix")){const N=[];Z.nX&&N.push(Z.nX);Z.NR&&N.push(Z.NR);
N.length>0&&g.U5(k,N)}else g.U5(k,[Z.nX,Z.NR])}ov(){const Z=g.C9(),k=K2(this);Z&&k&&g.bA(Z,[k.nX])}HA(Z){const k=K2(this),N=g.C9();this.V?Z?(Z=this.context.logger,rG(Z,k.DI.eS),Z.S.sendVideoStatsEngageEvent(4,void 0),N&&k.nX&&g.p9(N,k.nX)):(Z=this.context.logger,rG(Z,k.DI.eS),Z.S.sendVideoStatsEngageEvent(4,void 0),N&&k.NR&&g.p9(N,k.NR)):(Z=this.context.logger,rG(Z,k.DI.eS),Z.S.sendVideoStatsEngageEvent(4,void 0),N&&this.NR&&g.p9(N,this.NR))}};var Mvr=class extends RNe{constructor(Z,k,N){super(Z,k);this.annotation=N;this.isActive=!1}zt(){super.zt();rxa(this)}show(){super.show();const Z=g.C9();var k=this.annotation.data;Z&&k&&(k=k.session_data)&&g.U5(Z,[g.yz(k.itct)])}hide(){super.hide();const Z=g.C9();var k=this.annotation.data;Z&&k&&(k=k.session_data)&&g.bA(Z,[g.yz(k.itct)])}};var tvc=class extends Mvr{constructor(Z,k,N){super(Z,k,N);this.V=null;this.D=!1;this.U=null}show(){if(!this.isActive){super.show();if(!this.D){g.jX(this.lq(),"iv-branding");const Z=this.annotation.data;this.V=this.createElement({J:"img",BD:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:Z.image_url,width:Z.image_width,height:Z.image_height}});g.jA(this.V,!1);const k=this.createElement({J:"button",BD:["branding-img-container","ytp-button"]});k.appendChild(this.V);this.lq().appendChild(k);
const N=this.annotation.mH();N&&j8(this,k,N,this.annotation.id,Z.session_data);this.D=!0}g.jA(this.lq(),!0);this.isActive=!0;if(this.V){try{CKi(this,this.V)}catch{}g.jX(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",`${this.V.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.jA(this.lq(),!1),this.isActive=!1,g.Wp(this.context.S.getRootNode(),"ytp-branding-shown"))}destroy(){this.U&&(this.U.dispose(),this.U=
null);g.Wp(this.context.S.getRootNode(),"ytp-branding-shown");super.destroy()}};var wFB=class{constructor(Z,k,N,a,T,K,y){this.V=Z;this.D=k;this.kW=N;this.videoData=a;this.logger=T;this.S=K;this.U=y}};var hNK=class extends Mvr{constructor(Z,k,N){super(Z,k,N);this.C=this.isCollapsed=this.N=!1;this.G=5E3;this.U=this.D=this.V=this.Y=null;this.j=this.createElement({J:"div",BD:["iv-promo-contents"]});this.L=new g.Uc(()=>{this.V.setAttribute("aria-hidden","true");g.jA(this.D,!1);g.jA(this.U,!0)},700,this);
g.u(this,this.L)}show(){this.isActive||(super.show(),this.N||(Axi(this),this.N=!0),g.jA(this.lq(),!0),g.W2(function(){g.Wp(this.lq(),"iv-promo-inactive")},100,this),this.lq().removeAttribute("aria-hidden"),this.isActive=!0,q5(this),m3h(this),sIJ(this,this.G))}hide(){this.isActive&&(g.jX(this.lq(),"iv-promo-inactive"),this.isActive=!1,this.lq().setAttribute("aria-hidden","true"))}Kp(Z,k,N,a,T,K){return this.isCollapsed?!1:super.Kp(Z,k,N,a,T,K)}dA(Z){this.C=!0;
Qt(this,500,Z)}xW(){this.C=!1;PKa(this)}Vz(Z){Z.stopPropagation();this.hide()}O(Z){Z.stopPropagation();q5(this);this.isCollapsed=!0;g.jX(this.lq(),"iv-promo-collapsed-no-delay");this.L.start()}destroy(){this.L.dispose();super.destroy()}};var n9h=class{constructor(Z){this.S=Z}};g.o1("annotations_module",class extends g.oS{constructor(Z){super(Z);this.Vz=this.O=!1;this.loadNumber=0;this.G={};this.logger=new n9h(this.player);this.L=new g.tt(this);this.j=this.Y=null;this.events=new g.tt(this);this.Mj=this.C=this.V=null;this.zt=[];g.u(this,this.L);this.L.K(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.L.K(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.L.K(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.L.K(this.player,"resize",N=>{this.publish("resize",N)});
this.L.K(this.player,"presentingplayerstatechange",N=>{this.publish("presentingplayerstatechange",N)});
this.subscribe("presentingplayerstatechange",this.dA,this);this.subscribe("resize",this.N,this);this.player.X().vD.subscribe("vast_info_card_add",this.xW,this);g.u(this,this.events);this.FS=this.createElement({J:"div",Z:"video-custom-annotations"});this.U=new g.E({J:"div",BD:["ytp-player-content","ytp-iv-player-content"]});g.u(this,this.U);g.$n(this.player,this.U.element,4);this.U.hide();this.D=new g.E({J:"div",BD:["ytp-iv-video-content"]});g.u(this,this.D);Z=this.createElement({J:"div",Z:"video-annotations"});
Z.appendChild(this.FS);this.D.element.appendChild(Z);this.a8()?this.load():this.player.B("web_fix_annotations")&&(this.Y=()=>{this.loaded||this.jm()||!this.a8()||(Hln(this),this.load())},this.player.addEventListener("videodatachange",this.Y));
const k=this.createElement({J:"style"});(g.Uf("HEAD")[0]||document.body).appendChild(k);this.addOnDisposeCallback(()=>{g.rM(k)});
if(Z=k.sheet){for(const N of U3K)Z.insertRule(N,0);for(const N of blB)Z.insertRule(N,0)}}kd(Z,k){if(!cxJ(this.player.X().playerStyle))return null;switch(Z){case "loadCustomAnnotationsXml":return(Z=g.Fc(k))&&mI(this,Z),!0;case "removeCustomAnnotationById":return k&&this.V&&(WN(this.V,k),tr(this.player)),!0}return null}getOptions(){return cxJ(this.player.X().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}a8(){const Z=this.player.getVideoData(),k=Z.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return Z.o4||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.B("web_fix_annotations")?ftB(this)?k?.isWatermarkEnforced===!0?!0:k?.isAnnotationsEnabled??!1:!1:ftB(this)}N(){if(this.D){var Z=this.player.fF().getVideoContentRect(!0);g.n1(this.D.element,Z.width,Z.height);g.o4(this.D.element,Z.left,Z.top)}if(this.V){var k=this.player.Sd();Z=this.V;k=k.width;g.D(Z.Y,"iv-drawer-small",k<=426);g.D(Z.Y,"iv-drawer-big",k>=1280)}}dA(Z){BPr(this,Z.state);Z.state.V(2)&&(this.pm()&&this.hh()&&this.player.getPresentingPlayerType()!==
2&&this.Kl(!1),this.r3(!1))}load(){super.load();BPr(this,this.player.getPlayerStateObject());this.loadNumber++;const Z=this.player.getVideoData();ilc(this,Z);g.$n(this.player,this.D.element,4);this.N();var k=g.kn(Z);const N=Z.l9();if(this.player.B("web_fix_annotations")){if(k&&(k.featuredChannel&&GWe(this,k.featuredChannel,k.annotationId||"branding",Z.videoId||null,Z.eventId||null),k=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,k?.isWatermarkEnforced&&!k?.isAnnotationsEnabled))return;
N&&Ap(this,N)}else N&&Ap(this,N),k&&k.featuredChannel&&GWe(this,k.featuredChannel,k.annotationId||"branding",Z.videoId||null,Z.eventId||null);this.Mj=g.Mc("ytp-cards-button",this.player.getRootNode());Z.j9()&&v9a(this,Z)}onVideoDataChange(){}unload(){this.player.jl("annotations_module");for(const Z of Object.keys(this.G))this.G[Z].destroy();this.C=null;this.V&&(this.V.destroy(),this.V=null,tr(this.player));this.O=!1;this.j&&(this.j.abort(),this.j=null);this.Vz=!1;this.G={};this.U.hide();super.unload();
this.D.detach();Hln(this)}xW(Z){Z===this.player.getVideoData().videoId&&(this.loaded?$3T(this):this.load())}pm(){return this.V?.isAvailable()||this.Vz}hh(){return!!this.V&&this.V.D}Kl(Z,k=!1,N){this.pm();this.V&&(Z?N?ZP(this.V,N,k):ZP(this.V,"YOUTUBE_DRAWER_AUTO_OPEN",k):N5(this.V))}r3(Z,k){this.player.publish(Z?"cardsteasershow":"cardsteaserhide",k)}YW(){this.player.X().vD.unsubscribe("vast_info_card_add",this.xW,this);g.Wp(this.player.getRootNode(),g.Cs.IV_DRAWER_OPEN);var Z=this.zt,k=g.g3;for(let N=
0,a=Z.length;N<a;N++)k.Ux(Z[N]);this.zt.length=0;super.YW()}createElement(Z){Z=new g.E(Z);g.u(this,Z);return Z.element}});g.o1("creatorendscreen",zNe);})(_yt_player);
