(function(g){var window=this;'use strict';var jIH=async function(Z,k,N){Z.U=g.SD(k,N)},PA=function(Z){Z.isActive()||Z.start()},E9e=function(Z,k){const N=new g.RO;
N.languageCode=Z.languageCode;N.languageName=Z.languageName;N.name=Z.name;N.displayName=Z.displayName;N.kind=Z.kind;N.isDefault=!1;N.V=Z.V;N.isTranslateable=Z.isTranslateable;N.vssId=Z.vssId;N.url=Z.url;N.translationLanguage=k;Z.xtags&&(N.xtags=Z.xtags);Z.captionId&&(N.captionId=Z.captionId);return N},cA=function(Z,k){return k?Z.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},W1c=function(Z){return g.fQ(Z)||Z.B("web_enable_caption_language_preference_stickiness")},Ymn=async function(Z,k){Z=
Z+"|"+k;
k=await g.TN();if(!k)throw g.wO("gct");return(await g.KL(k)).get("captions",Z)},ZCh=function(Z,k,N){Ymn(Z,k).then(a=>{a&&N(a.trackData,new g.RO(a.metadata))})},HA=function(Z){if(!kXB.test(Z))throw Error("'"+Z+"' is not a valid hex color");
Z.length==4&&(Z=Z.replace(NUi,"#$1$1$2$2$3$3"));Z=Z.toLowerCase();Z=parseInt(Z.slice(1),16);return[Z>>16,Z>>8&255,Z&255]},aqa=function(){var Z={};
let k="suggest_correction"in g.gy?g.gy.suggest_correction:"Edit caption";k=k||"";for(let N in Z){const a=()=>String(Z[N]);
k=k.replace(new RegExp("\\$\\{"+N+"\\}","gi"),a);k=k.replace(new RegExp("\\$"+N,"gi"),a)}return k},dG=function(){return g.kh("yt-player-caption-display-settings")},TUi=function(Z,k){let N=g.F_(Z.segments,k);
N>=0||N<0&&(-N-1)%2===1||(N=-N-1,N>0&&k-Z.segments[N-1]===1&&N<Z.segments.length&&Z.segments[N]-k===1?(g.QH(Z.segments,N),g.QH(Z.segments,N-1)):N>0&&k-Z.segments[N-1]===1?Z.segments[N-1]=k:N<Z.segments.length&&Z.segments[N]-k===1?Z.segments[N]=k:(g.dH(Z.segments,N,0,k),g.dH(Z.segments,N+1,0,k)))},Kbh=function(Z){return Z.V&&Z.V.L?Z.V.L+Z.player.mx()<Z.player.getCurrentTime():!1},yJr=function(Z,k){if(Z.policy.lf&&Z.player.nP()){var N=g.GH(k,Z.policy,{});
N.set("pot",Z.player.nP());N=N.mH()}else N=g.GH(k,Z.policy,{}).mH();const a={format:"RAW",withCredentials:!0};if(Z.policy.vD){a.method="POST";const y=k.Y;y&&Object.keys(y).length>0?a.postBody=g.SV(y,g.t_):a.postBody=(0,g.di)([120,0])}Z.L&&(a.responseType="arraybuffer");let T=++Z.zt;const K=(0,g.z)();Z.U=g.Ri(N,a,3,100,-1,y=>{y.errorCode==="net.timeout"&&Z.player.U6("capnt",{rn:T++})}).then(y=>{if(Z.policy.LU&&T%100===1){var Q=(0,g.z)();
Z.player.U6("caprsp",{rn:T,ms:Q-K,kb:(y.xhr.responseText.length/1024).toFixed()})}a:{y=y.xhr;Z.jm();if(Z.D){var q=!(Z.L?y.response:y.responseText)||y.status>=400;if(Q=g.RIU(y)){y=g.GH(Z.D,Z.policy,{});Z.D.DT(y,Q);yJr(Z,Z.D);break a}q?Z.player.U6("capfail",{status:y.status}):(g.LN("fcb_r",(0,g.z)(),Z.player.getVideoData()?.Vz||""),Q=Z.D.Vi[0],q=Q.Cp,Z.C!=null&&Z.G!==q&&(Z.L?Z.C(y.response,(Q.startTime+Z.player.mx())*1E3):Z.C(y.responseText,(Q.startTime+Z.player.mx())*1E3),Z.G=q))}Z.D=null;Z.U=null}}).eK(y=>
{Z.D=null;
Z.U=null;Z.player.U6("capfail",{rn:T,status:y.xhr?.status})});
Z.D=k;TUi(Z.Y,Z.D.Vi[0].Cp)},QqJ=function(Z,k){return k!=null&&k in Z.U.V?Z.U.V[k]:null},qeF=function(Z,k,N){const a=[];
for(const T in Z.U.V){if(!Z.U.V.hasOwnProperty(T))continue;const K=Z.U.V[T];if(g.U8(K,N||null)){const y=K.info.captionTrack;y&&y.languageCode===k&&a.push(K)}}return a.length?a[0]:null},CWc=function(Z,k){const N=[];
for(const T in Z.U.V){if(!Z.U.V.hasOwnProperty(T))continue;var a=Z.U.V[T];if(g.U8(a,k||null)){let K=a.info.id,y=K,Q=`.${K}`,q="",r="";if(a=a.info.captionTrack)K=a.languageCode,y=a.displayName,Q=a.vssId,q=a.kind,r=a.id;else{{a=K;let C=g.bKB.get(a);C==null&&(C=rJe[a]||rJe[a.replace(/-/g,"_")],g.bKB.set(a,C));a=C}y=a||y}N.push(new g.RO({id:T,languageCode:K,languageName:y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:q,captionId:r}))}}return N},mmi=function(Z,k,N,a){let T=k/360*16;
k>=Z&&(Z=640,a>N*1.3&&(Z=480),T=N/Z*16);return T},sqi=function(Z){let k=1+.25*(Z.fontSizeIncrement||0);
if(Z.offset===0||Z.offset===2)k*=.8;return k},AJc=function(Z,k){let N="vertical-rl";
Z.V.XG===1&&(N="vertical-lr");g.yd&&(N=N==="vertical-lr"?"tb-lr":"tb-rl");g.ij(k,"-o-writing-mode",N);g.ij(k,"-webkit-writing-mode",N);g.ij(k,"writing-mode",N);g.ij(k,"text-orientation","upright");g.jX(k,"ytp-vertical-caption");Z.U.params.b9===3&&(g.ij(k,"text-orientation",""),g.ij(k,"transform","rotate(180deg)"))},PWD=function(Z,k){const N={};
var a=k.background?k.background:Z.V.p8.background;if(k.backgroundOpacity!=null||k.background){var T=k.backgroundOpacity!=null?k.backgroundOpacity:Z.V.p8.backgroundOpacity;a=HA(a);N.background="rgba("+a[0]+","+a[1]+","+a[2]+","+T+")";Z.Ap&&(N["box-decoration-break"]="clone",N["border-radius"]=`${Z.Kp/8}px`)}if(k.fontSizeIncrement!=null||k.offset!=null)N["font-size"]=`${Z.Qz*sqi(k)}px`;a=1;T=k.color||Z.V.p8.color;if(k.color||k.textOpacity!=null)T=HA(T),a=k.textOpacity==null?Z.V.p8.textOpacity:k.textOpacity,
T="rgba("+T[0]+","+T[1]+","+T[2]+","+a+")",N.color=T,N.fill=T;var K=k.charEdgeStyle;K===0&&(K=void 0);if(K){T=`rgba(34, 34, 34, ${a})`;let q=`rgba(204, 204, 204, ${a})`;k.Mv&&(q=T=k.Mv);const r=Z.Qz/16/2,C=Math.max(r,1);var y=Math.max(2*r,1),Q=Math.max(3*r,1);const m=Math.max(5*r,1);a=[];switch(K){case 4:for(;Q<=m;Q+=r)a.push(`${y}px ${y}px ${Q}px ${T}`);break;case 1:y=window.devicePixelRatio>=2?.5:1;for(K=C;K<=Q;K+=y)a.push(`${K}px ${K}px ${T}`);break;case 2:a.push(`${C}px ${C}px ${q}`);a.push(`-${C}px -${C}px ${T}`);
break;case 3:for(Q=0;Q<5;Q++)a.push(`0 0 ${y}px ${T}`)}N["text-shadow"]=a.join(", ")}T="";switch(k.fontFamily){case 1:T='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:T='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:T='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:T='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:T='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:T=g.ce()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:T='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}T&&(N["font-family"]=T);T=k.offset;T==null&&(T=Z.V.p8.offset);switch(T){case 0:N["vertical-align"]="sub";break;case 2:N["vertical-align"]="super"}k.fontFamily===7&&(N["font-variant"]="small-caps");k.bold&&(N["font-weight"]="bold");k.italic&&(N["font-style"]="italic");k.underline&&
(N["text-decoration"]="underline");k.RY&&(N.visibility="hidden");k.Jj===1&&Z.Y&&(N["text-combine-upright"]="all",N["text-orientation"]="mixed",T=g.iS||g.v9,Z.U.params.b9===3?N.transform=T?"rotate(90deg)":"rotate(180deg)":T&&(N.transform="rotate(-90deg)"));if(k.textEmphasis===1||k.textEmphasis===2||k.textEmphasis===3||k.textEmphasis===4||k.textEmphasis===5)if(g.iS)N["font-weight"]="bold";else switch(N["text-emphasis-style"]="filled circle",N["text-emphasis-color"]="currentcolor",N["webkit-text-emphasis"]=
"filled circle",k.textEmphasis){case 4:case 3:N["text-emphasis-position"]="under left";N["webkit-text-emphasis-position"]="under left";break;case 5:case 2:N["text-emphasis-position"]="over right",N["webkit-text-emphasis-position"]="over right"}return N},Xg=function(Z){Z=Z.split("px");
return Z.length>0?(Z=Number(Z[0]))?Z:0:0},dm_=function(Z,k,N){Z.vD=Z.vD||!!N;
const a={};Object.assign(a,Z.V.p8);Object.assign(a,N||k.V);Object.assign(a,Z.tW.p8);(N=!Z.j)&&cJB(Z);let T=Z.Sm&&Z.Rq&&g.pK(a,Z.Rq)?Z.Sm:HCa(Z,a);const K=typeof k.text==="string",y=K?k.text.split("\n"):[k.text];for(let q=0;q<y.length;q++){var Q=q>0||!k.append;const r=y[q];Q&&!N?(cJB(Z),T=HCa(Z,a)):Q&&N&&(N=!1);r&&(T.appendChild(K?g.K1(r):r),K||r.tagName!=="RUBY"||r.childElementCount!==4||g.iS||!g.x1(r.children[2],"text-emphasis")||(Q=Z.Y?"padding-right":"padding-top",g.x1(r.children[2],"text-emphasis-position")&&
(Q=Z.Y?"padding-left":"padding-bottom"),g.YK?g.ij(T,Q,"1em"):g.ij(T,Q,"0.5em")))}Z.Rq=a;Z.Sm=T;Z.G.push(k)},cJB=function(Z){Z.j=g.TU("SPAN");
g.ij(Z.j,{display:"block"});g.jX(Z.j,"caption-visual-line");Z.D.appendChild(Z.j)},HCa=function(Z,k){const N=g.TU("SPAN");
g.ij(N,{display:"inline-block","white-space":"pre-wrap"});g.ij(N,PWD(Z,k));N.classList.add("ytp-caption-segment");Z.j.appendChild(N);N.previousElementSibling&&(g.ij(N.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ij(N,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return N},Lbh=function(Z,k,N){if(Z===255&&k===255||!Z&&!k)return{PX:Z,
pI:k,result:0};Z=XRr[Z];k=XRr[k];if(Z&128){var a;if(a=!(k&128))a=k,a=N.cG()&&N.pI===a;if(a)return{PX:Z,pI:k,result:1}}else if(k&128&&1<=Z&&Z<=31)return{PX:Z,pI:k,result:2};return{PX:Z,pI:k,result:3}},Fbe=function(Z,k,N,a){k===255&&N===255||!k&&!N?(++Z.D===45&&Z.reset(),Z.Y.U.clear(),Z.L.U.clear()):(Z.D=0,VaT(Z.Y,k,N,a))},tan=function(Z,k){Z.V.sort((N,a)=>{const T=N.time-a.time;
return T===0?N.order-a.order:T});
for(const N of Z.V)Z.time=N.time,N.type===0?Fbe(Z,N.Zi,N.Cb,k):N.type===1&&Z.U&496&&VaT(Z.L,N.Zi,N.Cb,k);Z.V.length=0},BUH=function(Z,k){switch(Z){case 0:return hzH[(k&127)-32];
case 1:return uln[k&15];case 2:return lqK[k&31];case 3:return fqh[k&31]}return 0},L2=function(Z,k){if(Z.style.type===3){var N=0,a=0,T=Z.L.time+0,K="",y="",Q=T;
for(var q=1;q<=15;++q){var r=!1;for(var C=a?a:1;C<=32;++C){var m=Z.D[q][C];if(m.V!==0){N===0&&(N=q,a=C);r=String.fromCharCode(m.V);var A=m.timestamp;A<T&&(T=A);m.timestamp=Q;y&&(K+=y,y="");K+=r;r=!0}if((m.V===0||C===32)&&r){y="\n";break}else if(a&&!r)break}if(N&&!r)break}K&&k.Y(N,a,T,Q,K)}else for(a=N=0,K=T=Z.L.time+0,y=1;y<=15;++y)for(Q="",q=1;q<=32;++q)if(C=Z.D[y][q],m=C.V,m!==0&&(N===0&&(N=y,a=q),r=String.fromCharCode(m),A=C.timestamp,A<=T&&(T=A),Q+=r,C.reset()),q===32||m===0)Q&&k.Y(N,a,T,K,Q),
T=K,Q="",a=N=0},Vt=function(Z){return Z.D[Z.row][Z.U]},Fg=function(Z,k,N){k>=2&&Z.U>1&&(--Z.U,Vt(Z).V=0);
const a=Vt(Z);a.timestamp=Z.L.time+0;a.V=BUH(k,N);Z.U<32&&Z.U++},Dmn=function(Z,k,N,a){for(let y=0;y<a;y++)for(let Q=0;Q<=32;Q++){var T=Z.D[k+y][Q],K=Z.D[N+y][Q];
T.V=K.V;T.timestamp=K.timestamp}},tp=function(Z,k,N){for(let a=0;a<N;a++)for(let T=0;T<=32;T++)Z.D[k+a][T].reset()},hp=function(Z){Z.row=Z.V>0?Z.V:1;
Z.U=1;tp(Z,0,15)},OCJ=function(Z){Z.style.set(1);
Z.V=Z.Y;Z.V.V=0;Z.V.style=Z.style;Z.D.mode=1<<Z.V.Y},uC=function(Z,k,N){const a=Z.U;
let T=!1;switch(Z.style.get()){case 4:case 1:case 2:Z.style.get()===4&&a.V>0||(L2(a,N),hp(Z.U),hp(Z.Y),a.row=15,a.V=k,T=!0)}Z.style.set(3);Z.V=a;Z.V.style=Z.style;Z.D.mode=1<<a.Y;T?a.U=1:a.V!==k&&(a.V>k?(L2(a,N),tp(a,a.row-a.V,k)):a.row<k&&(k=a.V),a.V=k)},v4T=function(Z){Z.style.set(4);
Z.V=Z.text;Z.V.style=Z.style;Z.D.mode=1<<Z.V.Y},VaT=function(Z,k,N,a){Z.U.update();
k=Lbh(k,N,Z.U);switch(k.result){case 0:return;case 1:case 2:return}var T=k.PX;k=k.pI;if(32<=T||!T)Z.V.mode&Z.V.U&&(N=T,N&128&&(N=127),k&128&&(k=127),Z=Z.Y.V,N&96&&Fg(Z,0,N),k&96&&Fg(Z,0,k),N!==0&&k!==0&&Z.style.type===3&&L2(Z,a));else if(T&16)a:if(!Z.U.matches(T,k)&&(N=Z.U,N.PX=T,N.pI=k,N.state=2,N=T&8?Z.G:Z.D,Z.Y=N,Z.V.mode=1<<(Z.L<<2)+(N.L<<1)+(N.style.type===4?1:0),(Z.V.mode|1<<(Z.L<<2)+(N.L<<1)+(N.style.type!==4?1:0))&Z.V.U))if(k&64){a=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(T&7)<<1|k>>5&1];
Z=k&16?((k&14)>>1)*4:0;k=N.V;switch(N.style.get()){case 4:a=k.row;break;case 3:if(a!==k.row){if(a<k.V&&(a=k.V,a===k.row))break;var K=1+k.row-k.V;const y=1+a-k.V;Dmn(k,y,K,k.V);N=K;T=k.V;y<K?(K=y+T-K,K>0&&(N+=K,T-=K)):(K=K+T-y,K>0&&(T-=K));tp(k,N,T)}}k.row=a;k.U=Z+1}else switch(T&7){case 1:switch(k&112){case 32:Fg(N.V,0,32);break a;case 48:k===57?(a=N.V,Vt(a).V=0,a.U<32&&a.U++):Fg(N.V,1,k&15)}break;case 2:k&32&&Fg(N.V,2,k&31);break;case 3:k&32&&Fg(N.V,3,k&31);break;case 4:case 5:if(32<=k&&k<=47)switch(k){case 32:OCJ(N);
break;case 33:a=N.V;a.U>1&&(--a.U,Vt(a).V=0);break;case 36:a=N.V;Z=Vt(a);for(k=0;k<=15;k++)for(N=0;N<=32;N++)if(a.D[k][N]===Z){for(;N<=32;N++)a.D[k][N].reset();break}break;case 37:uC(N,2,a);break;case 38:uC(N,3,a);break;case 39:uC(N,4,a);break;case 40:Fg(N.V,0,32);break;case 41:a=N;a.style.set(2);a.V=a.U;a.V.V=0;a.V.style=a.style;a.D.mode=1<<a.V.Y;break;case 42:a=N;Z=a.text;Z.V=15;Z.style.set(4);hp(Z);v4T(a);break;case 43:v4T(N);break;case 44:Z=N;k=Z.U;switch(Z.style.get()){case 1:case 2:case 3:L2(k,
a)}tp(k,0,15);break;case 45:b:{k=N;Z=k.V;switch(k.style.get()){default:case 2:case 1:break b;case 4:if(Z.row<15){++Z.row;Z.U=1;break b}break;case 3:}Z.V<2&&(Z.V=2,Z.row<Z.V&&(Z.row=Z.V));k=Z.row-Z.V+1;L2(Z,a);Dmn(Z,k,k+1,Z.V-1);tp(Z,Z.row,1)}break;case 46:tp(N.Y,0,15);break;case 47:Z=N,L2(Z.U,a),Z.Y.updateTime(Z.D.time+0),a=Z.Y,Z.Y=Z.U,Z.U=a,OCJ(Z)}break;case 7:switch(k){case 33:case 34:case 35:a=N.V,(a.U+=k&3)>32&&(a.U=32)}}},g4H=function(Z,k,N,a,T,K,y){var Q=K[0];
let q=y[Q.getAttribute("p")];if(q.UP===1){var r=K[1],C=K[2];K=K[3];Q.getAttribute("t");r.getAttribute("t");C.getAttribute("t");K.getAttribute("t");Q.getAttribute("p");r.getAttribute("p");K.getAttribute("p");y=y[C.getAttribute("p")];Q=iCH(Q.textContent,r.textContent,C.textContent,K.textContent,y);return new lC(Z,k,T,N,Q,a,q)}switch(q.UP){case 9:case 10:q.textEmphasis=1;break;case 11:q.textEmphasis=2;break;case 12:q.textEmphasis=3;break;case 13:q.textEmphasis=4;break;case 14:q.textEmphasis=5}return new lC(Z,
k,T,N,Q.textContent||"",a,q)},iCH=function(Z,k,N,a,T){var K=g.ce();
const y=K?g.TU("DIV"):g.TU("RUBY"),Q=g.TU("SPAN");Q.textContent=Z;y.appendChild(Q);Z=K?g.TU("DIV"):g.TU("RP");Z.textContent=k;y.appendChild(Z);k=K?g.TU("DIV"):g.TU("RT");k.textContent=N;y.appendChild(k);N=T.UP;if(N===10||N===11||N===12||N===13||N===14)if(g.ij(k,"text-emphasis-style","filled circle"),g.ij(k,"text-emphasis-color","currentcolor"),g.ij(k,"webkit-text-emphasis","filled circle"),T.UP===11||T.UP===13)g.ij(k,"webkit-text-emphasis-position","under left"),g.ij(k,"text-emphasis-position","under left");
N=!0;if(T.UP===4||T.UP===7||T.UP===12||T.UP===14)g.ij(y,"ruby-position","over"),g.ij(y,"-webkit-ruby-position","before");else if(T.UP===5||T.UP===6||T.UP===11||T.UP===13)g.ij(y,"ruby-position","under"),g.ij(y,"-webkit-ruby-position","after"),N=!1;T=K?g.TU("DIV"):g.TU("RP");T.textContent=a;y.appendChild(T);K&&(a=N,g.ij(y,{display:"inline-block",position:"relative"}),K=y.firstElementChild.nextElementSibling,g.ij(K,"display","none"),K=K.nextElementSibling,g.ij(K,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ij(y.lastElementChild,"display","none"),a?(g.ij(y,"padding-top","0.6em"),g.ij(K,"top","0")):(g.ij(y,"padding-bottom","0.6em"),g.ij(K,"bottom","0")));return y},wRJ=function(Z){const k="_"+f2++;
return new BA(0,0x8000000000000,0,k,Z)},DP=function(Z,k){Z=Z.getAttribute(k);
if(Z!=null)return Number(Z)},Ou=function(Z,k){Z=Z.getAttribute(k);
if(Z!=null)return Z==="1"},vA=function(Z,k){Z=DP(Z,k);
return Z!==void 0?Z:null},gG=function(Z,k){Z=Z.getAttribute(k);
if(Z!=null)return iC.test(Z),Z},$mD=function(Z,k){const N={},a=k.getAttribute("ws");
Object.assign(N,a?Z.N[a]:Z.Y);Z=vA(k,"mh");Z!=null&&(N.yy=Z);Z=vA(k,"ju");Z!=null&&(N.textAlign=Z);Z=vA(k,"pd");Z!=null&&(N.b9=Z);Z=vA(k,"sd");Z!=null&&(N.XG=Z);Z=gG(k,"wfc");Z!=null&&(N.windowColor=Z);k=DP(k,"wfo");k!==void 0&&(N.windowOpacity=k/255);return N},xma=function(Z,k){const N={},a=k.getAttribute("wp");
a&&Object.assign(N,Z.C[a]);Z=vA(k,"ap");Z!=null&&(N.yp=Z);Z=DP(k,"cc");Z!=null&&(N.UN=Z);Z=DP(k,"ah");Z!=null&&(N.Hi=Z);Z=DP(k,"rc");Z!=null&&(N.Hj=Z);k=DP(k,"av");k!=null&&(N.Mu=k);return N},GXi=function(Z,k,N,a){let T={};
Object.assign(T,xma(Z,k));Object.assign(T,$mD(Z,k));a?g.pK(T,Z.Y)?(a=Z.L,T=Z.Y):a="_"+f2++:a=k.getAttribute("id")||"_"+f2++;Z=DP(k,"t")+N;k=DP(k,"d")||0x8000000000000;if(T.b9===2||T.b9===3)N=T.Hj,T.Hj=T.UN,T.UN=N;return new BA(Z,k,0,a,T)},wG=function(Z){Z=g.u0(Math.round(Z),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-Z.length)+Z},SeD=function(Z,k,N,a,T){a===0&&(a=0x8000000000000);
const K={};k.wpWinPosId&&Object.assign(K,Z.Y.get(k.wpWinPosId));k.wsWinStyleId&&Object.assign(K,Z.L.get(k.wsWinStyleId));Z=k.rcRowCount;Z!==void 0&&(K.Hj=Z);k=k.ccColCount;k!==void 0&&(K.UN=k);if(K.b9===2||K.b9===3)k=K.Hj,K.Hj=K.UN,K.UN=k;return new BA(N,a,0,T,K)},$0=function(Z){const k=Z.byteOffset;
Z.byteOffset+=1;return Z.V.getUint8(k)},x0=function(Z){const k=Z.byteOffset;
Z.byteOffset+=4;return Z.V.getUint32(k)},JJD=function(Z){if(typeof Z==="string")return!1;
Z=new ezh(Z,0);return o4r(Z)},o4r=function(Z){if(!(Z.byteOffset<Z.V.byteLength)||x0(Z)!==1380139777)return!1;
Z.version=$0(Z);if(Z.version>1)return!1;$0(Z);$0(Z);$0(Z);return!0},zzc=function(Z,k){if(!k)return"";
Z.Y&&Z.U.params.XG!==1&&(k*=-1);return`translate${Z.Y?"X":"Y"}(${k}px)`},UmT=function(Z){Z.dA=Array.from(Z.element.getElementsByClassName("caption-visual-line"));
for(var k=Z.U.params.Hj,N=0,a=0,T=Z.dA.length-1;N<k&&T>-1;){var K=Z.dA[T];a+=Z.Y?K.offsetWidth:K.offsetHeight;N++;T--}Z.O=a;k=Math;N=k.max;isNaN(Z.FS)&&((a=Z.V.UN)?(T=g.TU("SPAN"),g.m_(T,"\u2013".repeat(a)),g.ij(T,PWD(Z,Z.V.p8)),Z.D.appendChild(T),Z.FS=T.offsetWidth,Z.D.removeChild(T)):Z.FS=0);a=Z.D;Z.zt=N.call(k,Z.FS,Z.iq,(Z.Y?a.offsetHeight:a.offsetWidth)+1)},bCF=function(Z,k){UmT(Z);
var N=Z.dA.reduce((a,T)=>(Z.Y?T.offsetWidth:T.offsetHeight)+a,0);
N=Z.O-N;if(N!==Z.tq){const a=N>0&&Z.tq===0,T=N<Z.tq;k||isNaN(N)||a||!T||(g.jX(Z.element,"ytp-rollup-mode"),Z.K(Z.element,"transitionend",Z.hq));g.ij(Z.D,"transform",zzc(Z,N));Z.tq=N}UmT(Z)},Rzh=function(Z,k){Z.V=(N,a)=>{if(N.info.D){var T=N;
if(Z.GX.length>0){for(T=Z.GX.shift();Z.GX.length>0;)T=T.G(Z.GX.shift());T=T.G(N)}if(T){N=T;try{var K=g.Ic(N)*1E3}catch(P){K=N.info.startTime*1E3}try{var y=g.Sw0(N)*1E3}catch(P){y=N.info.duration*1E3}if(K<0||y<0)K<0&&(K=N.info.startTime*1E3),y<0&&(y=N.info.duration*1E3);N.info.startTime=K/1E3;N.info.Y=K/1E3;N.info.duration=y/1E3;N.info.C=y/1E3;const {formatId:Q,Cp:q,startTimeMs:r,durationMs:C}=Z.pY(T);K={formatId:Q,startTimeMs:r,durationMs:C,Uq:q,e9:q};y=pRK(Z.jI,K.startTimeMs);const m=(N=y>=0?Z.jI[y]:
null)?N.startTimeMs+N.durationMs:0,A=K.startTimeMs+K.durationMs;!N||K.startTimeMs-m>Z.U?Z.jI.splice(y+1,0,K):(N.durationMs=Math.max(m,A)-N.startTimeMs,N.e9=Math.max(N.e9,K.e9));a(Z.jI);K=g.Rc(T);a=Z.D;K=K.buffer.slice(K.byteOffset,K.byteLength+K.byteOffset);T=T.info.Y;a.Vz?a.C==null?g.pG(a.logger,350058965,"Null loaded track meta data at captions data received"):k.Hl(K,a.C,T*1E3):g.pG(a.logger,350058965,"Null Representation at captions data received")}else g.pG(Z.logger,350058965,"Empty slice")}else Z.GX.push(N)};
Z.S.addEventListener("sabrCaptionsDataLoaded",Z.V)},pRK=function(Z,k){Z=g.F_(Z,{startTimeMs:k},(N,a)=>N.startTimeMs-a.startTimeMs);
return Z>=0?Z:-Z-2},Mah=function(Z,k){if(!g.N0G(Z)||Z.V!=null&&g.zx(k,Z.V)&&Z.V.V.rawcc!=null)return!1;
k=!!Z.V&&Z.V.isManifestless&&Object.values(Z.V.V).some(N=>g.U8(N,"386"));
Z=!!Z.V&&!Z.V.isManifestless&&g.rNf(Z.V);return k||Z},n4K=function(Z,k,N){const a=[];
for(const T in Z.U.V){if(!Z.U.V.hasOwnProperty(T))continue;const K=Z.U.V[T];if(g.U8(K,N||null)){const y=K.info.captionTrack;y&&y.languageCode===k&&a.push(K)}}return a.length?a[0]:null},IqH=function(Z,k){const N=[];
for(const T in Z.U.V){if(!Z.U.V.hasOwnProperty(T))continue;var a=Z.U.V[T];if(g.U8(a,k||null)){let K=a.info.id,y=K,Q=`.${K}`,q="",r="";if(a=a.info.captionTrack)K=a.languageCode,y=a.displayName,Q=a.vssId,q=a.kind,r=a.id;N.push(new g.RO({id:T,languageCode:K,languageName:y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:q,captionId:r}))}}return N},E4e=function(Z){const k=jqB.length;
if(Z.byteLength<k)return!1;Z=new Uint8Array(Z,0,k);for(let N=0;N<k;N++)if(jqB[N]!==Z[N])return!1;return!0},GE=function(Z){Z=Z.split(":");
let k=0;for(const N of Z)k=k*60+Number(N);return k*1E3},WbJ=function(Z,k,N,a){a=Object.assign({yy:0},a);
return new BA(Z,k,N,"_"+f2++,a)},Yec=function(Z,k,N,a,T,K,y,Q,q){switch(y.tagName){case "b":Q.bold=!0;
break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}for(let C=0;C<y.childNodes.length;C++){var r=y.childNodes[C];if(r.nodeType===3)r=new lC(k,N,a,T.id,r.nodeValue,K||C>0,g.ze(Q)?void 0:Q),q.push(r),T.V.push(r);else{const m={};Object.assign(m,Q);Yec(Z,k,N,a,T,!0,r,m,q)}}},kJF=function(Z,k,N){if(typeof k==="string"||JJD(k))return[{trackData:k,
Av:N}];if(typeof k==="string"&&k.substring(0,6)==="WEBVTT"||typeof k!=="string"&&E4e(k))return[{trackData:k,Av:N}];const a=new DataView(k);if(a.byteLength<=8||a.getUint32(4)!==1718909296)return[];var T=g.UPy(a);if(Z.uq&&T){var K=g.wgU(T),y=g.$PX(T);T=T.segmentNumber;K&&T&&Z.uq.kY(T,K,y)}Z=g.jw(a,1835295092);if(!Z||!Z.length||!Z[0].size)return[];K=[];for(y=0;y<Z.length;y++)T=Z[y],T=new Uint8Array(k,T.dataOffset,T.size-(T.dataOffset-T.offset)),T=g.Lv(T),K.push({trackData:T,Av:N+y*1E3});Zke(a,K,N);return K=
K.filter(Q=>!!Q.trackData)},a1i=function(Z,k,N){Z.V||(Z.V=new NpH);
Z=Z.V.D(k,N);Math.random()<.01&&g.L9(Error("Deprecated subtitles format in web player: WebVTT"));return Z},Zke=function(Z,k,N){var a=g.RV(Z,0,1836476516);
let T=9E4;a&&(T=g.Mr(a)||9E4);a=0;const K=g.jw(Z,1836019558);for(let Q=0;Q<K.length;Q++){var y=K[Q];Q<k.length&&(y=g.RV(Z,y.dataOffset,1953653094))&&(y=g.RV(Z,y.dataOffset,1952867444))&&(y=g.IV(y)/T*1E3,Q===0&&(a=y),k[Q].Av=y-a+N||N*Q*1E3)}},Tpe=function(Z){const k={};
if(Z=g.co(Z))k.lang=Z,g.Cgi.test(Z)&&(k.b9=1);return k},KQa=function(Z){const k=!!Z.S.TM()?.xW();
return Z.D==="HLS"&&k?!0:Z.MX&&k&&Z.D!=="LIVE"&&Z.D!=="SABR_LIVE"},e3=function(Z,k,N=!1){const a=S3.p8;
Z.L={};Object.assign(Z.L,S3);Z.L.p8={};Object.assign(Z.L.p8,a);Z.G={p8:{}};var T=k.backgroundOverride?Z.G:Z.L,K=k.background||a.background;iC.test(K);T.p8.background=K;T=k.colorOverride?Z.G:Z.L;K=k.color||a.color;iC.test(K);T.p8.color=K;T=k.windowColorOverride?Z.G:Z.L;K=k.windowColor||S3.windowColor;iC.test(K);T.windowColor=K;T=k.backgroundOpacityOverride?Z.G:Z.L;K=k.backgroundOpacity;K==null&&(K=a.backgroundOpacity);T.p8.backgroundOpacity=K;T=k.fontSizeIncrementOverride?Z.G:Z.L;K=k.fontSizeIncrement;
K==null&&(K=a.fontSizeIncrement);T.p8.fontSizeIncrement=K;K=k.fontStyleOverride?Z.G:Z.L;T=k.fontStyle;T==null&&(T=a.bold&&a.italic?3:a.bold?1:a.italic?2:0);K=K.p8;switch(T){case 1:K.bold=!0;delete K.italic;break;case 2:delete K.bold;K.italic=!0;break;case 3:K.bold=!0;K.italic=!0;break;default:delete K.bold,delete K.italic}T=k.textOpacityOverride?Z.G:Z.L;K=k.textOpacity;K==null&&(K=a.textOpacity);T.p8.textOpacity=K;T=k.windowOpacityOverride?Z.G:Z.L;K=k.windowOpacity;K==null&&(K=S3.windowOpacity);T.windowOpacity=
K;T=k.charEdgeStyleOverride?Z.G:Z.L;K=k.charEdgeStyle;K==null&&(K=a.charEdgeStyle);T.p8.charEdgeStyle=K;T=k.fontFamilyOverride?Z.G:Z.L;K=k.fontFamily;K==null&&(K=a.fontFamily);T.p8.fontFamily=K;Z.loaded&&Z.qX();N&&g.Z_("yt-player-caption-display-settings",k,2592E3)},oM=function(Z,k,N){k&&!Z.Vz?(k=wRJ({b9:0,
lang:"en-GB"}),Z.Vz=[k,new lC(k.start,k.end-k.start,0,k.id,N??"Captions look like this")],Z.player.f8(Z.Vz)):!k&&Z.Vz&&(yRD(Z,Z.Vz),Z.Vz=null)},QaT=function(Z){if(!Z.S.isInline())return g.kh("yt-player-sticky-caption")},Jp=function(Z){let k=void 0;
const N=g.QC().Aq(65);if(g.fQ(Z.kW)&&N!=null){if(QaT(Z)!=null)return!1;k=!N}return k},q3B=function(Z){if(Z.kW.g0===1||Z.videoData.D4===1||g.ID(Z.videoData,"yt:cc")==="alwayson")return!0;
let k;Z.videoData.captionTracks.length&&(k=Z.getAudioTrack().U);if(Z.kW.g0===2){if(g.fQ(Z.kW))var N=Z.kW.B("enable_player_captions_persistence_state_machine")?Z.kW.B("enable_player_captions_persistence_state_machine")?g.kh("yt-player-caption-persistence"):void 0:QaT(Z);else if(Z.storage)try{N=Z.storage.get("module-enabled")}catch(T){Z.storage.remove("module-enabled")}else N=null;if(N!=null)return!!N}N=cA(Z.player.getAudioTrack(),g.fQ(Z.kW));const a=g.ID(Z.videoData,"yt:cc");if(Jp(Z)===void 0){if(N===
"CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return a?a==="on":!0;if(N==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return a==="on"}else return a==="on";return k==="ON"||g.ID(Z.videoData,"yt:cc")==="on"},zE=function(Z,k=!1){if(Z.U&&!k||!Z.videoData.captionTracks.length)return!1;
Z=Z.getAudioTrack();return!!Z.V||Z.U==="FORCED_ON"},rRc=function(Z,k){if(Z.U){var N=Z.S.TM().lq().textTracks,a=null;
Z.D==="HLS"?a=Z.U.getId():a=Z.U.toString();for(let K=0;K<N.length;K++){var T=N[K];T.id===a&&(k?T.mode!=="showing"&&(T.mode="showing",T=Z.U,Z.F8(T,!!T,Uu(Z)?"g":Z.j?"m":"s")):T.mode==="showing"&&(T.mode="disabled"))}}},Uu=function(Z){const k=bC(Z);
return!!k&&Z.U===k},CkT=function(Z,k){if(Z.D==="HLS")return!1;
g.aC(Z.videoData)&&(k=!0);k||(k=Z.D==="TTS"?!1:Z.D==="INNERTUBE"?!1:!0);return k||Z.kW.B("web_deprecate_always_includes_asr_setting")&&g.fQ(Z.kW)?!0:!!g.QC().Aq(66)},bC=function(Z){return Z.N&&Z.N.V},p2=function(Z,k){if(!Z.V)return null;
if(Z.N&&Z.N.Y)return Z.N.Y;k=CkT(Z,k);k=g.V9(Z.V.V,k);let N=null;if(W1c(Z.kW)){var a=Z.S.isInline()?void 0:g.kh("yt-player-caption-sticky-language");var T=[a,Z.videoData.captionsLanguagePreference,Z.kW.captionsLanguagePreference,g.ID(Z.videoData,"yt:cc_default_lang")];let Q=!1;for(let q=0;q<T.length;q++){const r=T[q];if(r){Q=!0;for(var K=0;K<k.length;K++)if(g.co(k[K])===r)return k[K];for(K=0;K<k.length;K++)if(g.co(k[K]).split("-")[0]===r.split("-")[0])return k[K]}}if(Q&&Z.V&&(T=Z.V.N,T.length))for(var y of T)if(y.languageCode===
a){N=y;break}}else for(y=[Z.videoData.captionsLanguagePreference,Z.kW.captionsLanguagePreference,g.ID(Z.videoData,"yt:cc_default_lang")],a=0;a<y.length;a++)for(T=0;T<k.length;T++)if(g.co(k[T])===y[a])return k[T];y=null;Z.N&&Z.N.D&&(y=Z.N.D);y||(y=k.find(Q=>Q.isDefault)||null);
y||(y=k[0]||bC(Z));y&&N&&g.co(y).split("-")[0]!==N.languageCode.split("-")[0]&&(y=E9e(y,N));return y},j3=function(Z,k,N){Z.loaded&&Z.unload();
N!=null&&(Z.j=N,Z.j&&(Z.kW.B("enable_player_captions_persistence_state_machine")?RM(Z,!!k):g.fQ(Z.kW)?M5(Z,!!k):n2(Z,!!k)));k!==null||zE(Z,!0)||Z.F8(k,!!k,Z.j?"m":"s");Z.U=k;zE(Z)&&(Z.U=bC(Z));IM(Z,Z.U??void 0);Z.load()},RM=function(Z,k){Z.kW.B("enable_player_captions_persistence_state_machine")&&g.Z_("yt-player-caption-persistence",k,3122064E3)},M5=function(Z,k){Z.S.isInline()||g.Z_("yt-player-sticky-caption",k,2592E3)},n2=function(Z,k){if(Z.storage)try{Z.storage.set("module-enabled",k)}catch(N){}},
IM=function(Z,k){Z.kW.B("html5_modify_caption_vss_logging")&&(Z.videoData.dZ=k)},sac=function(Z,k){var N=Z.zt[k.id];
N&&N.U!==k&&(N.dispose(),delete Z.zt[k.id],N=null);N||(N=mQr(Z,k))&&(Z.zt[k.id]=N)},ARJ=function(Z,k){const N=k.windowId;
Z.tq[N]||(Z.tq[N]=[]);Z.tq[N].push(k)},mQr=function(Z,k){const N=Pkn(Z);
if(!N)return null;var a=Z.U?g.co(Z.U):null;a&&g.Cgi.test(a)&&(k.params.b9=1);var T=Z.Tt.getPlayerSize();a=T.height*Z.O.height;T=T.width*Z.O.width;Z.kW.playerStyle!=="google-live"||Z.L.isDefault||Object.assign(k.params,Z.L);switch(k.params.yy!=null?k.params.yy:k.V.length>1?1:0){case 1:return new cRe(k,Z.L,Z.G,N.width,N.height,T,a,Z.kW.experiments,Z.Qz.bind(Z),Z.S);case 2:return new Hkn(k,Z.L,Z.G,N.width,N.height,T,a,Z.kW.experiments,Z.Qz.bind(Z),Z.S);default:return new Eu(k,Z.L,Z.G,N.width,N.height,
T,a,Z.kW.experiments,Z.Qz.bind(Z),Z.S)}},Pkn=function(Z){let k=Z.Tt.getVideoContentRect(!0).height,N=Z.Tt.getVideoContentRect(!0).width;
if(!k||!N)return null;k*=Z.O.height;N*=Z.O.width;return{width:N,height:k}},yRD=function(Z,k){Z.player.h$(k);
for(const N of k)g.qF(Z.FS,N);PA(Z.vD)},dQB=function(Z,k){if(!Z.V)return{};
if(k){g.ze(k)||Z.AQ(k.vss_id,"m");if(Z.Y&&Z.D!=="HLS"||!g.lf(k))return;if(g.ze(k)){j3(Z,null,!0);return}let a;var N=g.V9(Z.V.V,!0);for(let T=0;T<N.length;T++){const K=N[T];K.languageCode!==k.languageCode||a&&(K.languageName!==k.languageName||(K.captionId||"")!==(k.captionId||"")||g.AQ(K)!==k.displayName)||(a=k.translationLanguage?E9e(K,k.translationLanguage):K)}Z.Uz(k.position);!a||a===Z.U&&Z.loaded||(k=g.qr(),N=g.co(a),k.length&&N===k[k.length-1]||(k.push(N),g.Z_("yt-player-caption-language-preferences",
k)),W1c(Z.kW)&&!Z.S.isInline()&&g.Z_("yt-player-caption-sticky-language",N,2592E3),j3(Z,a,!0))}else return Z.loaded&&Z.U&&!Uu(Z)?g.Po(Z.U):{};return""};
g.Zg.prototype.kY=g.ay(65,function(Z,k,N){this.U.set(Z,{wG:k,Tr:N})});
g.kD.prototype.kY=g.ay(64,function(Z,k,N){this.Vz.kY(Z,k,N)});
g.JK.prototype.O=g.ay(63,function(){return!1});
g.JK.prototype.Y=g.ay(62,function(){});
g.zP.prototype.Y=g.ay(61,function(Z,k,N){this.jm();k=this.G(Z,k);const a=this.rA.X().B("html5_report_captions_ctmp_qoe"),T=(0,g.z)();this.D();jIH(this,k,{format:"RAW",onSuccess:K=>{this.U=null;if(a){var y=(K.responseText.length/1024).toFixed();const Q=(0,g.z)();this.videoData.U6("capresp",{ms:Q-T,kb:y})}y=K.getResponseHeader&&K.getResponseHeader("Content-Length")?Number(K.getResponseHeader("Content-Length")):0;N.Hl(K.responseText,Z,void 0,void 0,y)},
onError:a?K=>{this.videoData.U6("capfail",{status:K?.status??0})}:void 0,
withCredentials:!0})});
g.Uy.prototype.Y=g.ay(60,function(Z,k,N){this.jm();k=this.G(Z,k);this.D();this.U=g.SD(k,{format:"RAW",onSuccess:a=>{this.U=null;const T=a.getResponseHeader&&a.getResponseHeader("Content-Length")?Number(a.getResponseHeader("Content-Length")):0;N.Hl(a.responseText,Z,void 0,void 0,T)},
withCredentials:!0})});
g.WE.prototype.j=g.ay(59,function(){const Z=g.Rk(document,"track",void 0,this.V);for(let k=0;k<Z.length;k++)g.rM(Z[k])});
g.k$.prototype.j=g.ay(58,function(){this.mediaElement.j()});
g.WE.prototype.dA=g.ay(57,function(){return!(!this.V.textTracks||!this.V.textTracks.addEventListener)});
g.k$.prototype.dA=g.ay(56,function(){return this.mediaElement.dA()});
g.WE.prototype.xW=g.ay(55,function(){return!!this.V.textTracks});
g.k$.prototype.xW=g.ay(54,function(){return this.mediaElement.xW()});
g.WE.prototype.Vz=g.ay(53,function(Z){for(let k=0;k<Z.length;k++)this.V.appendChild(Z[k])});
g.k$.prototype.Vz=g.ay(52,function(Z){this.mediaElement.Vz(Z)});
g.cH.prototype.S7=g.ay(40,function(Z){return this.app.PA({playerType:void 0}).S7(Z)});
g.LX.prototype.S7=g.ay(39,function(Z){return this.fp.kX.S7(Z)});
g.iw.prototype.S7=g.ay(38,function(Z){return this.jO().some(k=>k.namespace===Z)});
g.jz.prototype.S7=g.ay(37,function(){return!1});
g.cH.prototype.AQ=g.ay(35,function(Z,k){this.app.wA().AQ(Z,k)});
g.LX.prototype.AQ=g.ay(34,function(Z,k){this.fp.AQ(Z,k)});
g.BH.prototype.AQ=g.ay(33,function(Z,k){Z=[Z,k];g.MX(this,g.j_(this.provider),"cfi",Z)});
g.vH.prototype.AQ=g.ay(32,function(Z,k){this.qoe&&this.qoe.AQ(Z,k)});
g.fX.prototype.AQ=g.ay(31,function(Z,k){this.WA.AQ(Z,k)});
g.jz.prototype.AQ=g.ay(30,function(){});
g.cH.prototype.F8=g.ay(29,function(Z,k,N){this.app.wA().F8(Z,k,N)});
g.LX.prototype.F8=g.ay(28,function(Z,k,N){this.fp.F8(Z,k,N)});
g.BH.prototype.F8=g.ay(27,function(Z,k,N){if(this.vD!==Z||this.pF!==k)k=k==="rawcc"?"":k,N=[Z,k,this.vD,N],g.MX(this,g.j_(this.provider),"cfs",N),this.vD=Z,this.pF=k});
g.vH.prototype.F8=g.ay(26,function(Z,k,N){this.qoe&&this.qoe.F8(Z,k,N)});
g.fX.prototype.F8=g.ay(25,function(Z,k,N){this.WA.F8(Z,k,N)});
g.jz.prototype.F8=g.ay(24,function(){});
g.TP.prototype.eJ=g.ay(3,function(Z){return(Z=this.D(Z))?Z.V:0});
g.yl.prototype.eJ=g.ay(2,function(){return 0});
var NUi=/#(.)(.)(.)/,kXB=/^#(?:[0-9a-f]{3}){1,2}$/i,rJe={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},X1F={en:"English"},LQa=class extends g.JK{constructor(Z){super(Z);this.U=new Set}L(Z){var k=this.rA.TM();if(k&&k.lq()){k=k.lq().textTracks;for(const N of k)N.kind==="subtitles"&&!this.U.has(N.language)&&N.language&&(g.J1(this.V,new g.RO({languageCode:N.language,languageName:N.language,kind:N.kind,id:N.id,displayName:X1F[N.label]||N.label,vss_id:`.${N.language}`})),this.U.add(N.language))}g.V9(this.V).length>
0&&Z.Yd()}},VtF=class{constructor(){this.segments=[]}contains(Z){Z=g.F_(this.segments,Z);return Z>=0||Z<0&&(-Z-1)%2===1}length(){return this.segments.length/2}},FQe=class extends g.jR{constructor(Z,k,N,a,T,K){super();this.policy=Z;this.player=k;this.l3=N;this.C=a;this.L=T;this.O=K;this.Y=new VtF;this.G=-1;this.U=this.D=this.V=null;this.zt=0;this.j=new g.Uc(this.Vz,1E3,this);this.events=new g.tt(this);g.u(this,this.j);g.u(this,this.events);this.events.K(k,"SEEK_COMPLETE",this.N);this.N();this.Vz()}YW(){super.YW();
this.U&&this.U.cancel()}N(){this.seekTo(this.player.getCurrentTime())}seekTo(Z){Z-=this.player.mx();const k=this.V;this.V=g.bf(this.l3.G(Z).Vi);k!==this.V&&this.O&&this.O()}reset(){this.Y=new VtF;this.G=-1;this.U&&(this.U.cancel(),this.U=null)}Vz(){this.jm();var Z;if(Z=this.V!=null)Z=this.V,Z=Z.l3.Y(Z);if(Z&&!this.U&&!(this.V&&this.V.startTime-this.player.getCurrentTime()>30)){Z=this.V;Z=Z.l3.vD(Z);const T=Z.Vi[0];if(this.player.getVideoData()?.enableServerStitchedDai){var k=this.player.gG();if(k){var N=
T.l3.info.id;const K=T.Cp;var a=Z.Vi[0].Y;if(this.policy.vD){if(k=g.V$f(k,a,K,N,3))Z.Y=k}else if(N=k.cM(a,K,N,3))if(a=2,k.uN.has(K)?a=0:g.tz(k,K)&&(a=1),k=a,k===0)N&&(Z.V=new g.hY(N));else if(k===2){this.j.start();Kbh(this)&&this.seekTo(this.player.getCurrentTime());return}}}T.l3.index.Of(T.Cp)?(this.Y.contains(Z.Vi[0].Cp)||yJr(this,Z),this.V=g.bf(Z.Vi)):Kbh(this)&&this.seekTo(this.player.getCurrentTime())}this.j.start()}},tth=class extends g.JK{constructor(Z,k){super(k);this.U=Z;this.S=k;this.C=
null;this.Vz=!1;this.logger=new g.bI("caps");this.zt=g.zx(this.S,this.U)}Y(Z,k,N){this.D();k=QqJ(this,Z.getId());k||(k=Z.languageCode,k=this.U.isManifestless?qeF(this,k,"386"):qeF(this,k));if(k){var a=(k.index.eJ(k.index.N7())-k.index.getStartTime(k.index.N7()))*1E3,T=new g.tYy(this.S.X());this.C=new FQe(T,this.S,k,(K,y)=>{N.Hl(K,Z,y,a)},this.zt||g.Sx(k.info),()=>{this.C&&this.C.reset();
this.Vz=!0})}}O(){const Z=this.Vz;
this.Vz=!1;return Z}L(Z){var k=this.S.X().B("html5_fallback_if_rawcc_missing");const N=this.U.V.rawcc!=null;if(!this.zt||!N&&k)k=this.U.isManifestless?CWc(this,"386"):CWc(this);else{if(!N){g.pG(this.logger,386248249,"rawcc used but unavailable");return}k=[new g.RO({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.RO({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const a of k)g.J1(this.V,
a);Z.Yd()}D(){this.C&&(this.C.dispose(),this.C=null)}G(){return""}},iC=/^#(?:[0-9a-f]{3}){1,2}$/i;var hka=["left","right","center","justify"];var Eu=class extends g.E{constructor(Z,k,N,a,T,K,y,Q,q,r){const C=r.isInline()&&!0,m={};Object.assign(m,k);Object.assign(m,Z.params);Object.assign(m,N);const A={};Object.assign(A,k.p8);Z.params.p8&&Object.assign(A,Z.params.p8);Object.assign(A,N.p8);C&&(m.windowOpacity=.6,A.backgroundOpacity=0);m.p8=A;const P=m.b9===1,d=[{J:"span",Z:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],h=Q.yz("caption_edit_on_hover")&&r.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
h&&d.unshift({J:"button",Z:"caption-edit",W:{tabindex:"0","aria-label":aqa()},A:[{J:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},A:[{J:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({J:"div",Z:"caption-window",W:{id:`${"caption-window"}-${Z.id}`,dir:P?"rtl":"ltr",tabindex:"0",lang:m.lang},A:d});this.G=
[];this.vD=!1;this.U=Z;this.Rq=this.Sm=null;this.LC=K;this.gD=y;this.j=null;this.maxWidth=K*.96;this.maxHeight=y*.96;this.V=m;this.tW=N;this.xW=k;this.D=this.Lp("captions-text");this.Ap=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Qz=mmi(a,T,K,y);this.FN=q;h&&(this.L=this.Lp("caption-edit"),this.K(this.L,"click",()=>{this.FN()}));
this.type=0;this.Kp=this.Qz*sqi(A);this.xl=C;this.s6=Q.yz("enable_centered_caption_for_tvfilm_video")&&r.getVideoData().isTvfilmVideo;this.N=r.X().Yl().V.Aq(g.Lwy);Z=new g.tU(this.element,!0);g.u(this,Z);Z.subscribe("dragstart",this.NW,this);Z.subscribe("dragmove",this.Ke,this);Z.subscribe("dragend",this.rD,this);this.O6=this.Tt=this.pF=this.qX=0;Z="";this.V.windowOpacity&&(Z=HA(this.V.windowColor),Z="rgba("+Z[0]+","+Z[1]+","+Z[2]+","+this.V.windowOpacity+")");k={"background-color":Z,display:this.V.isVisible===
!1?"none":"","text-align":hka[this.V.textAlign]};this.Ap&&(k["border-radius"]=Z?`${this.Kp/8}px`:"");(this.Y=this.U.params.b9===2||this.U.params.b9===3)&&AJc(this,this.element);g.ij(this.element,k);C&&this.element.parentElement?.style.setProperty("--caption-window-color",Z);switch(this.V.yp){case 0:case 1:case 2:g.jX(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jX(this.element,"ytp-caption-window-bottom")}}NW(Z,k){this.Tt=Z;this.O6=k;const N=g.Mi(this.element,this.element.parentElement);
this.qX=Z-N.x;this.pF=k-N.y}Ke(Z,k){if(Z!==this.Tt||k!==this.O6){g.I3(this.element,"ytp-dragging")||g.jX(this.element,"ytp-dragging");var N=g.I4(this.element);Z=Z-this.qX-.02*this.LC;var a=k-this.pF-.02*this.gD,T=(Z+N.width/2)/this.maxWidth*3;T=Math.floor(g.u0(T,0,2));var K=(a+N.height/2)/this.maxHeight*3;K=Math.floor(g.u0(K,0,2));k=T+K*3;Z=(Z+T/2*N.width)/this.maxWidth;Z=g.u0(Z,0,1)*100;N=(a+K/2*N.height)/this.maxHeight;N=g.u0(N,0,1)*100;this.U.params.yp=k;this.U.params.Mu=N;this.U.params.Hi=Z;this.U.params.isDefault=
!1;this.V.yp=k;this.V.Mu=N;this.V.Hi=Z;this.V.isDefault=!1;this.xW.yp=k;this.xW.Mu=N;this.xW.Hi=Z;this.xW.isDefault=!1;this.hp()}}rD(){g.Wp(this.element,"ytp-dragging")}hp(){this.C(this.G)}C(Z){var k=this.xl?0:Math.min(this.jY(),this.maxWidth),N=this.HA(),a=this.xl;if(a){var T=getComputedStyle(this.D.parentNode);T=Xg(T.borderLeftWidth)+Xg(T.borderRightWidth)+Xg(T.paddingLeft)+Xg(T.paddingRight)}else T=0;const K=T;T="";this.U.params.b9===3&&(T="rotate(180deg)");var y=a?`calc(${"96%"} - ${K}px)`:"96%";
g.ij(this.element,{top:0,left:0,right:"",bottom:"",width:k?`${k}px`:"",height:N?`${N}px`:"","max-width":y,"max-height":y,margin:"",transform:""});this.MX(Z);T={transform:T,top:"",left:"",width:k?`${k}px`:"",height:N?`${N}px`:"","max-width":"","max-height":""};y=this.V.yp;var Q=this.V.Hi;const q=this.V.Mu;this.s6&&y!=null&&(Q=50,y=Math.floor(y/3)*3+1);Q=Q*.96+2;switch(y){case 0:case 3:case 6:(a=this.V.p8.fontSizeIncrement)&&a>0&&this.V.b9!==2&&this.V.b9!==3&&(Q=Math.max(Q/(1+a*2),2));T.left=`${Q}%`;
break;case 1:case 4:case 7:T.left=`${Q}%`;Q=0;this.N||(Q=this.D.offsetWidth);k||Q?(k=k||Q+1,T.width=`${k}px`,T["margin-left"]=a?`${k/-2-K/2}px`:`${k/-2}px`):(this.N&&(T.width="max-content"),T.transform+=" translateX(-50%)");break;case 2:case 5:case 8:T.right=`${100-Q}%`}a=q*.96+2;switch(y){case 0:case 1:case 2:T.top=`${a}%`;break;case 3:case 4:case 5:T.top=`${a}%`;a=0;this.N||(a=this.element.clientHeight);(N=N||a)?(T.height=`${N}px`,T["margin-top"]=`${N/-2}px`):T.transform+=" translateY(-50%)";break;
case 6:case 7:case 8:T.bottom=`${100-a}%`}g.ij(this.element,T);if(this.L){if(this.N)N=this.Kp;else{if(this.s6&&Z.length===0)Z=0;else{N=1;for(a=0;a<Z.length;a++)T=Z[a],typeof T.text==="string"&&(N+=T.text.split("\n").length-1,T.append||a===0||N++);Z=N}N=this.s6?Z>0?this.D.offsetHeight/Z:0:this.D.offsetHeight/Z}this.L.style.height=`${N}px`;this.L.style.width=`${N}px`;this.element.style.paddingLeft=`${N+5}px`;this.element.style.paddingRight=`${N+5}px`;this.N||(Z=Number(this.element.style.marginLeft.replace("px",
""))-N-5,N=Number(this.element.style.marginRight.replace("px",""))-N-5,this.element.style.marginLeft=`${Z}px`,this.element.style.marginRight=`${N}px`)}}MX(Z){let k;for(k=0;k<Z.length&&Z[k]===this.G[k];k++);if(this.vD||this.G.length>k)k=0,this.vD=!1,this.G=[],this.j=this.Rq=this.Sm=null,g.Qp(this.D);for(;k<Z.length;k++)dm_(this,Z[k])}jY(){return 0}HA(){return 0}toString(){return super.toString()}};var l1a=class{constructor(){this.D=this.time=this.mode=this.U=0;this.Y=new uDT(this);this.L=new uDT(this);this.V=[];this.clear()}clear(){this.D=this.time=this.mode=0;this.V=[];this.reset()}reset(){this.mode=0;this.Y.reset(0);this.L.reset(1)}},XRr=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],f1r=class{constructor(){this.type=0}set(Z){this.type=Z}get(){return this.type}},BpK=class{constructor(){this.state=this.pI=this.PX=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}cG(){return this.state!==0}matches(Z,k){return this.cG()&&Z===this.PX&&k===this.pI}},DQJ=class{constructor(){this.timestamp=this.V=0}reset(){this.timestamp=
this.V=0}},WA=class{constructor(Z){this.L=Z;this.D=[];this.V=this.U=this.row=0;this.style=new f1r;this.Y=0;for(Z=0;Z<=15;Z++){this.D[Z]=[];for(let k=0;k<=32;k++)this.D[Z][k]=new DQJ}}updateTime(Z){for(let k=1;k<=15;++k)for(let N=1;N<=32;++N)this.D[k][N].timestamp=Z}debugString(){let Z="\n";for(let k=1;k<=15;++k){for(let N=1;N<=32;++N){const a=this.D[k][N];Z=a.V===0?Z+"_":Z+String.fromCharCode(a.V)}Z+="\n"}return Z}reset(Z){for(let k=0;k<=15;k++)for(let N=0;N<=32;N++)this.D[k][N].reset();this.Y=Z;
this.V=0;this.U=this.row=1}},hzH=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],uln=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],lqK=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],fqh=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Oki=class{constructor(Z){this.D=Z;this.L=0;this.style=new f1r;this.G=new WA(this.D);this.j=new WA(this.D);this.text=new WA(this.D);this.U=this.G;this.Y=this.j;this.V=this.U}reset(Z,k){this.L=k;this.style.set(2);this.U=this.G;this.Y=this.j;this.V=this.U;const N=(Z<<2)+(k<<1);this.G.reset(N);this.j.reset(N);
this.text.reset((Z<<2)+(k<<1)+1)}},uDT=class{constructor(Z){this.V=Z;this.L=0;this.D=new Oki(this.V);this.G=new Oki(this.V);this.U=new BpK;this.Y=this.D}reset(Z){this.L=Z;this.U.clear();this.Y=this.D;this.D.reset(Z,0);this.G.reset(Z,1)}};var vlH=class{Y(){}};var lC=class extends g.pe{constructor(Z,k,N,a,T,K=!1,y=null){super(Z,Z+k,{priority:N,namespace:"captions"});this.windowId=a;this.text=T;this.append=K;this.V=y}toString(){return super.toString()}};var Y0=class extends g.jR{reset(){}};var BA=class extends g.pe{constructor(Z,k,N,a,T){super(Z,Z+k,{priority:N,namespace:"captions"});this.id=a;this.params=T;this.V=[]}toString(){return super.toString()}},f2=0;var ikB=class extends Y0{constructor(Z){super();this.Y=Z;this.pens={};this.C={};this.N={};this.L="_"+f2++;this.j={};this.U=this.V=null;this.G=!0}reset(){this.j={};this.U=this.V=null;this.G=!0}D(Z,k){Z=Z.firstChild;Z.getAttribute("format");k=k||0;Number.isFinite(k);Z=Array.from(Z.childNodes);for(var N of Z)if(N.nodeType===1)switch(N.tagName){case "head":var a=N;break;case "body":var T=N}if(a){a=Array.from(a.childNodes);for(var K of a)if(K.nodeType===1)switch(K.tagName){case "pen":N=K.getAttribute("id");
a=this.pens;Z={};var y=K.getAttribute("p");y&&Object.assign(Z,this.pens[y]);y=Ou(K,"b");y!=null&&(Z.bold=y);y=Ou(K,"i");y!=null&&(Z.italic=y);y=Ou(K,"u");y!=null&&(Z.underline=y);y=vA(K,"et");y!=null&&(Z.charEdgeStyle=y);y=vA(K,"of");y!=null&&(Z.offset=y);y=gG(K,"bc");y!=null&&(Z.background=y);y=gG(K,"ec");y!=null&&(Z.Mv=y);y=gG(K,"fc");y!=null&&(Z.color=y);y=vA(K,"fs");y!=null&&y!==0&&(Z.fontFamily=y);y=DP(K,"sz");y!==void 0&&(Z.fontSizeIncrement=y/100-1);y=DP(K,"bo");y!==void 0&&(Z.backgroundOpacity=
y/255);y=DP(K,"fo");y!==void 0&&(Z.textOpacity=y/255);y=vA(K,"rb");y!=null&&y!==10&&y!==0&&(Z.UP=y>10?y-1:y);y=vA(K,"hg");y!=null&&(Z.Jj=y);a[N]=Z;break;case "ws":a=K.getAttribute("id");this.N[a]=$mD(this,K);break;case "wp":a=K.getAttribute("id"),this.C[a]=xma(this,K)}}if(T){K=[];T=Array.from(T.childNodes);for(h of T)if(h.nodeType===1)switch(h.tagName){case "w":this.V=GXi(this,h,k,!1);(T=this.j[this.V.id])&&T.end>this.V.start&&(T.end=this.V.start);this.j[this.V.id]=this.V;K.push(this.V);break;case "p":var Q=
h;Z=k;T=[];a=Q.getAttribute("w")||this.L;N=!!Ou(Q,"a");Z=(DP(Q,"t")||0)+Z;y=DP(Q,"d")||5E3;N||(!this.G&&this.U&&this.U.windowId===a&&this.U.end>Z&&(this.U.end=Z),this.U&&this.U.text==="\n"&&(this.U.text=""));const B=N?6:5;var q=Q.getAttribute("p");q=q?this.pens[q]:null;const v=Array.from(Q.childNodes);v.length&&(this.G=Q.getAttribute("d")!=null);for(Q=0;Q<v.length;Q++){var r=v[Q],C=void 0;Q>0&&(N=!0);let O;r.nodeType===1&&(O=r);if(O&&O.tagName==="s"){if((r=(r=O.getAttribute("p"))?this.pens[r]:null)&&
r.UP&&(r.UP===1?(r=v.slice(Q,Q+4),r.length===4&&(C=g4H(Z,y,a,N,B,r,this.pens),Q+=3)):C=g4H(Z,y,a,N,B,[O],this.pens)),!C){var m=O;C=Z;r=y;var A=a,P=N;const x=m.textContent?m.textContent:"";var d=m.getAttribute("p");d=d?this.pens[d]:null;m=DP(m,"t")||0;C=new lC(C+m,r-m,B,A,x,P,d)}}else C=new lC(Z,y,B,a,r.textContent||"",N,q);T.push(C);this.U=C}if(T.length>0){T[0].windowId===this.L&&(this.V=GXi(this,h,k,!0),K.push(this.V));for(const O of T)O.windowId=this.V.id,this.V.V.push(O),K.push(O)}}var h=K}else h=
[];return h}};var gl_=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),w1r=class extends Y0{constructor(Z){super();this.G=Z;this.V=new Map;this.Y=new Map;this.L=new Map;this.U=new Map}reset(){this.U.clear()}D(Z,k){Z=JSON.parse(Z);if(!Z)return[];if(Z.pens){var N=Z.pens,a=0;for(var T of N){N={};var K=T.pParentId;K&&Object.assign(N,this.V.get(K));T.bAttr&&(N.bold=!0);T.iAttr&&(N.italic=!0);T.uAttr&&(N.underline=!0);K=T.ofOffset;K!=null&&(N.offset=K);T.szPenSize!==void 0&&(N.fontSizeIncrement=T.szPenSize/100-1);
K=T.etEdgeType;K!=null&&(N.charEdgeStyle=K);T.ecEdgeColor!==void 0&&(N.Mv=wG(T.ecEdgeColor));K=T.fsFontStyle;K!=null&&K!==0&&(N.fontFamily=K);T.fcForeColor!==void 0&&(N.color=wG(T.fcForeColor));T.foForeAlpha!==void 0&&(N.textOpacity=T.foForeAlpha/255);T.bcBackColor!==void 0&&(N.background=wG(T.bcBackColor));T.boBackAlpha!==void 0&&(N.backgroundOpacity=T.boBackAlpha/255);(K=T.rbRuby)&&K!==10&&(N.UP=K>10?K-1:K,N.textEmphasis=gl_.get(N.UP));T.hgHorizGroup&&(N.Jj=T.hgHorizGroup);this.V.set(a++,N)}}if(Z.wsWinStyles){a=
Z.wsWinStyles;T=0;for(var y of a)a={},(N=y.wsParentId)?Object.assign(a,this.L.get(N)):Object.assign(a,this.G),y.mhModeHint!==void 0&&(a.yy=y.mhModeHint),y.juJustifCode!==void 0&&(a.textAlign=y.juJustifCode),y.pdPrintDir!==void 0&&(a.b9=y.pdPrintDir),y.sdScrollDir!==void 0&&(a.XG=y.sdScrollDir),y.wfcWinFillColor!==void 0&&(a.windowColor=wG(y.wfcWinFillColor)),y.wfoWinFillAlpha!==void 0&&(a.windowOpacity=y.wfoWinFillAlpha/255),this.L.set(T++,a)}if(Z.wpWinPositions){T=Z.wpWinPositions;y=0;for(var Q of T)T=
{},(a=Q.wpParentId)&&Object.assign(T,this.Y.get(a)),Q.ahHorPos!==void 0&&(T.Hi=Q.ahHorPos),Q.apPoint!==void 0&&(T.yp=Q.apPoint),Q.avVerPos!==void 0&&(T.Mu=Q.avVerPos),Q.ccCols!==void 0&&(T.UN=Q.ccCols),Q.rcRows!==void 0&&(T.Hj=Q.rcRows),this.Y.set(y++,T)}if(Z.events){Z=Z.events;Q=[];for(const e of Z)if(y=(e.tStartMs||0)+k,T=e.dDurationMs||0,e.id)a=String(e.id),Z=SeD(this,e,y,T,a),Q.push(Z),this.U.set(a,Z);else{e.wWinId?a=e.wWinId.toString():(a="_"+f2++,Z=SeD(this,e,y,T,a),Q.push(Z),this.U.set(a,Z));
Z=Q;var q=e;T===0&&(T=5E3);N=this.U.get(a);const Ki=(K=!!q.aAppend)?6:5,yf=q.segs;let Jy=null;q.pPenId&&(Jy=this.V.get(q.pPenId));for(q=0;q<yf.length;q++){var r=yf[q],C=r.utf8;if(C){var m=r.tOffsetMs||0;let hy=null;r.pPenId&&(hy=this.V.get(r.pPenId));if((N.params.yy!=null?N.params.yy:N.V.length>1?1:0)===2&&K&&C==="\n")continue;r=null;var A=[],P;if(P=hy&&hy.UP===1)a:{P=yf;var d=q;if(d+3>=P.length||!P[d+1].pPenId||!P[d+2].pPenId||!P[d+3].pPenId){P=!1;break a}var h=P[d+1].pPenId;(h=this.V.get(h))&&h.UP&&
h.UP===2?(h=P[d+2].pPenId,h=this.V.get(h),!h||!h.UP||h.UP<3?P=!1:(h=P[d+3].pPenId,P=(h=this.V.get(h))&&h.UP&&h.UP===2?!0:!1)):P=!1}if(P)m=yf[q+1].utf8,r=yf[q+3].utf8,P=yf[q+2].utf8,d=this.V.get(yf[q+2].pPenId),C=iCH(C,m,P,r,d),r=new lC(y,T,Ki,a,C,K,hy),q+=3;else{if(C.indexOf("<")>-1){A=hy;P=Jy;d=y;h=T;var B=m,v=Ki,O=K;const zf=[];var x=g.Fc(`<html>${C}</html>`);if(!x.getElementsByTagName("parsererror").length&&x.firstChild?.childNodes.length)for(const MR of x.firstChild.childNodes){x=MR.textContent?.replace(/\n/g,
"")??"";if(MR.nodeType===3&&(!x||x.match(/^ *$/)!=null))continue;const OD={};Object.assign(OD,A||P);switch(MR?.tagName){case "b":OD.bold=!0;break;case "i":OD.italic=!0;break;case "u":OD.underline=!0}zf.push(new lC(d+B,h-B,v,N.id,x,O,OD))}A=zf}A.length||(A=[new lC(y+m,T-m,Ki,N.id,C,K,hy||Jy)])}if(A.length)for(const zf of A)Z.push(zf),N.V.push(zf);else r&&(Z.push(r),N.V.push(r))}K=!0}}k=Q}else k=[];return k}};var $QT=class extends g.JK{constructor(Z,k,N){super(Z);this.videoData=k;this.audioTrack=N;this.N=k.b$}Y(Z,k,N){ZCh(this.videoData.videoId,Z.vssId,N.Hl)}L(Z){if(this.audioTrack)for(const k of this.audioTrack.captionTracks)g.J1(this.V,k);Z.Yd()}};var cRe=class extends Eu{constructor(Z,k,N,a,T,K,y,Q,q,r){super(Z,k,N,a,T,K,y,Q,q,r);this.type=1}MX(Z){const k=this.U.V;super.MX(Z);let N,a;for(Z=Z.length;Z<k.length;Z++){const T=k[Z];let K;a&&T.V===N?K=a:(K={},Object.assign(K,T.V),Object.assign(K,xQh),N=T.V,a=K);dm_(this,T,K)}}},xQh={RY:!0};var ezh=class extends vlH{constructor(Z,k){super();this.trackData=Z;this.G=k;this.version=this.L=this.D=this.byteOffset=0;this.U=[];this.V=new DataView(this.trackData)}Y(Z,k,N,a,T){if(N<a){const K="_"+f2++;N=N/1E3-this.G;a=a/1E3-this.G;Z=new BA(N,a-N,5,K,{textAlign:0,yp:0,Hi:k*2.5,Mu:Z*5.33});T=new lC(N,a-N,5,K,T);this.U.push(Z);this.U.push(T)}}},GJF=class extends Y0{constructor(Z,k){super();this.U=Z;this.Y=k;this.track=this.Y.languageName==="CC3"?4:0;this.V=new l1a;this.V.U=1<<this.track}D(Z){Z=
new ezh(Z,this.U);if(o4r(Z)){for(;Z.byteOffset<Z.V.byteLength;)for(Z.version===0?Z.D=x0(Z)*(1E3/45):Z.version===1&&(Z.D=x0(Z)*4294967296+x0(Z)),Z.L=$0(Z);Z.L>0;Z.L--){var k=$0(Z);const N=$0(Z),a=$0(Z);k&4&&(k&3)===this.track&&(this.track===0||this.track===1)&&(k=this.V,k.V.push({time:Z.D,type:this.track,Zi:N,Cb:a,order:k.V.length}))}tan(this.V,Z);return Z.U}return[]}reset(){this.V.clear()}};var Hkn=class extends Eu{constructor(Z,k,N,a,T,K,y,Q,q,r){super(Z,k,N,a,T,K,y,Q,q,r);this.type=2;this.dA=[];this.zt=this.O=this.tq=0;this.FS=NaN;this.iq=0;this.ov=null;this.bq=new g.Uc(this.hq,433,this);this.L&&(r.createClientVe(this.L,this,167342),this.K(this.L,"click",()=>{r.logClick(this.L)}),Z=new g.tU(this.element,!0),g.u(this,Z),Z.subscribe("hoverstart",()=>{r.logVisibility(this.L,!0)},this));
g.jX(this.element,"ytp-caption-window-rollup");g.u(this,this.bq);g.ij(this.element,"overflow","hidden")}hp(){g.b6(this.bq)}hq(){this.element.removeEventListener("transitionend",this.hq,!1);g.Wp(this.element,"ytp-rollup-mode");this.C(this.ov,!0)}HA(){return this.Y?this.zt:this.O}jY(){return this.Y?this.O:this.zt}C(Z,k){this.ov=Z;if(this.U.params.Hj){var N=0;for(let a=0;a<this.G.length&&N<Z.length;a++)this.G[a]===Z[N]&&N++;N>0&&N<Z.length&&(Z=this.G.concat(Z.slice(N)));this.iq=this.zt;this.O=this.zt=
0;super.C(Z);bCF(this,k)}super.C(Z)}};var S3D=class{constructor(Z,k,N,a){this.S=Z;this.D=k;this.logger=N;this.Rn=a;this.jI=[];this.GX=[];this.V=null;this.nF={Cbp:()=>this.V,
pN:()=>this.jI};
Z=g.Q5(this.S.X().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=Z>0?Z:10}unload(){this.V!=null&&(this.S.removeEventListener("sabrCaptionsDataLoaded",this.V),this.V=null);this.jI=[];this.S.publish("sabrCaptionsBufferedRangesUpdated",this.jI)}pY(Z){return{formatId:g.ot(Z.info.l3.info,this.Rn),Cp:Z.info.Cp+(this.Rn?0:1),startTimeMs:Z.info.Y*1E3,durationMs:Z.info.C*1E3}}};var ekK=class extends g.JK{constructor(Z,k){super(k);this.U=Z;this.S=k;this.logger=new g.bI("caps");this.C=this.Vz=null;this.zt=new S3D(this.S,this,this.logger,this.U.Rn)}Y(Z,k,N){this.D();k=Z.getId();k=k!=null&&k in this.U.V?this.U.V[k]:null;k||(k=Z.languageCode,k=this.U.isManifestless?n4K(this,k,"386"):n4K(this,k));k&&(this.C=Z,this.Vz=k,Rzh(this.zt,N),this.S.publish("sabrCaptionsTrackChanged",g.ot(k.info,this.U.Rn)))}L(Z){var k=this.U.isManifestless?IqH(this,"386"):IqH(this);for(const N of k)g.J1(this.V,
N);Z.Yd()}D(){this.C&&(this.C=this.Vz=null,this.zt.unload(),this.S.publish("sabrCaptionsTrackChanged",null))}G(){return""}};var jqB="WEBVTT".split("").map(Z=>Z.charCodeAt(0)),NpH=class extends Y0{constructor(){super()}D(Z,k){Z instanceof ArrayBuffer&&(Z=g.Lv(new Uint8Array(Z)));
const N=[];Z=Z.split(olh);for(let d=1;d<Z.length;d++){var a=Z[d],T=k;if(a!==""&&!JRD.test(a)){var K=ZI.exec(a);if(K&&K.length>=4){var y=GE(K[1]),Q=GE(K[2])-y;y+=T;var q=(K=K[3])?K.split(" "):[];K={};var r=null;var C="";var m=null,A="";for(const h of q){q=h.split(":");if(q.length!==2)continue;var P=q[1];switch(q[0]){case "line":q=P.split(",");q[0].endsWith("%")&&(r=q[0],K.Mu=Number.parseInt(r,10),q.length===2&&(C=q[1].trim()));break;case "position":q=P.split(",");m=q[0];K.Hi=Number.parseInt(m,10);
q.length===2&&(A=q[1].trim());break;case "align":switch(P){case "start":K.textAlign=0;break;case "middle":K.textAlign=2;break;case "end":K.textAlign=1}}}r||C||(C="end");if(!m)switch(K.textAlign){case 0:K.Hi=0;break;case 1:K.Hi=100;break;case 2:K.Hi=50}if(K.textAlign!=null){r=0;switch(C){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(A){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(K.textAlign){case 0:r+=0;break;case 2:r+=1;break;
case 1:r+=2}}C=r<0||r>8?7:r;K.yp=C}a=a.substring(ZI.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");A=K;K=a;a={};if(K.indexOf("<")<0&&K.indexOf("&")<0)T=WbJ(y,Q,5,A),Q=new lC(y,Q,5,T.id,K,!1,g.ze(a)?void 0:a),N.push(T),N.push(Q),T.V.push(Q);else for(C=K.split(zki),C.length===1?(K=5,A=WbJ(y,Q,K,A)):(r=K=6,A=Object.assign({UN:32},A),A=new BA(y,Q,r,"_"+f2++,A)),N.push(A),r=y,m=0;m<C.length;m++)if(q=C[m],m%2===0){P=g.Fc(`<html>${q}</html>`);let h;P.getElementsByTagName("parsererror").length?(h=P.createElement("span"),
h.appendChild(P.createTextNode(q))):h=P.firstChild;Yec(this,r,Q-(r-y),K,A,m>0,h,a,N)}else r=GE(q)+T}ZI.lastIndex=0}}return N}},JRD=/^NOTE/,olh=/(?:\r\n|\r|\n){2,}/,ZI=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),zki=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var UQF=class extends g.jR{constructor(Z,k){super();this.S=Z;this.kW=k;this.V=null;this.uq=this.S.gG();this.logger=new g.bI("caps")}clear(){this.V&&this.V.dispose();this.V=null}reset(){this.V&&this.V.reset()}YW(){super.YW();this.clear()}};var S3={windowColor:"#080808",windowOpacity:0,textAlign:2,yp:7,Hi:50,Mu:100,isDefault:!0,p8:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.o1("captions",class extends g.oS{constructor(Z){super(Z);this.S=Z;this.FS=[];this.zt={};this.tq={};this.j=!1;this.D="NONE";this.V=this.N=this.Vz=this.Rq=this.s6=null;this.O6={Yd:()=>{this.Yd()},
Hl:(a,T,K,y,Q=0)=>{const q=Number(this.videoData.X().Yl().V.Aq(g.DEf)??0);Q>0&&q>0&&this.videoData.lengthSeconds>0&&Q/this.videoData.lengthSeconds>q?this.S.U6("tts",{dropcap:Q}):this.Hl(a,T,K,y)}};
this.U=null;this.kW=this.S.X();this.videoData=this.S.getVideoData();this.Tt=this.S.fF();this.L={p8:{}};this.G={p8:{}};this.videoData.jY()?this.D="OFFLINE":g.xlU(this.videoData,this.S)?this.D="HLS":Mah(this.videoData,this.S)?this.D="SABR_LIVE":g.GwN(this.videoData,this.S)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.HA&&(this.D="TTS");this.MX=this.kW.controlsType==="3";this.Kp=new UQF(this.S,this.kW);this.xW=new g.tt(this);this.C=new g.E({J:"div",Z:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});this.O={top:0,right:0,bottom:0,left:0,width:1,height:1};let k=null;const N=g.xN("yt-html5-player-modules::subtitlesModuleData");N&&(k=new g.tw(N));this.storage=k;this.hq=!!Z.TM()?.dA();this.Y=KQa(this);this.dA=!this.Y&&this.MX&&this.hq&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.u(this,this.Kp);this.Y?this.Sm=this.vD=null:(this.vD=new g.o3(this.xl,void 0,this),g.u(this,this.vD),this.Sm=new g.Uc(this.hp,2E3,this),g.u(this,this.Sm));g.u(this,this.xW);g.$n(this.player,
this.C.element,4);g.u(this,this.C);this.Y||this.xW.K(Z,"resize",this.qX);(this.pF=g.ml(this.kW)&&!g.z4()&&!this.S.isFullscreen()&&!this.Y&&!this.dA)&&this.xW.K(Z,"resize",this.HA);this.xW.K(Z,"onPlaybackAudioChange",this.r5);this.xW.K(Z,g.te("captions"),a=>{this.onCueRangeEnter(a)});
this.xW.K(Z,g.he("captions"),a=>{this.onCueRangeExit(a)});
e3(this,dG()||{});g.dv(this.player,"onCaptionsModuleAvailable");this.D==="HLS"&&this.Y&&(Z=this.S.TM().lq(),this.hq&&this.xW.K(Z.textTracks,"addtrack",this.jY))}YW(){if(this.Y||this.dA){const Z=this.S.TM();Z&&!Z.jm()&&Z.j()}else oM(this,!1);super.YW()}FG(){return this.kW.B("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"}a8(){if(this.MX)return this.Y||this.dA;if(this.D==="HLS")return this.Y;var Z=this.getAudioTrack();if(this.FG()){if(!Z.captionTracks.length)return!1;
if(!this.V)return!0}Z=cA(Z,g.fQ(this.kW));return Z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:Z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?zE(this):Jp(this)||zE(this)?!0:q3B(this)}load(){super.load();this.N=this.getAudioTrack();if(this.V)this.U&&(this.Kp.clear(),this.Y?rRc(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.Y(this.U,"json3",this.O6),this.D!=="HLS"&&this.Y||this.dA||Uu(this)||g.dv(this.player,"captionschanged",g.Po(this.U)));else{let Z;this.D==="OFFLINE"?Z=new $QT(this.player,this.videoData,
this.getAudioTrack()):this.D==="SABR_LIVE"?Z=new ekK(this.videoData.V,this.player):this.D==="HLS"?Z=new LQa(this.player):this.D==="LIVE"?Z=new tth(this.videoData.V,this.player):this.D==="INNERTUBE"?Z=new g.zP(this.player,this.videoData,this.getAudioTrack()):Z=new g.Uy(this.player,this.videoData.HA,this.videoData.videoId,g.K8r(this.videoData),this.videoData.GF,this.videoData.eventId);this.V=Z;g.u(this,this.V);this.V.L(this.O6)}}unload(){this.Y&&this.U?rRc(this,!1):(this.Sm&&this.Sm.fH(),this.player.jl("captions"),
this.FS=[],this.V&&this.V.D(),this.Kp.clear(),this.Vz&&this.player.f8(this.Vz),this.qX());super.unload();this.player.bC();g.dv(this.player,"captionschanged",{})}create(){this.a8()&&this.load();var Z;a:{if(this.kW.B("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(Z=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const k of Z)if(k.kind==="asr"&&k.languageCode===
"en"){Z=!0;break a}Z=!1}Z&&this.S.publish("showpromotooltip",this.C.element)}Yd(){var Z=cA(this.player.getAudioTrack(),g.fQ(this.kW));var k=Z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?p2(this,this.j):Z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&zE(this)?bC(this):Jp(this)||this.j||q3B(this)?p2(this,this.j):zE(this)?bC(this):null;if(this.D!=="HLS"&&this.Y||this.dA){const N=g.V9(this.V.V,!0);Z=[];for(let a=0;a<N.length;a++){const T=N[a],K=g.TU("TRACK");K.setAttribute("kind","subtitles");K.setAttribute("label",
g.AQ(T));K.setAttribute("srclang",g.co(T));K.setAttribute("id",T.toString());this.dA||K.setAttribute("src",this.V.G(T,"vtt"));T===k&&K.setAttribute("default","1");Z.push(K)}k=this.S.TM();k.Vz(Z);Z=k.lq();this.hq&&this.xW.K(Z.textTracks,"change",this.iq)}else!this.U&&k&&j3(this,k),g.dv(this.player,"onCaptionsTrackListChanged"),g.Xd(this.player,"onApiChange")}getTrackById(Z){const k=g.V9(this.V.V,!0);for(let N=0;N<k.length;N++)if(k[N].toString()===Z)return k[N];return null}iq(){const Z=this.S.TM().lq().textTracks;
let k=null;for(let N=0;N<Z.length;N++)Z[N].mode==="showing"&&(k=this.getTrackById(Z[N].id));(this.loaded?this.U:null)!==k&&j3(this,k,!0)}jY(){this.V?.L(this.O6)}Y$(){!this.U&&this.Y||this.unload()}Hl(Z,k,N,a){if(Z){IM(this,this.U??void 0);this.V.O()&&(this.FS=[],this.S.jl("captions"),PA(this.vD),this.Kp.reset());a:{var T=this.Kp;a=a||0;N=kJF(T,Z,N||0);Z=[];try{for(const v of N){const O=v.trackData,x=v.Av,e=T.kW.B("safari_live_drm_captions_fix");if(typeof O!=="string"){N=Z;var K=N.concat;if(e&&E4e(O))var y=
a1i(T,O,x);else{var Q=T,q=k,r=O,C=x,m=a;if(!JJD(r))throw Error("Invalid binary caption track data");Q.V||(Q.V=new GJF(m,q));y=Q.V.D(r,C)}var A=K.call(N,y)}else{if(O.substring(0,6)==="WEBVTT")var P=Z.concat(a1i(T,O,x));else{N=Z;var d=N.concat;b:{q=T;Q=k;if(O[0]==="{")try{q.V||(q.V=new w1r(Tpe(Q)));var h=q.V.D(O,x);break b}catch(Jy){g.b(Jy);h=[];break b}const Ki=g.Fc(O);if(!Ki||!Ki.firstChild){const Jy=Error("Invalid caption track data");Jy.params=O;throw Jy;}if(Ki.firstChild.tagName==="timedtext"){if(Number(Ki.firstChild.getAttribute("format"))===
3){r=Ki;q.V||(q.V=new ikB(Tpe(Q)));h=q.V.D(r,x);break b}const Jy=Error("Unsupported subtitles format in web player (Format2)");Jy.params=O;throw Jy;}if(Ki.firstChild.tagName==="transcript"){const Jy=Error("Unsupported subtitles format in web player (Format1)");Jy.params=O;throw Jy;}const yf=Error("Invalid caption track data");yf.params=O;throw yf;}P=d.call(N,h)}A=P}Z=A}var B=Z;break a}catch(v){g.pG(T.logger,187101178,`Captions parsing failed: ${v.message}. `);T.clear();B=[];break a}B=void 0}k=B;k.length>
0&&(B=this.U,this.F8(B,!!B,Uu(this)?"g":this.j?"m":"s"));this.player.f8(k,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");!this.j||this.dA||Uu(this)||g.Qw(this.kW)||g.CQ(this.kW)||g.oJ(this.kW)||this.kW.zt==="shortspage"||this.player.isInline()||(this.Sm.fH(),k=wRJ({yp:0,Hi:5,Mu:5,Hj:2,textAlign:0,b9:0,lang:"en-GB"}),this.Rq=[k],B=["Click "," for settings"],this.s6||(T=new g.JO(g.cm()),g.u(this,T),this.s6=T.element),T=k.end-k.start,(A=g.AQ(this.U))&&this.Rq.push(new lC(k.start,T,0,k.id,A)),this.Rq.push(new lC(k.start,
T,0,k.id,B[0]),new lC(k.start,T,0,k.id,this.s6,!0),new lC(k.start,T,0,k.id,B[1],!0)),this.player.f8(this.Rq),this.Sm.XN());!this.j||this.dA||Uu(this)||(this.kW.B("enable_player_captions_persistence_state_machine")?RM(this,!0):g.fQ(this.kW)?M5(this,!0):n2(this,!0),this.N&&(this.N.Y=this.U),this.player.bC());this.j=!1}}onCueRangeEnter(Z){this.FS.push(Z);PA(this.vD)}onCueRangeExit(Z){g.qF(this.FS,Z);this.V instanceof tth&&this.V.zt&&this.player.h$([Z]);PA(this.vD)}getCaptionWindowContainerId(){return this.C.element.id}hp(){yRD(this,
this.Rq);this.Rq=null}xl(){if(!this.pF||!this.Y){this.vD.stop();g.Uh(this.tq);this.FS.sort(g.Fi);var Z=this.FS;if(this.Vz){const k=g.Ry(Z,function(N){return this.Vz.indexOf(N)===-1},this);
k.length&&(Z=k)}for(const k of Z)k instanceof BA?sac(this,k):ARJ(this,k);for(const [k,N]of Object.entries(this.zt)){const a=k,T=N;this.tq[a]?(T.element.parentNode||(T instanceof Hkn||T instanceof cRe||g.vB(this.zt,(K,y)=>{y!==a&&K.U.params.yp===T.U.params.yp&&K.U.params.Hi===T.U.params.Hi&&K.U.params.Mu===T.U.params.Mu&&(K.dispose(),delete this.zt[y]);return y===a},this),this.C.element.appendChild(T.element)),T.C(this.tq[a])):(T.dispose(),delete this.zt[a])}}}xe(){e3(this,{},!0);
g.dv(this.player,"captionssettingschanged")}f2(){var Z=S3.p8;Z={background:Z.background,backgroundOpacity:Z.backgroundOpacity,charEdgeStyle:Z.charEdgeStyle,color:Z.color,fontFamily:Z.fontFamily,fontSizeIncrement:Z.fontSizeIncrement,fontStyle:Z.bold&&Z.italic?3:Z.bold?1:Z.italic?2:0,textOpacity:Z.textOpacity,windowColor:S3.windowColor,windowOpacity:S3.windowOpacity};const k=dG()||{};k.background!=null&&(Z.background=k.background);k.backgroundOverride!=null&&(Z.backgroundOverride=k.backgroundOverride);
k.backgroundOpacity!=null&&(Z.backgroundOpacity=k.backgroundOpacity);k.backgroundOpacityOverride!=null&&(Z.backgroundOpacityOverride=k.backgroundOpacityOverride);k.charEdgeStyle!=null&&(Z.charEdgeStyle=k.charEdgeStyle);k.charEdgeStyleOverride!=null&&(Z.charEdgeStyleOverride=k.charEdgeStyleOverride);k.color!=null&&(Z.color=k.color);k.colorOverride!=null&&(Z.colorOverride=k.colorOverride);k.fontFamily!=null&&(Z.fontFamily=k.fontFamily);k.fontFamilyOverride!=null&&(Z.fontFamilyOverride=k.fontFamilyOverride);
k.fontSizeIncrement!=null&&(Z.fontSizeIncrement=k.fontSizeIncrement);k.fontSizeIncrementOverride!=null&&(Z.fontSizeIncrementOverride=k.fontSizeIncrementOverride);k.fontStyle!=null&&(Z.fontStyle=k.fontStyle);k.fontStyleOverride!=null&&(Z.fontStyleOverride=k.fontStyleOverride);k.textOpacity!=null&&(Z.textOpacity=k.textOpacity);k.textOpacityOverride!=null&&(Z.textOpacityOverride=k.textOpacityOverride);k.windowColor!=null&&(Z.windowColor=k.windowColor);k.windowColorOverride!=null&&(Z.windowColorOverride=
k.windowColorOverride);k.windowOpacity!=null&&(Z.windowOpacity=k.windowOpacity);k.windowOpacityOverride!=null&&(Z.windowOpacityOverride=k.windowOpacityOverride);return Z}U8(Z,k){const N={};Object.assign(N,dG());Object.assign(N,Z);e3(this,N,k);g.dv(this.player,"captionssettingschanged")}qX(){!this.Y&&this.loaded&&(g.BB(this.zt,function(Z,k){Z.dispose();delete this.zt[k]},this),this.xl())}kd(Z,k){switch(Z){case "fontSize":if(isNaN(k))break;
Z=g.u0(k,-2,4);this.U8({fontSizeIncrement:Z});return Z;case "reload":k&&!this.Y&&j3(this,this.U,!0);break;case "stickyLoading":k!==void 0&&this.kW.C&&(this.kW.B("enable_player_captions_persistence_state_machine")?RM(this,!(!k||!k.userInitiated)):g.fQ(this.kW)?M5(this,!!k):n2(this,!!k));break;case "track":return dQB(this,k);case "tracklist":return this.V?g.ni(g.V9(this.V.V,!(!k||!k.includeAsr)),N=>g.Po(N)):[];
case "translationLanguages":return this.V?this.V.N.map(N=>Object.assign({},N)):[];
case "sampleSubtitles":this.Y||k===void 0||oM(this,!!k);break;case "sampleSubtitlesCustomized":this.Y||oM(this,!!k,k);break;case "recommendedTranslationLanguages":return g.qr();case "defaultTranslationSourceTrackIndices":return this.V?this.V.xW:[]}}getOptions(){const Z="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.kW.C&&Z.push("stickyLoading");return Z}QP(){let Z=this.U;if(this.S.S7("captions")){if(this.kW.B("html5_modify_caption_vss_logging"))return(Z=this.videoData.dZ??
null)?{cc:g.QEr(Z)}:{};if(Z){let k=Z.vssId;Z.translationLanguage&&k&&(k=`t${k}.${g.co(Z)}`);return{cc:k}}}return{}}OV(Z){this.isSubtitlesOn()?(this.kW.B("enable_player_captions_persistence_state_machine")&&Z?RM(this,!1):g.fQ(this.kW)?M5(this,!1):n2(this,!1),IM(this),j3(this,null,!0)):this.bj(Z)}bj(Z){const k=Uu(this)||!this.U?p2(this,!0):this.U;k&&this.AQ(k.vssId,"m");this.isSubtitlesOn()||j3(this,k,this.kW.B("enable_player_captions_persistence_state_machine")?Z:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.U&&!Uu(this)}r5(){const Z=Uu(this);zE(this,Z)?j3(this,this.getAudioTrack().V,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.FG()&&(this.j=!1,this.U=null,this.V&&(this.V.dispose(),this.V=null)),this.a8()&&(Z?j3(this,p2(this,!1),!1):this.load()))}Uz(Z){Z&&(this.O={top:Z.top,right:Z.right,bottom:Z.bottom,left:Z.left,width:1-Z.left-Z.right,height:1-Z.top-Z.bottom},this.C.element.style.top=`${this.O.top*100}%`,this.C.element.style.left=`${this.O.left*100}%`,this.C.element.style.width=
`${this.O.width*100}%`,this.C.element.style.height=`${this.O.height*100}%`,this.C.element.style.position="absolute",Z=Pkn(this))&&(this.C.element.style.width=`${Z.width}px`,this.C.element.style.height=`${Z.height}px`)}onVideoDataChange(Z,k){Z==="newdata"&&(this.videoData=k,this.loaded&&this.unload(),this.j=!1,this.U=null,this.V&&(this.V.dispose(),this.V=null,g.dv(this.player,"captionschanged",{})),this.a8()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}HA(){const Z=this.S.TM();
Z&&!Z.jm()&&Z.j();this.S.isFullscreen()?(this.Y=this.MX=!0,this.loaded&&this.Yd()):(this.MX=this.kW.controlsType==="3",this.Y=KQa(this));j3(this,this.U)}Qz(){const Z=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;Z&&g.A7(this.player,"innertubeCommand",Z)}F8(Z,k,N){const a=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let T="";Z&&(T=Z.vssId,T=T.replace(a,""));let K="";Z&&Z.getId()&&(K=Z.getId()||"");Z&&Z.getXtags()&&(Z=Z.getXtags(),Z=Z.replace(a,""),K=K.concat(`;${Z}`));
this.D==="HLS"&&(K="");this.S.F8(k?T:"",k?K:"",N)}AQ(Z,k){Z=(Z||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");Z.length>0&&this.S.AQ(Z,k)}});})(_yt_player);
