#/* Copyright (C) 2019 Radhamadhab Dalai - All Rights Reserved
# * You may use, distribute and modify this code under the
# * terms of the license, which unfortunately won't be
# * written for another century.
# *
# * You should have received a copy of the license with
# * this file. If not, please write to: dalai115@gmail.com.
# */


#This file supports the following commands:
#make build
#make clean
#make unbuild

include ../../make/rtl.mk
