(function(g){var window=this;'use strict';var Bz=function(f){f.publish("cardstatechange",f.O4()&&f.fV()?1:0)},nG=function(f,e){var B=g.Yg(e);
const n=B?e:arguments;for(B=B?0:1;B<n.length;B++){if(f==null)return;f=f[n[B]]}return f},QxI=function(f){const e=g.Tt(f);
f=g.WN(f);return new g.oY(e.x,e.y,f.width,f.height)},T22=function(f,e,B){let n;
return n=g.Ds(f,e,function(){g.Jl(n);B.apply(f,arguments)},{})},d4=function(f){f=g.od(f);
delete r4[f];g.TL(r4)&&LG&&LG.stop()},JuH=function(){LG||(LG=new g.T6(function(){DTe()},20));
const f=LG;f.isActive()||f.start()},DTe=function(){var f=g.u0();
g.OM(r4,function(e){MBM(e,f)});
g.TL(r4)||JuH()},tC=function(f,e,B,n){g.eh.call(this);
if(!Array.isArray(f)||!Array.isArray(e))throw Error("Start and end parameters must be arrays");if(f.length!=e.length)throw Error("Start and end points must be the same length");this.G=f;this.X=e;this.duration=B;this.W=n;this.coords=[];this.progress=this.U=0;this.V=null},MBM=function(f,e){e<f.startTime&&(f.endTime=e+f.endTime-f.startTime,f.startTime=e);
f.progress=(e-f.startTime)/(f.endTime-f.startTime);f.progress>1&&(f.progress=1);f.U=1E3/(e-f.V);f.V=e;GLF(f,f.progress);f.progress==1?(f.C=0,d4(f),f.onFinish(),f.SG()):f.isPlaying()&&f.bD()},GLF=function(f,e){typeof f.W==="function"&&(e=f.W(e));
f.coords=Array(f.G.length);for(let B=0;B<f.G.length;B++)f.coords[B]=(f.X[B]-f.G[B])*e+f.G[B]},xT2=function(f,e){g.fI.call(this,f);
this.coords=e.coords;this.x=e.coords[0];this.y=e.coords[1];this.z=e.coords[2];this.duration=e.duration;this.progress=e.progress;this.fps=e.U;this.state=e.C},Hz=function(f,e,B,n,r){tC.call(this,e,B,n,r);
this.element=f},kd=function(f,e,B,n,r){if(e.length!=2||B.length!=2)throw Error("Start and end points must be 2D");
Hz.call(this,f,e,B,n,r)},WeV=function(f){return Math.pow(f,3)},sx2=function(f){return 3*f*f-2*f*f*f},CG=function(f){return f.baseUrl||null},w4=function(f,e){return g.GO(g.xg(f,e),B=>!!B)},XBM=function(f,e,B){function n(AY){var Dl=AY.hovercardButton;
if(!Dl)return null;Dl=Dl.subscribeButtonRenderer;if(!Dl)return null;const W5=L(Dl.unsubscribedButtonText),lP=L(Dl.subscribedButtonText);let JY,Y2;Dl.subscribed?(JY=L(Dl.subscriberCountWithUnsubscribeText),Y2=L(Dl.subscriberCountText)):(JY=L(Dl.subscriberCountText),Y2=L(Dl.subscriberCountWithSubscribeText));let Dm=null;return AY.signinEndpoint&&((Dm=nG(AY,"signinEndpoint","webNavigationEndpointData","url"))||(Dm=g.u(Dl.signInEndpoint?.commandMetadata,g.L1)?.url),!Dm)?null:W5&&(lP||Dm)?{subscribed:Dl.subscribed,
subscribeText:W5,subscribeCount:JY,unsubscribeText:lP,unsubscribeCount:Y2,enabled:Dl.enabled,signinUrl:Dm,classic:AY.useClassicSubscribeButton}:null}
function r(AY){if(AY){var Dl=[],W5=AY.videoId;W5&&Dl.push("v="+W5);(W5=AY.playlistId)&&Dl.push("list="+W5);(AY=AY.startTimeSeconds)&&Dl.push("t="+AY);return"/watch?"+Dl.join("&")}}
function L(AY){if(!AY)return null;const Dl=AY.simpleText;return Dl?Dl:AY.runs?g.xg(AY.runs,W5=>W5.text).join(""):null}
e=e.endscreenElementRenderer;if(!e)return null;const d=e.style,t=e.endpoint||{};let H=null;var k=null,C=!1;let w=null,v=null,b=null,K=null;var Y=!1;let l=null,m=null;var F=null;let N=null,E=null,Lw=null;if(d==="VIDEO")g.u(t,g.jL)?H=g.u(t,g.jL).url:(Lw=g.u(t,g.iK),H=r(Lw)),k=!1,w=f,e.thumbnailOverlays?(C=e.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,v=L(C.text),C=C.style==="LIVE"):v=L(e.videoDuration);else if(d==="PLAYLIST")g.u(t,g.jL)?H=g.u(t,g.jL).url:(Lw=g.u(t,g.iK),H=r(Lw)),k=!1,w=
f,b=L(e.playlistLength);else if(d==="CHANNEL"){if(Y=nG(t,"browseEndpoint","browseId"))K=Y,H=`/channel/${K}`;k=!1;w="new";(Y=!!e.isSubscribe)?l=n(e):m=L(e.subscribersText)}else d==="WEBSITE"?((F=nG(t,"urlEndpoint","url"))&&(H=F),k=!0,w="new",F=e.icon.thumbnails[0].url):d==="CREATOR_MERCHANDISE"&&(e.productPrice&&(N=L(e.productPrice)),e.additionalFeesText&&(E=L(e.additionalFeesText)),(k=nG(t,"urlEndpoint","url"))&&(H=k),k=!0,w="new");f=nG(e,"title","accessibility","accessibilityData","label");const d6=
e.endpoint?e.endpoint.clickTrackingParams:null;let TO="";if(e.metadata){const AY=L(e.metadata);AY&&(TO=AY)}return{id:`element-${B}`,type:d,title:L(e.title),metadata:TO,callToAction:L(e.callToAction),MR:e.image,iconUrl:F,left:Number(e.left),width:Number(e.width),top:Number(e.top),aspectRatio:Number(e.aspectRatio),startMs:Math.floor(Number(e.startMs)),endMs:Math.floor(Number(e.endMs)),videoDuration:v,IG:C,playlistLength:b,channelId:K,subscribeButton:l,subscribersText:m,isSubscribe:Y,targetUrl:H||null,
bN:k,sessionData:d6?{itct:d6}:null,JS:w,WV:f?f:null,isPlaceholder:e.isPlaceholder,impressionUrls:w4(e.impressionUrls||[],CG),lU:w4(e.hovercardShowUrls||[],CG),clickUrls:w4(t.loggingUrls||[],CG),visualElement:g.kv(e.trackingParams),productPrice:N,additionalFeesText:E,watchEndpoint:Lw||null}},vz=function(f,e){const B={startMs:Math.floor(Number(f.startMs)),
impressionUrls:w4(f.impressionUrls||[],CG),elements:w4(f.elements||[],(n,r)=>XBM(e,n,r))};
f.trackingParams&&(B.visualElement=g.kv(f.trackingParams));return B},bV=function(f){return f.player.S().playerStyle==="creator-endscreen-editor"},yuu=function(f){return f.player.getVideoData().AF?"current":f.N?"new":"current"},ZN=function(f,e,B=!0){f.player.sK("creatorendscreen");
f.J&&(f.J.dispose(),f.J=null,f.W.dispose(),f.W=null);for(var n of Object.values(f.G))n.dispose();f.G={};f.U={};f.K.length>0&&(f.K.forEach(r=>{r.dispose()}),f.K.length=0);
f.C&&(g.$i(f.C,"ytp-ce-element-show"),f.C.setAttribute("aria-hidden","true"));f.X=0;if((f.endscreen=e)&&e.elements){B&&PHg(f);B=[];n=new g.VD(e.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});B.push(n);f.player.S().G||(f.J=new g.y({L:"div",B:"ytp-ce-shadow"}),g.qX(f.player,f.J.element,4),f.W=new g.Ob(f.J,200));for(n=0;n<e.elements.length;++n){const r=e.elements[n],L=IVM(f,r);if(!L){g.Yv(new g.Dj("buildEndscreenElement null",r));continue}f.G[r.id]=L;f.U[r.id]=r;g.qX(f.player,
L.element,4);const d=new g.VD(r.startMs,r.endMs,{id:"ytp-ce-element-"+r.id,namespace:"creatorendscreen"});B.push(d);$TL(f,L,r)}f.player.AI(B);f.Sf()}},iFB=function(f){var e=f.player.getVideoData(),B=e.videoId;
f.V&&f.V.abort();B={method:"POST",onFinish:r=>{var L=f.V=null;r.status===200&&(r=r.responseText,r.substring(0,3)===")]}"&&(r=r.substring(3),L=JSON.parse(r),L=vz(L,yuu(f))));ZN(f,L)},
urlParams:{v:B},withCredentials:!0};f.N&&(B.urlParams.ptype="embedded");const n=e.Cv;n&&(B.postParams={ad_tracking:n});if(e=g.Q7g(e))if(e=g.hs(e),e=g.FL(e))f.V=g.QY(e,B)},PHg=function(f){const e=g.v6(),B=g.be();
B&&e&&f.endscreen.visualElement&&g.LN(g.ER)(void 0,B,e,f.endscreen.visualElement)},IVM=function(f,e){var B=null;
switch(e.type){case "VIDEO":f={L:"div",y9:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":e.WV||"","aria-hidden":"true"},j:[{L:"div",B:"ytp-ce-element-shadow"},{L:"div",B:"ytp-ce-covering-image",O:Rk(e)},{L:"div",B:"ytp-ce-covering-shadow-top"},{L:"a",B:"ytp-ce-covering-overlay",O:{href:KG(f,e.targetUrl),tabindex:"-1"},j:[{L:"div",y9:["ytp-ce-video-title","ytp-webkit-ellipsis"],O:{dir:g.k4(e.title||"")},Ga:e.title},{L:"div",B:e.IG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Ga:e.videoDuration||void 0}]}]};B=new g.y(f);break;case "PLAYLIST":f={L:"div",y9:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":e.WV||"","aria-hidden":"true"},j:[{L:"div",B:"ytp-ce-element-shadow"},{L:"div",B:"ytp-ce-covering-image",O:Rk(e)},{L:"div",B:"ytp-ce-covering-shadow-top"},{L:"a",B:"ytp-ce-covering-overlay",O:{href:KG(f,e.targetUrl),tabindex:"-1"},j:[{L:"div",y9:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],O:{dir:g.k4(e.title||"")},Ga:e.title},{L:"div",B:"ytp-ce-playlist-count",
j:[{L:"div",B:"ytp-ce-playlist-icon"},{L:"div",B:"ytp-ce-playlist-count-text",Ga:e.playlistLength||void 0}]}]}]};B=new g.y(f);break;case "CHANNEL":B={L:"div",y9:["ytp-ce-element","ytp-ce-channel",e.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":e.WV||"","aria-hidden":"true"},j:[{L:"div",B:"ytp-ce-element-shadow"},{L:"div",B:"ytp-ce-expanding-overlay",j:[{L:"div",B:"ytp-ce-expanding-overlay-hider"},{L:"div",B:"ytp-ce-expanding-overlay-background"},{L:"div",B:"ytp-ce-expanding-overlay-content",
j:[{L:"div",B:"ytp-ce-expanding-overlay-body",j:[{L:"div",B:"ytp-ce-expanding-overlay-body-padding",j:[{L:"a",y9:["ytp-ce-channel-title","ytp-ce-link"],O:{href:KG(f,e.targetUrl),target:"_blank",tabindex:"-1",dir:g.k4(e.title||"")},Ga:e.title},e.subscribeButton?{L:"div",B:"ytp-ce-subscribe-container",j:[{L:"div",B:"ytp-ce-channel-subscribe"}]}:"",e.subscribersText?{L:"div",B:"ytp-ce-channel-subscribers-text",Ga:e.subscribersText}:"",e.metadata?{L:"div",y9:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Ga:e.metadata}:""]}]}]}]},{L:"div",B:"ytp-ce-expanding-image",O:Rk(e)}]};B=new g.y(B);const r=g.Ge(document,"div","ytp-ce-channel-subscribe",B.element)[0];if(e.subscribeButton&&e.channelId){g.PW(r,"ytp-ce-subscribe-button");let L;if(f.player.S().G){var n=null;L=e.sessionData.itct}else n="endscreen",L=null;n=new g.ez(e.subscribeButton.subscribeText,e.subscribeButton.subscribeCount,e.subscribeButton.unsubscribeText,e.subscribeButton.unsubscribeCount,!!e.subscribeButton.enabled,!!e.subscribeButton.classic,
e.channelId,!!e.subscribeButton.subscribed,n,L,f.player,!1);r.appendChild(n.element);f.K.push(n)}break;case "WEBSITE":f={L:"div",y9:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":e.WV||"","aria-hidden":"true"},j:[{L:"div",B:"ytp-ce-element-shadow"},{L:"div",B:"ytp-ce-expanding-overlay",j:[{L:"div",B:"ytp-ce-expanding-overlay-hider"},{L:"div",B:"ytp-ce-expanding-overlay-background"},{L:"div",B:"ytp-ce-expanding-overlay-content",j:[{L:"div",B:"ytp-ce-expanding-overlay-body",j:[{L:"div",
B:"ytp-ce-expanding-overlay-body-padding",j:[{L:"div",B:"ytp-ce-website-title",O:{dir:g.k4(e.title||"")},Ga:e.title},{L:"div",B:"ytp-ce-website-metadata",Ga:e.metadata},{L:"a",y9:["ytp-ce-website-goto","ytp-ce-link"],O:{href:KG(f,e.targetUrl),target:"_blank",tabindex:"-1"},Ga:e.callToAction}]}]}]}]},{L:"div",B:"ytp-ce-expanding-image",O:Rk(e)},{L:"div",B:"ytp-ce-expanding-icon",O:fwg(e.iconUrl)}]};B=new g.y(f);break;case "CREATOR_MERCHANDISE":B="",e.productPrice&&(B={L:"div",B:"ytp-ce-merchandise-price-container",
j:[{L:"div",B:"ytp-ce-merchandise-price",Ga:e.productPrice}]},e.additionalFeesText&&B.j.push({L:"div",B:"ytp-ce-merchandise-additional-fees",Ga:e.additionalFeesText})),f={L:"div",y9:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":e.WV||"","aria-hidden":"true"},j:[{L:"div",B:"ytp-ce-element-shadow"},{L:"div",B:"ytp-ce-expanding-overlay",j:[{L:"div",B:"ytp-ce-expanding-overlay-hider"},{L:"div",B:"ytp-ce-expanding-overlay-background"},{L:"div",B:"ytp-ce-expanding-overlay-content",
j:[{L:"div",B:"ytp-ce-expanding-overlay-body",j:[{L:"div",B:"ytp-ce-expanding-overlay-body-padding",j:[{L:"div",B:"ytp-ce-merchandise-title",O:{dir:g.k4(e.title||"")},Ga:e.title},B,{L:"div",B:"ytp-ce-merchandise-metadata",Ga:e.metadata},{L:"a",y9:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:KG(f,e.targetUrl),target:"_blank",tabindex:"-1"},Ga:e.callToAction}]}]}]}]},{L:"div",B:"ytp-ce-expanding-image",O:Rk(e)},{L:"div",B:"ytp-ce-merchandise-invideo-cta-container",j:[{L:"div",B:"ytp-ce-merchandise-invideo-cta",
Ga:e.callToAction||void 0}]}]},B=new g.y(f)}e.isPlaceholder&&g.PW(B.element,"ytp-ce-placeholder");return B},$TL=function(f,e,B){function n(){d(1)}
function r(){d(-1)}
e.listen("mouseenter",()=>{qN(f,e,B)});
e.listen("mouseleave",()=>{z4(f,e,B)});
f.player.S().G||e.listen("click",()=>{g.PW(e.element,"ytp-ce-element-hover")});
e.listen("click",t=>{eue(f,B,t)});
e.listen("keypress",t=>{eue(f,B,t)});
e.listen("focus",()=>{qN(f,e,B)});
e.listen("blur",()=>{z4(f,e,B)});
e.listen("touchstart",()=>{qN(f,e,B)});
var L=g.x2("ytp-ce-expanding-overlay-hider",e.element);L&&e.D(L,"touchstart",t=>{t.stopPropagation();g.$i(e.element,"ytp-ce-element-hover");g.$i(e.element,"ytp-ce-force-expand")});
e.listen("keydown",t=>{f.Ed=t.keyCode===9&&!t.shiftKey});
const d=t=>{f.X+=t;f.X>0?(g.PW(e.element,"ytp-ce-force-expand"),ak(f,B.id,!0)):(g.$i(e.element,"ytp-ce-force-expand"),g.$i(e.element,"ytp-ce-element-hover"),ak(f,B.id,!1))};
L=t=>{t&&(e.listen("blur",()=>{t.style.display!="none"&&f.Ed&&t.focus()}),e.D(t,"focus",n),e.D(t,"blur",r))};
L(g.x2("ytp-sb-subscribe",e.element));L(g.x2("ytp-sb-unsubscribe",e.element));e.listen("focus",n);e.listen("blur",r)},pG=function(f,e,B){function n(){L||(r++,r===e.length&&(d.stop(),B&&B()))}
if(!e||e.length===0||bV(f))B&&B();else{e=B0g(f,e);var r=0,L=!1,d=new g.T6(()=>{L=!0;B&&B()},1E3,f);
d.start();for(f=0;f<e.length;f++)g.gq(e[f],n)}},Rk=function(f){let e;
f.MR&&(e=f.MR.thumbnails);return fwg(e?e[e.length-1].url:null)},KG=function(f,e){f=f.player.S();
if(e){if(e.startsWith("//"))return f.protocol+":"+e;if(e.startsWith("/"))return g.C3(f)+e}else return"";return e},fwg=function(f){return f?{style:"background-image: url("+f+")"}:{}},qN=function(f,e,B){g.yC(e.element,"ytp-ce-element-hover")||(B.type==="VIDEO"||B.type==="PLAYLIST"?g.PW(e.element,"ytp-ce-element-hover"):f.player.S().G?(new g.T6(()=>{g.PW(e.element,"ytp-ce-element-hover")},200)).start():g.PW(e.element,"ytp-ce-element-hover"),pG(f,B.lU),ak(f,B.id,!0))},z4=function(f,e,B){g.$i(e.element,
"ytp-ce-element-hover");
g.$i(e.element,"ytp-ce-force-expand");ak(f,B.id,!1)},eue=function(f,e,B){if(e.targetUrl&&(!B||B.type!=="keypress"||B.keyCode===13)){for(var n=B.target;n&&!g.yC(n,"ytp-ce-element");){g.yC(n,"subscribe-label")&&cz(f,e);
if(g.yC(n,"ytp-ce-channel-subscribe"))return;n=n.parentElement||null}if(!n||g.yC(n,"ytp-ce-element-hover")){B.preventDefault();B.stopPropagation();if(n=f.G[e.id])z4(f,n,e),n.element.blur();if(B.ctrlKey||B.metaKey||e.JS==="new")cz(f,e),f.player.sendVideoStatsEngageEvent(17,void 0),f.player.pauseVideo(),B=g.hs(KG(f,e.targetUrl)),B=g.FL(B),g.I5(B,void 0,e.sessionData);else{const r=g.yQ(f.player.S())||f.player.getVideoData().AF,L=()=>{var d=KG(f,e.targetUrl),t=e.sessionData,H=e.watchEndpoint;const k=
g.vb(d);r&&k&&(k.v||k.list)?f.player.P6(k.v,t,k.list,!1,void 0,H||void 0):g.Wl(d,t)};
cz(f,e,()=>{f.player.sendVideoStatsEngageEvent(17,L)})}}}},ak=function(f,e,B){f.J&&(B?f.W.show():f.W.hide());
for(const n of Object.keys(f.G))n!==e&&g.h(f.G[n].element,"ytp-ce-element-shadow-show",B)},cz=function(f,e,B){pG(f,e.clickUrls,B);
(f=g.be())&&e.bN&&g.yL(f,e.visualElement)},B0g=function(f,e){var B=f.player.getVideoData().clientPlaybackNonce;
f=f.player.getCurrentTime().toFixed(2);B={CPN:B,AD_CPN:B,MT:f};f=[];for(let n=0;n<e.length;n++)f.push(nWe(e[n],B));return f},nWe=function(f,e){return f.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,B=>{let n=unescape(B);
n=n.substring(1,n.length-1);return e[n]?escape(e[n]):B})},rsM=function(f){return typeof f==="string"?f:""},Yd=function(f,e,B){for(const n in e)if(e[n]===f)return f;
return B},AC=function(f){if(!f)return null;
var e=g.hs(rsM(f.value));e=g.FL(e);if(!e)return null;const B=Yd(f.target,LBB,"current");if(B==null)f=null;else{var n=f.show_link_icon;f=new dbe(e,B,n==="true"||n==="false"?n==="true":!0,f.pause_on_navigation!=null?f.pause_on_navigation:!0)}return f},CPM=function(f){if(!f)return null;
const e=Yd(f.type,tUG),B=Yd(f.trigger,HEg);f=f.url;f=Array.isArray(f)&&f.length?f[0]:f;f=AC(f?f:null);return e?new kcG(e,B,f):null},wEI=function(f,e){return g.$g(f.action,e)},jR=function(f,e){f="background-image: url("+f+");";
const B=[];e&&B.push(e);return{L:"div",B:"iv-card-image",O:{style:f},j:B}},ok=function(f){return f.customMessage?O4("div","iv-card-message",f.customMessage):""},Vk=function(f){if(!f.metaInfo||f.metaInfo.length===0)return"";
const e=[];for(const B of f.metaInfo)e.push(O4("li","",B));return{L:"ul",B:"iv-card-meta-info",j:e}},lV=function(f,e,B,n){if(n)for(const r of e)f.C(r,n,B.id,B.sessionData,B.o8.click,5)},O4=function(f,e,B){e?typeof e==="string"?e={"class":e}:Array.isArray(e)&&(e={"class":e.join(" ")}):e={};
e.dir=g.k4(B);return{L:f,O:e,Ga:B}},vWV=function(f){if(!f.customMessage)return"";
const e=["iv-card-action","iv-card-primary-link"],B={};f.HV&&(e.push("iv-card-action-icon"),B.style="background-image: url("+f.HV+");");B.dir=g.k4(f.customMessage);const n=[{L:"span",Ga:f.customMessage}];f.showLinkIcon&&(n.push("\u00a0"),n.push({L:"span",B:"iv-card-link-icon"}));return{L:"div",y9:e,O:B,j:n}},bEV=function(f){var e;
(e=f)&&!(e=f.length>1?f.charAt(0)==="/"&&f.charAt(1)!=="/":f==="/")&&(e=f.replace(/^(https?:)?\/\//,"").split("/",1),e=!e||e.length<1||!e[0]?[]:e[0].toLowerCase().split(".").reverse(),e=e[0]==="com"&&e[1]==="youtube"||e[0]==="be"&&e[1]==="youtu");return e?f.indexOf("/redirect?")===-1:!1},ZEV=function(f,e){return e?e:bEV(f)?"current":"new"},uV=function(f,e,B,n,r,L,d){f.context.C.listen(e,"click",t=>{f.Fl(B,n,r,L||[],d||0,t)});
f.context.C.listen(e,"touchstart",()=>{f.xA=!1});
f.context.C.listen(e,"touchmove",()=>{f.xA=!0})},RuF=function(f){if(g.u(f,g.jL)?.url)return g.u(f,g.jL).url;
if((f=g.u(f,g.iK))&&f.videoId){let e="/watch?v="+f.videoId;f.playlistId&&(e+="&list="+f.playlistId);f.index&&(e+="&index="+f.index);f.startTimeSeconds&&(e+="&t="+f.startTimeSeconds);return e}return null},FJ=function(f,e,B){return{ji:(f.impressionLoggingUrlsV2s||[]).map(n=>n.baseUrl||""),
click:(B.loggingUrls||[]).map(n=>n.baseUrl||""),
close:(e.dismissLoggingUrlsV2s||[]).map(n=>n.baseUrl||""),
zH:(e.impressionLoggingUrlsV2s||[]).map(n=>n.baseUrl||""),
Q0:(e.clickLoggingUrlsV2s||[]).map(n=>n.baseUrl||"")}},hC=function(f,e){if(e.onClickCommand&&g.u(e.onClickCommand,g.vdO)?.targetId==="engagement-panel-error-corrections"){f.A=e;
var B=!0}else B=!1;if(!B||KBI(f,e))if(B=q0L(f,e)){var n={R1:e,Ny:B.element,Mb:!1};if(e.onClickCommand)f.Z.Y("web_infocards_teaser_show_logging_fix")&&(f.G6||awe(f),mH(f,e.id),B=f.findLastIndex(n),g.Rx(f.cards,B,0,n));else{f.isInitialized||zuH(f);mH(f,e.id);const r=f.findLastIndex(n);g.Rx(f.cards,r,0,n);B.di(f.G,r);f.WS()}e.autoOpen?f.addCueRange(e.startMs,0x8000000000000,e.id,()=>{f.J||(f.C=n,U4(f),pEx(f,n),NN(f,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(B=f.context.Z.getCurrentTime()*1E3,B<5E3&&B>e.startMs&&
cs2(f,n),f.addCueRange(e.startMs,e.startMs+1,e.id,()=>{cs2(f,n)}),U4(f))}},g4=function(f){f.J&&(f.qC.hide(),f.Z9.G(),g.$i(f.context.Z.getRootNode(),g.y1.IV_DRAWER_OPEN),f.J=!1,Bz(f.Z),f.U&&f.U.stop(),f.U=new g.T6(()=>{f.Lq&&(f.Lq.focus(),f.Lq=null)},330),f.U.start())},Y0B=function(f,e){e=e.data;
e.autoOpenMs&&f.addCueRange(e.autoOpenMs,0x8000000000000,"",()=>{NN(f,"YOUTUBE_DRAWER_AUTO_OPEN")});
e.autoCloseMs&&f.addCueRange(e.autoCloseMs,0x8000000000000,"",()=>{g4(f)});
const B=e.headerText;g.kC(f.Ch,B);f.W&&(f.Z.Y("player_tooltip_data_title_killswitch")?f.W.setAttribute("title",B):f.W.setAttribute("data-tooltip-title",B));e.eventId&&(f.eventId=e.eventId);f.PS=g.kv(e.trackingParams);f.K=g.kv(e.closeTrackingParams);f.kK=g.kv(e.iconTrackingParams)},SR=function(f,e,B){let n=-1,r=-1;
for(let L=0;L<f.length;L++){if(f[L].height===e||f[L].width===B)return f[L];((f[L].height||0)<e||(f[L].width||0)<B)&&(n<0||(f[n].height||0)<(f[L].height||0)||(f[n].width||0)<(f[L].width||0))?n=L:((f[L].height||0)>=e||(f[L].width||0)>=B)&&(r<0||(f[r].height||0)>(f[L].height||0)||(f[r].width||0)>(f[L].width||0))&&(r=L)}return f[r>=0?r:n]},E4=function(f,e,B,n){return{feature:B.feature?B.feature:"cards",
src_vid:f.context.videoData.videoId,annotation_id:e,ei:f.context.videoData.eventId||"",itct:n.trackingParams||""}},AsB=function(f,e){const B=e.cardId?e.cardId:`cr:${f.X}`;
var n=f.Z.S().experiments.SI("enable_error_corrections_infocard_web_client");if(!e.content&&e.teaser.simpleCardTeaserRenderer&&n){n=e.teaser.simpleCardTeaserRenderer;var r=e.icon?e.icon.infoCardIconRenderer:null;if(n.channelAvatar&&n.channelAvatar.thumbnails&&n.channelAvatar.thumbnails.length>0)var L=SR(n.channelAvatar.thumbnails,22,22).url;e={id:B,timestamp:f.X,type:"simple",teaserText:g.nS(n.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),
autoOpen:!!e.autoOpen,sessionData:{},sponsored:!1,o8:{},wc:null,fG:n.trackingParams?g.kv(n.trackingParams):null,kK:r&&r.trackingParams?g.kv(r.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,HV:null,title:"",customMessage:"",url:null,onClickCommand:n.onTapCommand||null,Eq:L};hC(f,e)}else if(e.content?.simpleCardContentRenderer){if(!e.cueRanges.length)return;L=e.content?.simpleCardContentRenderer;n=e.teaser.simpleCardTeaserRenderer;r=e.icon?e.icon.infoCardIconRenderer:null;e={id:B,
timestamp:f.X,type:"simple",teaserText:g.nS(n.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:E4(f,B,e,L),sponsored:!1,o8:FJ(L,n,L.command),wc:L.trackingParams?g.kv(L.trackingParams):null,fG:n.trackingParams?g.kv(n.trackingParams):null,kK:r&&r.trackingParams?g.kv(r.trackingParams):null,imageUrl:SR(L.image.thumbnails,290,290).url,displayDomain:L.displayDomain?g.nS(L.displayDomain):null,showLinkIcon:!!L.showLinkIcon,
HV:null,title:L.title?g.nS(L.title):"",customMessage:L.callToAction?g.nS(L.callToAction):"",url:g.u(L.command,g.jL).url?AC({pause_on_navigation:!f.context.videoData.isLivePlayback,target:"new",value:g.u(L.command,g.jL).url}):null,onClickCommand:null};hC(f,e)}else if(e.content?.collaboratorInfoCardContentRenderer){if(!e.cueRanges.length)return;L=e.content?.collaboratorInfoCardContentRenderer;n=e.teaser.simpleCardTeaserRenderer;r=e.icon?e.icon.infoCardIconRenderer:null;e={id:B,timestamp:f.X,type:"collaborator",
teaserText:g.nS(n.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:E4(f,B,e,L),sponsored:!1,o8:FJ(L,n,L.endpoint),wc:L.trackingParams?g.kv(L.trackingParams):null,fG:n.trackingParams?g.kv(n.trackingParams):null,kK:r&&r.trackingParams?g.kv(r.trackingParams):null,channelId:g.u(L.endpoint,g.Ip).browseId,customMessage:L.customText?g.nS(L.customText):null,profileImageUrl:SR(L.channelAvatar.thumbnails,290,
290).url,title:L.channelName?g.nS(L.channelName):"",metaInfo:[L.subscriberCountText?g.nS(L.subscriberCountText):""],url:AC({pause_on_navigation:!f.context.videoData.isLivePlayback,target:"new",value:g.u(L.endpoint,g.Ip).canonicalBaseUrl?g.u(L.endpoint,g.Ip).canonicalBaseUrl:`/channel/${g.u(L.endpoint,g.Ip).browseId}`}),onClickCommand:null};hC(f,e)}else if(e.content?.playlistInfoCardContentRenderer){if(!e.cueRanges.length)return;L=e.content?.playlistInfoCardContentRenderer;n=e.teaser.simpleCardTeaserRenderer;
r=e.icon?e.icon.infoCardIconRenderer:null;e={id:B,timestamp:f.X,type:"playlist",teaserText:g.nS(n.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:E4(f,B,e,L),sponsored:!1,o8:FJ(L,n,L.action),wc:L.trackingParams?g.kv(L.trackingParams):null,fG:n.trackingParams?g.kv(n.trackingParams):null,kK:r&&r.trackingParams?g.kv(r.trackingParams):null,bW:SR(L.playlistThumbnail.thumbnails,258,290).url,customMessage:L.customMessage?
g.nS(L.customMessage):null,playlistVideoCount:g.nS(L.playlistVideoCount),title:L.playlistTitle?g.nS(L.playlistTitle):"",metaInfo:[L.channelName?g.nS(L.channelName):"",L.videoCountText?g.nS(L.videoCountText):""],url:AC({pause_on_navigation:!f.context.videoData.isLivePlayback,target:"new",value:RuF(L.action)}),onClickCommand:null};hC(f,e)}else if(e.content?.videoInfoCardContentRenderer){if(!e.cueRanges.length)return;L=e.content?.videoInfoCardContentRenderer;n=e.teaser.simpleCardTeaserRenderer;r=e.icon?
e.icon.infoCardIconRenderer:null;e={id:B,timestamp:f.X,type:"video",teaserText:g.nS(n.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:E4(f,B,e,L),sponsored:!1,o8:FJ(L,n,L.action),wc:L.trackingParams?g.kv(L.trackingParams):null,fG:n.trackingParams?g.kv(n.trackingParams):null,kK:r&&r.trackingParams?g.kv(r.trackingParams):null,bW:SR(L.videoThumbnail.thumbnails,258,290).url,videoDuration:L.lengthString?
g.nS(L.lengthString):null,customMessage:L.customMessage?g.nS(L.customMessage):null,title:L.videoTitle?g.nS(L.videoTitle):"",metaInfo:[L.channelName?g.nS(L.channelName):"",L.viewCountText?g.nS(L.viewCountText):""],isLiveNow:!!L.badge,url:AC({pause_on_navigation:!f.context.videoData.isLivePlayback,target:"new",value:RuF(L.action)}),onClickCommand:null};hC(f,e)}f.X++},j2B=function(f,e){return g.$g(f.cards,B=>B.R1.id===e)},U4=function(f){g.h(f.Z.getRootNode(),"ytp-cards-shopping-active",OE2(f))},mH=function(f,
e){if(e=j2B(f,e))e===f.C&&(f.C=null),f.Z.removeCueRange(e.R1.id),g.tb(e.Ny),g.d2(f.cards,e),f.WS(),U4(f)},NN=function(f,e,B){if(!f.J){f.qC.show();
f.BS=new g.T6(()=>{g.PW(f.context.Z.getRootNode(),g.y1.IV_DRAWER_OPEN)},0);
f.BS.start();f.Z9.D(f.G,"mousewheel",r=>{f.eI.start();r.preventDefault();r=r||window.event;let L=0;r.type=="MozMousePixelScroll"?L=0==(r.axis==r.HORIZONTAL_AXIS)?r.detail:0:window.opera?L=r.detail:L=r.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?r.wheelDeltaY/-30:r.wheelDeltaY/-1.2:r.wheelDelta/-1.6:r.wheelDeltaY/-3;if(r=L)f.G.scrollTop+=r});
f.J=!0;var n=g.be();n&&f.PS&&f.K&&g.sR(n,[f.PS,f.K]);e={TRIGGER_TYPE:e};for(const r of f.cards)r.Mb||(r.Mb=!0,oWe(f.context.logger,r.R1.o8.ji,e)),n&&g.sR(n,[r.R1.wc]);Bz(f.Z);B&&(f.U=new g.T6(()=>{f.Lq=f.W;f.IA.focus()},330),f.U.start())}},zuH=function(f){g.I0(f.V3(),[g.y1.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.qX(f.Z,f.V,5);f.X5();f.W=g.x2("ytp-cards-button",f.Z.getRootNode());f.IA=g.x2("iv-drawer-close-button",f.V);f.isInitialized=!0},awe=function(f){f.Ed.push(g.IF("iv-teaser-shown",f.uC,f));
f.Ed.push(g.IF("iv-teaser-hidden",f.EE,f));f.Ed.push(g.IF("iv-teaser-clicked",f.Q3,f));f.G6=!0},KBI=function(f,e){f.A=e;
var B=f.Z.getVideoData();if(!B)return!1;B=g.hq(B);if(B?.markersMap)for(let r=0;B?.markersMap.length>r;r++){var n=B?.markersMap[r];if(n.key==="ERROR_CORRECTION_MARKERS"&&(n=n.value?.markers)&&n.length>0)return e.startMs=g.u(n[0],g.sGY)?.timeRangeStartMillis||0,f.A=null,!0}return!1},q0L=function(f,e){switch(e.type){case "simple":f=f.cS;
var B=e.displayDomain?{L:"div",B:"iv-card-image-text",Ga:e.displayDomain}:void 0;var n=vWV(e);B={L:"div",y9:["iv-card"],j:[{L:"a",B:"iv-click-target",O:{href:e.url?e.url.C()||"":""},j:[jR(e.imageUrl,B),{L:"div",B:"iv-card-content",j:[O4("h2",void 0,e.title),n]}]}]};B=new g.y(B);lV(f,g.Mo("iv-click-target",B.element),e,e.url);e=B;break;case "collaborator":f=f.cS;B={L:"div",y9:["iv-card","iv-card-channel"],j:[{L:"a",y9:["iv-click-target"],O:{href:e.url.C()||"","data-ytid":e.channelId},j:[jR(e.profileImageUrl),
{L:"div",B:"iv-card-content",j:[ok(e),{L:"h2",B:"iv-card-primary-link",Ga:e.title},Vk(e)]}]}]};B=new g.y(B);lV(f,g.Mo("iv-click-target",B.element),e,e.url);e=B;break;case "playlist":f=f.cS;B={L:"div",y9:["iv-card","iv-card-playlist"],j:[{L:"a",B:"iv-click-target",O:{href:e.url.C()||""},j:[jR(e.bW,{L:"div",B:"iv-card-image-overlay",j:[{L:"span",B:"iv-card-playlist-video-count",Ga:e.playlistVideoCount}]}),{L:"div",B:"iv-card-content",j:[ok(e),O4("h2","iv-card-primary-link",e.title),Vk(e)]}]}]};B=new g.y(B);
lV(f,g.Mo("iv-click-target",B.element),e,e.url);e=B;break;case "productListing":f=f.cS;var r=e.offers.length!=0;B=["iv-card"];n="";var L=vWV(e);r&&(B.push("iv-card-product-listing"),n="iv-card-primary-link",L=e.offers[0],r=[],L.price&&r.push({L:"div",B:"iv-card-offer-price",Ga:L.price}),L.merchant&&r.push({L:"div",B:"iv-card-offer-merchant",Ga:L.merchant}),L={L:"div",j:r});r=e.url?e.url.C()||"":"";B={L:"div",y9:B,O:{tabindex:"0"},j:[{L:"a",y9:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+
e.imageUrl+");",href:r,"aria-hidden":"true",tabindex:"-1"}},{L:"div",B:"iv-card-content",j:[e.sponsored?{L:"div",B:"iv-card-sponsored",j:["Sponsored",{L:"div",B:"iv-ad-info-container",j:[{L:"div",B:"iv-ad-info",Ga:"{{adInfo}}"},{L:"div",B:"iv-ad-info-icon-container",j:[{L:"div",B:"iv-ad-info-icon"},{L:"div",B:"iv-ad-info-callout"}]}]}]}:"",{L:"a",B:"iv-click-target",O:{href:r},j:[O4("h2",n,e.title),L]}]}]};B=new g.y(B);n=g.BN("span");g.kC(n,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
B.setContent(n,"adInfo");lV(f,g.Mo("iv-click-target",B.element),e,e.url);e=B;break;case "video":f=f.cS;B=e.isLiveNow?{L:"span",y9:["yt-badge","yt-badge-live"],Ga:"LIVE NOW"}:null;B={L:"div",y9:["iv-card","iv-card-video"],j:[{L:"a",B:"iv-click-target",O:{href:e.url?.C()||""},j:[jR(e.bW,e.videoDuration?{L:"span",B:"iv-card-video-duration",Ga:e.videoDuration}:void 0),{L:"div",B:"iv-card-content",j:[ok(e),O4("h2","iv-card-primary-link",e.title),Vk(e),B]}]}]};B=new g.y(B);lV(f,g.Mo("iv-click-target",B.element),
e,e.url);e=B;break;default:return null}return e},cs2=function(f,e){if(!g.yC(f.Z.getRootNode(),"ytp-cards-teaser-shown")){if(f.C!==e){var B=g.be(),n=f.C?f.C.R1.kK:f.kK;
B&&n&&g.Xd(B,[n]);f.C=e;U4(f)}(B=f.isInitialized&&f.V3().style.display=="none")||(B=f.context.Z.getPlayerState(),n=B===0&&f.context.Z.getCurrentTime()===0,B=!(B===1||B===3||n));B||e.R1.teaserDurationMs&&f.Z.e5(!0,{teaserText:e.R1.teaserText,durationMs:e.R1.teaserDurationMs,onClickCommand:e.R1.onClickCommand,Eq:e.R1.Eq??null});f.tL.isActive()||((!f.J||!f.eI.isActive()&&f.uY)&&pEx(f,e),f.tL.start(910+e.R1.teaserDurationMs))}},OE2=function(f){return f.C?f.C.R1.type==="productListing":f.Z.Y("enable_wn_infocards")?
!!f.cards?.length&&g.P5(f.cards,e=>e.R1.type==="productListing"):g.P5(f.cards,e=>e.R1.type==="productListing")},pEx=function(f,e){f.N.ef?(e=new tC([0,
f.G.scrollTop],[0,e.Ny.offsetTop],600,sx2),f.context.J.listen(e,"animate",B=>{f.G.scrollTop=B.y}),f.context.J.listen(e,"finish",B=>{f.G.scrollTop=B.y}),e.play()):(f.N.FG(!0),f.G.scrollTop=e.Ny.offsetTop,f.N.FG(!1))},Qk=function(f){return f.C&&f.C.R1?f.C.R1:f.cards[0]&&f.cards[0].R1?f.cards[0].R1:null},VUe=function(f){const e=f.annotation.data;
"start_ms"in e&&"end_ms"in e&&f.addCueRange(Number(e.start_ms),Number(e.end_ms),f.annotation.id,()=>{f.show()},()=>{f.hide()})},lwB=function(f,e){var B=QxI(e).width;
g.Em(e,B);B=new kd(e,[B,e.offsetTop],[B-B,e.offsetTop],200,WeV);g.A(f,B);f.context.J.listen(B,"begin",()=>{g.sm(e,!0)});
B.play()},T4=function(f,e,B){B.stopPropagation();
uLe(f);FBB(f,e);f.C.focus()},mbI=function(f){const e=f.annotation.data;
if(f.annotation.style==="cta")var B=6;else if(f.annotation.style==="video"||f.annotation.style==="playlist")B=7;f.U=e.collapsedelay_ms||f.U;const n=["iv-promo","iv-promo-inactive"];f.V3().setAttribute("aria-hidden","true");f.V3().setAttribute("aria-label","Promotion");f.V3().tabIndex=0;const r=f.annotation.Dw();let L;var d=e.image_url;d&&(L=f.createElement({L:"div",y9:["iv-promo-img","iv-click-target"]}),d=f.createElement({L:"img",O:{src:d,"aria-hidden":"true"}}),L.appendChild(d),e.video_duration&&
!e.is_live?(d=f.createElement({L:"span",B:"iv-promo-video-duration",Ga:e.video_duration}),L.appendChild(d)):e.playlist_length&&(d=f.createElement({L:"span",B:"iv-promo-playlist-length",Ga:e.playlist_length.toString()}),L.appendChild(d)),r&&uV(f,L,r,f.annotation.id,e.session_data,void 0,B));r?(d=f.createElement({L:"a",B:"iv-promo-txt"}),g.E0(d,r.C()),f.C=d):f.C=f.createElement({L:"div",B:"iv-promo-txt"});let t,H,k,C;switch(f.annotation.style){case "cta":case "website":t=f.createElement({L:"p",j:[{L:"strong",
Ga:e.text_line_1}]});H=f.createElement({L:"p",j:[{L:"span",B:"iv-promo-link",Ga:e.text_line_2}]});if(d=e.text_line_3)n.push("iv-promo-website-card-cta-redesign"),k=f.createElement({L:"button",y9:["iv-promo-round-expand-icon","ytp-button"]}),d=f.createElement({L:"button",y9:["iv-button","iv-promo-button"],j:[{L:"span",B:"iv-button-content",Ga:d}]}),C=f.createElement({L:"div",B:"iv-promo-button-container"}),C.appendChild(d),r&&uV(f,f.V3(),r,f.annotation.id,e.session_data,void 0,B);g.PW(f.C,"iv-click-target");
r&&uV(f,f.C,r,f.annotation.id,e.session_data,void 0,B);break;case "playlist":case "video":t=f.createElement({L:"p",j:[{L:"span",Ga:e.text_line_1}]}),H=f.createElement({L:"p",j:[{L:"strong",Ga:e.text_line_2}]}),e.is_live&&(t=H,H=f.createElement({L:"span",y9:["yt-badge","iv-promo-badge-live"],Ga:"LIVE NOW"})),g.PW(f.C,"iv-click-target"),r&&uV(f,f.C,r,f.annotation.id,e.session_data,void 0,B),n.push("iv-promo-video")}t&&f.C.appendChild(t);H&&f.C.appendChild(H);f.X.appendChild(f.C);C&&f.X.appendChild(C);
B=f.createElement({L:"div",B:"iv-promo-actions"});f.G=f.createElement({L:"button",y9:["iv-promo-expand","ytp-button"]});f.G.title="Expand";f.context.C.listen(f.G,"click",w=>{T4(f,5E3,w)});
B.appendChild(f.G);g.sm(f.G,!1);f.context.C.listen(f.V3(),"mouseover",f.eI,f);f.context.C.listen(f.V3(),"mouseout",f.cS,f);f.context.C.listen(f.V3(),"touchend",w=>{T4(f,5E3,w)});
f.J=f.createElement({L:"button",y9:["iv-promo-close","ytp-button"]});f.J.title="Close";f.context.C.listen(f.J,"click",f.annotation.style==="cta"&&e.text_line_3?f.A:f.Ed,f);B.appendChild(f.J);g.I0(f.V3(),n);L&&(g.rw(f.V3(),L),k&&L.appendChild(k));g.rw(f.V3(),f.X);g.rw(f.V3(),B)},DN=function(f){f.V&&(g.Kw.clearTimeout(f.V),f.V=null)},uLe=function(f){f.W.stop();
f.isCollapsed&&(g.il(f.V3(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),f.isCollapsed=!1,f.C&&f.C.removeAttribute("aria-hidden"),g.sm(f.G,!1),g.sm(f.J,!0))},FBB=function(f,e){f.V||(f.V=g.Iv(function(){DN(this);
Ube(this)},e,f))},Ube=function(f){f.isCollapsed||f.K||f.V||(g.PW(f.V3(),"iv-promo-collapsed"),f.isCollapsed=!0,f.W.start())},oWe=function(f,e,B){e&&(B?JC(f,e.map(n=>g.pX(n,B))):JC(f,e))},JC=function(f,e,B,n){let r=1,L=void 0,d=-1;
if(B){let t=!1;L=()=>{r--;r||t||(clearTimeout(d),t=!0,B())};
d=setTimeout(()=>{t=!0;B()},1E3)}for(const t of e||[])r++,g.gq(t,L);
n&&(r++,n!==0&&f.Z.sendVideoStatsEngageEvent(n,L))},N0e=function(f){return f==="annotation-editor"||f==="live-dashboard"},huM=function(f){f.V&&(f.player.removeEventListener("videodatachange",f.V),f.V=null)},gWF=function(f){f=f.createElement({L:"div",
y9:["annotation","annotation-type-custom"]});g.sm(f,!1);return f},G4=function(f,e){var B=!1,n=e.getElementsByTagName("annotations");
if(n&&!(n.length<1)&&(n=n[0].getAttribute("itct"))){var r=g.be();if(r){var L=g.v6();L&&g.LN(g.Sa)(void 0,r,L,[g.kv(n)])}}e=e.getElementsByTagName("annotation");for(n=0;n<e.length;n++){var d=S0M(f,e[n]);r=null;try{a:{if(!d){r=null;break a}var t=d.id;L=/.+/;const b=typeof t==="string"&&L!=null&&t!=null&&t.match(L)?t:"",K=Yd(d.type,EWB),Y=Yd(d.style,Q2u),l=rsM(d.data),m=l.length!==0?JSON.parse(l):{};b:{var H=d.action;L=CPM;if(H==null){var k=null;break b}if(g.Yg(H)){d=[];for(const N of H){const E=L(N);
E&&d.push(E)}k=d;break b}const F=L(H);k=F?[F]:[]}L=k;r=b&&K?new T0B(b,K,Y,L,m):null}}catch(b){}if(r)if(r.type==="branding"||r.type==="promotion"){L=f;d=r;var C=gWF(L),w=null;switch(d.type){case "branding":if(L.player.S().mS)break;L.player.Y("web_player_overlay_positioned_layout")?(C.setAttribute("data-overlay-order","11"),L.player.vr(C,4,!0)):L.G.element.appendChild(C);w=new Dbg(C,MN(L),d);break;case "promotion":g.qX(L.player,C,4),w=new Jsg(C,MN(L),d)}w&&w.Cq();if(L=w)g.A(f,L),f.U[r.id]=L}else if(r.type===
"card"||r.type==="drawer"){f.C||(f.C=MUT(f),g.A(f,f.C));if(r.type==="card"){C=f.C;var v=(B=r)&&B.data&&B.data.card_type;r=B.data;if(v)switch(L=r.tracking||{},L={ji:L.impression,click:L.click,close:L.close,zH:L.teaser_impression,Q0:L.teaser_click},d=r.tracking_params||{},w=null,v){case "collaborator":B={id:B.id,timestamp:r.timestamp||0,type:r.card_type,teaserText:r.teaser_text,teaserDurationMs:r.teaser_duration_ms,startMs:r.start_ms,autoOpen:r.auto_open||!1,sessionData:r.session_data||{},sponsored:r.sponsored||
!1,o8:L,wc:d.card?g.kv(d.card):null,fG:d.teaser?g.kv(d.teaser):null,kK:d.icon?g.kv(d.icon):null,channelId:r.channel_id,customMessage:r.custom_message?r.custom_message:null,profileImageUrl:r.image_url,title:r.title,metaInfo:r.meta_info,url:AC({pause_on_navigation:r.pause_on_navigation,target:r.target||"new",value:r.url}),onClickCommand:null};hC(C,B);break;case "playlist":B={id:B.id,timestamp:r.timestamp||0,type:r.card_type,teaserText:r.teaser_text,teaserDurationMs:r.teaser_duration_ms,startMs:r.start_ms,
autoOpen:r.auto_open||!1,sessionData:r.session_data||{},sponsored:r.sponsored||!1,o8:L,wc:d.card?g.kv(d.card):null,fG:d.teaser?g.kv(d.teaser):null,kK:d.icon?g.kv(d.icon):null,bW:r.image_url,playlistVideoCount:r.playlist_video_count,customMessage:r.custom_message?r.custom_message:null,title:r.title,metaInfo:r.meta_info,url:AC({pause_on_navigation:r.pause_on_navigation,target:r.target||"new",value:r.url}),onClickCommand:null};hC(C,B);break;case "productListing":r.signin_url&&(w=AC({target:"current",
value:r.signin_url}));v=[];const b=r.offers||[];for(let K=0;K<b.length;K++)v.push(new Gcx(g.dr(b[K].merchant),g.dr(b[K].price)));B={id:B.id,timestamp:r.timestamp||0,type:r.card_type,teaserText:r.teaser_text,teaserDurationMs:r.teaser_duration_ms,startMs:r.start_ms,autoOpen:r.auto_open||!1,sessionData:r.session_data||{},sponsored:r.sponsored||!1,o8:L,wc:d.card?g.kv(d.card):null,fG:d.teaser?g.kv(d.teaser):null,kK:d.icon?g.kv(d.icon):null,imageUrl:r.image_url,displayDomain:r.display_domain?r.display_domain:
null,showLinkIcon:!!r.show_link_icon,HV:r.button_icon_url?r.button_icon_url:null,title:r.title,customMessage:r.custom_message?r.custom_message:null,url:AC({pause_on_navigation:r.pause_on_navigation,target:r.target||"new",value:r.url}),ptA:w,LdY:r.signin_title?r.signin_title:void 0,WdL:r.signin_message?r.signin_message:void 0,offers:v,onClickCommand:null};hC(C,B);break;case "simple":B={id:B.id,timestamp:r.timestamp||0,type:r.card_type,teaserText:r.teaser_text,teaserDurationMs:r.teaser_duration_ms,
startMs:r.start_ms,autoOpen:r.auto_open||!1,sessionData:r.session_data||{},sponsored:r.sponsored||!1,o8:L,wc:d.card?g.kv(d.card):null,fG:d.teaser?g.kv(d.teaser):null,kK:d.icon?g.kv(d.icon):null,imageUrl:r.image_url,displayDomain:r.display_domain?r.display_domain:null,showLinkIcon:!!r.show_link_icon,HV:r.button_icon_url?r.button_icon_url:null,title:r.title,customMessage:r.custom_message?r.custom_message:null,url:AC({pause_on_navigation:r.pause_on_navigation,target:r.target||"new",value:r.url}),onClickCommand:null};
hC(C,B);break;case "video":B={id:B.id,timestamp:r.timestamp||0,type:r.card_type,teaserText:r.teaser_text,teaserDurationMs:r.teaser_duration_ms,startMs:r.start_ms,autoOpen:r.auto_open||!1,sessionData:r.session_data||{},sponsored:r.sponsored||!1,o8:L,wc:d.card?g.kv(d.card):null,fG:d.teaser?g.kv(d.teaser):null,kK:d.icon?g.kv(d.icon):null,bW:r.image_url,videoDuration:r.video_duration||null,customMessage:r.custom_message?r.custom_message:null,title:r.title,metaInfo:r.meta_info,isLiveNow:!!r.is_live_now,
url:AC({pause_on_navigation:r.pause_on_navigation,target:r.target||"new",value:r.url}),onClickCommand:null},hC(C,B)}}else Y0B(f.C,r);B=!0}}B&&(Bz(f.player),f.N())},xbg=function(f){const e=f.player.S();
f=f.player.getVideoData();return(e.annotationsLoadPolicy||f.annotationsLoadPolicy)===1&&!f.qe||e.PS.get(f.videoId)||f.jX()||g.S_(f)?!0:!1},WBg=function(f,e){e=!e.isCued()&&!e.C(1024);
f.G.FG(e);f.J.FG(e)},PPV=function(f,e){const B=e.videoId;
var n=L=>{var d=f.loadNumber;f.X=null;f.loaded&&f.loadNumber===d&&f.player.getVideoData().videoId===B&&(L=g.o6(L)&&L.responseXML?L.responseXML:null)&&(G4(f,L),g.PW(f.player.getRootNode(),"iv-module-loaded"))};
g.Z4()&&(n=s2M(f,n));const r={format:"XML",onFinish:n,onError:()=>{f.X=null},
urlParams:{}};e.isPharma&&(r.urlParams.pharma="1");r.method="POST";r.withCredentials=!0;(n=f.player.S().PS.get(B))&&XEL(r,n);n=n&&n.Ti;if(!e.DI||n)f.V=()=>{if(!f.A)f.onVideoDataChange(r);const L=f.player.getVideoData();L?.y8()&&!f.Ed&&ysH(f,L)},f.player.addEventListener("videodatachange",f.V)},xd=function(f,e){var B=!1;
f.C||(f.C=MUT(f),g.A(f,f.C));for(var n of e.cards||[])n.cardRenderer&&(AsB(f.C,n.cardRenderer),B=!0);B&&(f.player.getVideoData()?.y8()||(B=f.C,n=e.headerText?g.nS(e.headerText):"",g.kC(B.Ch,n),B.W&&(B.Z.Y("player_tooltip_data_title_killswitch")?B.W.setAttribute("title",n):B.W.setAttribute("data-tooltip-title",n)),B.context.videoData.eventId&&(B.eventId=B.context.videoData.eventId),B.PS=e.trackingParams?g.kv(e.trackingParams):null,B.K=e.closeButton.infoCardIconRenderer.trackingParams?g.kv(e.closeButton.infoCardIconRenderer.trackingParams):
null,B.kK=e.icon.infoCardIconRenderer.trackingParams?g.kv(e.icon.infoCardIconRenderer.trackingParams):null,f.N()),Bz(f.player))},ysH=function(f,e){if(e=e.getWatchNextResponse()?.cards?.cardCollectionRenderer)f.Ed=!0,xd(f,e),e.headerText&&f.RM&&(e=g.nS(e.headerText),f.player.Y("player_tooltip_data_title_killswitch")?f.RM.setAttribute("title",e):f.RM.setAttribute("data-tooltip-title",e))},s2M=function(f,e){return(...B)=>{f.HS()||f.Cq.push(g.ul.Br(()=>{e(...B)}))}},XEL=function(f,e){f.method="POST";
f.postParams=f.postParams||{};e.Ti&&(f.postParams.ic_coll=e.Ti);e.Vd&&(f.postParams.ic_track=e.Vd)},S0M=function(f,e){const B={};
for(var n of e.attributes)B[n.name]=n.nodeValue;for(n=0;n<e.childNodes.length;n++){var r=e.childNodes[n];if(!g.jC(r)||r.nodeType!=1)continue;var L=void 0;if(B[r.tagName])L=B[r.tagName];else if(r.tagName==="data"){r.childNodes.length>0&&(L=r.childNodes[0].nodeValue,B[r.tagName]=typeof L==="string"?L.trim():L);continue}else L=[],B[r.tagName]=L;r&&r.tagName==="TEXT"?r.childNodes.length===1&&r.childNodes[0].nodeType===3?L.push(r.childNodes[0].nodeValue):L.push(""):r&&L.push(S0M(f,r))}return B},MN=function(f){if(!f.K){const e=
new IwH(f);
g.A(f,e);const B=new g.fX(f);g.A(f,B);f.K=new $bB(e,B,f.player.S(),f.player.getVideoData(),f.logger,f.player,f.Ys)}return f.K},iEx=function(f){const e=f.player.getVideoData();
if(e.j7){var B=f.player.S().PS.get(e.videoId);if(B){var n={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(r,L,d)=>{r=f.loadNumber;L=e.videoId;f.loaded&&f.loadNumber===r&&f.player.getVideoData().videoId===L&&(d=g.o6(d)&&d.responseXML?d.responseXML:null)&&G4(f,d)}};
g.Z4()&&(n.onFinish=s2M(f,n.onFinish));n.postParams={ic_only:"1"};XEL(n,B);f.A=!0;g.QY(e.j7,n)}}},MUT=function(f){const e=new g.y({L:"div"});
g.sm(e.element,!1);const B=new fmH(f.player,e.element,MN(f));g.A(B,e);e.di(f.G.element);B.Cq();return B},erV=function(f,e,B,n,r){if(!f.player.S().mS){var L=[];
e.navigationEndpoint&&g.u(e.navigationEndpoint,g.Ip)&&g.u(e.navigationEndpoint,g.Ip).browseId&&L.push(new kcG("openUrl","click",new dbe(`/channel/${g.u(e.navigationEndpoint,g.Ip).browseId}`,"new",!0,!0)));var d=e.watermark.thumbnails[0];n={channel_name:e.channelName,end_ms:e.endTimeMs,image_height:d.height,image_type:1,image_url:d.url,image_width:d.width,is_mobile:!1,session_data:{annotation_id:B,ei:r,feature:"iv",itct:e.trackingParams,src_vid:n},start_ms:e.startTimeMs};if(e.subscribeButton&&g.u(e.subscribeButton,
g.C2)){n.channel_id=g.u(e.subscribeButton,g.C2).channelId;e=g.u(e.subscribeButton,g.C2);d=r=null;e.subscribed?(e.subscriberCountWithUnsubscribeText&&(r=g.nS(e.subscriberCountWithUnsubscribeText)),e.subscriberCountText&&(d=g.nS(e.subscriberCountText))):(e.subscriberCountText&&(r=g.nS(e.subscriberCountText)),e.subscriberCountWithSubscribeText&&(d=g.nS(e.subscriberCountWithSubscribeText)));const t=g.u(e.signInEndpoint?.commandMetadata,g.L1)?.url||"";e={subscribeText:g.nS(e.unsubscribedButtonText),subscribeCount:r||
"",unsubscribeText:g.nS(e.subscribedButtonText),unsubscribeCount:d||"",enabled:e.enabled||!1,classic:!1,subscribed:e.subscribed||!1,feature:"iv",signInUrl:t};n.standalone_subscribe_button_data=e}L=new T0B(B,"branding","branding",L,n);n=gWF(f);f.player.Y("web_player_overlay_positioned_layout")?(n.setAttribute("data-overlay-order","11"),f.player.vr(n,4,!0)):f.G.element.appendChild(n);L=new Dbg(n,MN(f),L);L.Cq();g.A(L,L);f.U[B]=L}};
g.sL.prototype.e5=g.B5(36,function(f,e){const B=g.V9(this.iC());B&&B.e5(f,e)});
var r4={},LG=null;g.Uk(tC,g.eh);g.c=tC.prototype;g.c.getDuration=function(){return this.duration};
g.c.play=function(f){if(f||this.C==0)this.progress=0,this.coords=this.G;else if(this.isPlaying())return!1;d4(this);this.startTime=f=g.u0();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.V=this.startTime;this.progress||this.nt();this.UT("play");this.isPaused()&&this.UT("resume");this.C=1;const e=g.od(this);e in r4||(r4[e]=this);JuH();MBM(this,f);return!0};
g.c.stop=function(f){d4(this);this.C=0;f&&(this.progress=1);GLF(this,this.progress);this.onStop();this.SG()};
g.c.pause=function(){this.isPlaying()&&(d4(this),this.C=-1,this.UT("pause"))};
g.c.bY=function(){this.C==0||this.stop(!1);this.UT("destroy");tC.lj.bY.call(this)};
g.c.destroy=function(){this.dispose()};
g.c.bD=function(){this.UT("animate")};
g.c.UT=function(f){this.dispatchEvent(new xT2(f,this))};
g.Uk(xT2,g.fI);g.Uk(Hz,tC);Hz.prototype.J=function(){};
Hz.prototype.bD=function(){this.J();Hz.lj.bD.call(this)};
Hz.prototype.SG=function(){this.J();Hz.lj.SG.call(this)};
Hz.prototype.nt=function(){this.J();Hz.lj.nt.call(this)};
g.Uk(kd,Hz);kd.prototype.J=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var IwH=class extends g.$0{constructor(f){super();this.G=f||window;this.C=[]}listen(f,e,B,n){B=(0,g.VG)(B,n||this.G);f=g.Ds(f,e,B);this.C.push(f);return f}Vw(f,e,B,n){B=(0,g.VG)(B,n||this.G);f=T22(f,e,B);this.C.push(f);return f}uh(f){g.Jl(f);g.d2(this.C,f)}removeAll(){g.Jl(this.C);this.C.length=0}bY(){this.removeAll();super.bY()}};var doL=class extends g.zV{constructor(f){super(f);this.V=this.endscreen=null;this.G={};this.U={};this.W=this.J=null;this.K=[];this.C=null;this.Ed=!0;this.X=0;f=f.S();this.N=g.Ms(f)||g.Wk(f);this.events=new g.ep(this);g.A(this,this.events);this.events.D(this.player,g.kk("creatorendscreen"),this.onCueRangeEnter);this.events.D(this.player,g.Ca("creatorendscreen"),this.onCueRangeExit);this.events.D(this.player,"resize",this.Sf);this.events.D(window,"focus",this.A);this.load();const e=g.BN("STYLE");(g.Jj("HEAD")[0]||
document.body).appendChild(e);this.addOnDisposeCallback(()=>{g.tb(e)});
e.sheet&&(e.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),e.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!bV(this)){var f=g.T$O(this.player.getVideoData());f?(f=vz(f,yuu(this)),ZN(this,f,!1)):iFB(this)}}unload(){ZN(this,null);this.V&&(this.V.abort(),this.V=null);super.unload()}gZ(f,e){return bV(this)?f==="loadCustomEndscreenRenderer"?(f=vz(e,"new"),ZN(this,f),!0):null:null}getOptions(){return bV(this)?["loadCustomEndscreenRenderer"]:[]}Sf(){if(this.endscreen&&this.endscreen.elements){var f=this.player.getVideoContentRect();if(f&&f.width!==0&&f.height!==0){var e=this.player.getPlayerSize();
if(e&&e.width!==0&&e.height!==0){var B=f.width/f.height;var n=0;var r=-1;for(var L=0;L<BrG.length;L++){var d=Math.abs(e.width-BrG[L]);if(r===-1||n>=d)r=L,n=d}n=n2M[r];this.J&&g.uc(this.J.element,"outline-width",Math.max(e.width,e.height)+"px");for(e=0;e<this.endscreen.elements.length;++e){L=this.endscreen.elements[e].id;r=this.G[L];d=this.U[L];if(!r||!d)continue;const H=d.width*B/d.aspectRatio;var t=Math.round(d.width*f.width);L=Math.round(H*f.height);const k=f.left+Math.round(d.left*f.width),C=f.top+
Math.round(d.top*f.height);g.xC(r.element,t,L);g.Em(r.element,k,C);g.il(r.element,rjg);t>256||L>256?g.PW(r.element,"ytp-ce-large-round"):t>96||L>96?g.PW(r.element,"ytp-ce-medium-round"):g.PW(r.element,"ytp-ce-small-round");g.il(r.element,L$e);t=d.left+d.width/2;d=d.top+H/2;g.PW(r.element,t<=.5&&d<=.5?"ytp-ce-top-left-quad":t>.5&&d<=.5?"ytp-ce-top-right-quad":t<=.5&&d>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.il(r.element,n2M);g.PW(r.element,n);(r=g.Ge(document,"div","ytp-ce-expanding-overlay-body",
r.element)[0])&&g.uc(r,"height",`${L}px`)}}}}}onCueRangeEnter(f){if(this.endscreen)if(f.getId()==="ytp-ce-in-endscreen")pG(this,this.endscreen.impressionUrls),(f=g.be())&&this.endscreen.visualElement&&g.W6(f,this.endscreen.visualElement),this.C&&(g.PW(this.C,"ytp-ce-element-show"),this.C.removeAttribute("aria-hidden"),this.player.O4()?g.PW(this.C,"ytp-ce-hide-button-lower"):g.$i(this.C,"ytp-ce-hide-button-lower"));else{f=f.getId().substring(15);var e=this.G[f],B=this.U[f];g.PW(e.element,"ytp-ce-element-show");
e.element.removeAttribute("aria-hidden");e=this.player.getRootNode();g.PW(e,"ytp-ce-shown");pG(this,B.impressionUrls);(e=g.be())&&g.W6(e,B.visualElement);this.player.S().K&&g.yW(this.player,"endscreenelementshown",f)}}onCueRangeExit(f){if(f.getId()==="ytp-ce-in-endscreen")this.C&&(g.$i(this.C,"ytp-ce-element-show"),this.C.setAttribute("aria-hidden","true"));else{f=f.getId().substring(15);var e=this.G[f];g.$i(e.element,"ytp-ce-element-show");e.element.setAttribute("aria-hidden","true");e=this.player.getRootNode();
g.$i(e,"ytp-ce-shown");this.player.S().K&&g.yW(this.player,"endscreenelementhidden",f)}}A(f){f.target===window&&(new g.T6(()=>{for(const e of Object.values(this.G))g.il(e.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}FG(f){for(const e of Object.values(this.G))f?e.element.setAttribute("hidden",""):e.element.removeAttribute("hidden")}gW(f){this.C&&this.player.getRootNode().removeChild(this.C);
f&&(g.PW(f,"ytp-ce-hide-button-container"),this.C=f,g.qX(this.player,this.C,4))}},BrG=[346,426,470,506,570,640,853,1280,1920],n2M="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),L$e=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],rjg=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var dbe=class{constructor(f,e,B,n){this.value=f;this.target=e;this.showLinkIcon=B;this.G=n}C(){return this.value?this.value:null}},LBB={xQ:"current",cW:"new"};var kcG=class{constructor(f,e,B){this.type=f;this.trigger=e;this.url=B}},tUG={CLOSE:"close",d_:"openUrl",SUBSCRIBE:"subscribe"},HEg={fX:"click",CLOSE:"close",Vp:"hidden",Ydd:"rollOut",XSl:"rollOver",hjq:"shown"};var T0B=class{constructor(f,e,B,n,r){this.id=f;this.type=e;this.style=B;this.data=r;this.action=n||[]}Dw(){const f=wEI(this,e=>e.type==="openUrl"&&e.url!=null);
return f?f.url:null}},Q2u={Bn:"anchored",oz:"branding",CHANNEL:"channel",NJ:"cta",iZ:"highlightText",bQ:"label",PLAYLIST:"playlist",POPUP:"popup",xCY:"speech",SUBSCRIBE:"subscribe",JEa:"title",VIDEO:"video",xkq:"website"},EWB={oz:"branding",dO:"card",eE:"drawer",L3:"highlight",wJ:"marker",OZ:"promotion",TEXT:"text",YE9:"widget"};var tye=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
HHL=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var keH=class{constructor(f,e){this.context=f;this.C=e}};var Gcx=class{constructor(f,e){this.merchant=f;this.price=e}};var CNH=class extends g.$0{constructor(f,e){super();this.element=f;this.context=e;this.xA=!1;this.MC=new Map;this.kA=new Map;this.context.Z.addEventListener(g.kk("annotations_module"),B=>{(B=this.MC.get(B))&&B.apply(this)});
this.context.Z.addEventListener(g.Ca("annotations_module"),B=>{(B=this.kA.get(B))&&B.apply(this)})}addCueRange(f,e,B,n,r){f=new g.VD(f,e,{id:B,
namespace:"annotations_module"});n&&this.MC.set(f,n);r&&this.kA.set(f,r);this.context.Z.AI([f],1)}Cq(){this.context.G.subscribe("resize",this.WS,this)}V3(){return this.element}Fl(f,e,B,n,r,L){if(this.xA)return!1;L&&(L.stopPropagation(),L.preventDefault());this.navigate(f,B,n,r);return!1}show(){}hide(){}destroy(){g.tb(this.V3())}WS(){}navigate(f,e,B,n){const r=f.C();if(r){var L=ZEV(r,f.target),d=()=>{f.G&&this.context.Z.pauseVideo();const t=this.context.videoData.AF||!1,H=g.vb(r||"");t&&H&&(H.v||H.list)?
this.context.Z.P6(H.v,e,H.list,!1):g.I5(r||"",L==="current"?"_top":void 0,e)};
L==="new"&&(d(),d=null);JC(this.context.logger,B,d,n);bEV(r)||(B=g.be(),n=e.itct,B&&n&&g.yL(B,g.kv(n)))}}bY(){this.MC.clear();this.kA.clear();super.bY()}createElement(f){f=new g.y(f);g.A(this,f);return f.element}};var fmH=class extends CNH{constructor(f,e,B){super(e,B);this.Z=f;this.eventId=null;this.G6=this.uY=this.Yp=this.J=this.isInitialized=!1;this.cards=[];this.IA=this.W=this.Lq=this.U=this.BS=this.C=null;this.Ed=[];this.A=this.K=this.kK=this.PS=null;this.X=0;this.eI=new g.T6(()=>{},B.Ta.S6?4E3:3E3);
g.A(this,this.eI);this.tL=new g.T6(()=>{});
g.A(this,this.tL);this.cS=new keH(B,(n,r,L,d,t,H)=>{uV(this,n,r,L,d,t,H)});
this.N=new g.y({L:"div",B:"iv-drawer",O:{id:"iv-drawer"},j:[{L:"div",B:"iv-drawer-header",O:{"aria-role":"heading"},j:[{L:"span",B:"iv-drawer-header-text"},{L:"button",y9:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{L:"div",B:"iv-drawer-content"}]});g.A(this,this.N);this.V=this.N.element;this.qC=new g.Ob(this.N,330);g.A(this,this.qC);this.Ch=g.x2("iv-drawer-header-text",this.V);this.G=g.x2("iv-drawer-content",this.V);this.addCueRange(0,B.videoData.lengthSeconds*
1E3,"",()=>{this.Yp&&NN(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.Yp=this.J)&&g4(this)});
this.Z9=new g.ep(this);g.A(this,this.Z9);this.Z.addEventListener("videodatachange",this.N9.bind(this))}N9(){this.A&&hC(this,this.A)}isAvailable(){var f;if(f=!!this.cards.length)(f=this.Z.getRootNode())?(f=g.WN(f),f=173<f.width&&173<f.height):f=!1;return f}WS(){const f=this.isAvailable();g.sm(this.V3(),f);g.h(this.context.Z.getRootNode(),g.y1.IV_DRAWER_ENABLED,f);Bz(this.Z)}destroy(){this.Z.e5(!1);try{this.Z.getRootNode().removeChild(this.V)}catch(f){}g.$n(this.Ed);this.Z9.G();this.BS&&this.BS.dispose();
this.U&&this.U.dispose();super.destroy()}X5(){this.context.C.listen(g.x2("iv-drawer-close-button",this.V),"click",this.hE,this);this.context.C.listen(this.G,"touchend",()=>{this.eI.start()});
this.context.C.listen(this.G,"scroll",this.Mk,this);this.context.G.subscribe("onHideControls",()=>{this.uY=!0});
this.context.G.subscribe("onShowControls",()=>{this.uY=!1});
this.context.G.subscribe("onVideoAreaChange",()=>{this.uY=g.yC(this.Z.getRootNode(),"ytp-autohide")});
this.Ed.push(g.IF("iv-button-shown",this.lC,this));this.Ed.push(g.IF("iv-button-hidden",this.mS,this));awe(this)}findLastIndex(f){if(this.cards.length===0)return 0;const e=g.i0(this.cards,B=>f.R1.startMs>B.R1.startMs||f.R1.startMs===B.R1.startMs&&f.R1.timestamp>=B.R1.timestamp?!0:!1);
return e===-1?0:e+1}hE(){if(this.J){JC(this.context.logger,Qk(this).o8.close);var f=g.be();f&&this.K&&g.yL(f,this.K);g4(this)}}Mk(){g.h(this.V,"iv-drawer-scrolled",this.G.scrollTop>0)}lC(){const f=g.be();var e=Qk(this);e=e?e.kK:this.kK;f&&e&&g.sR(f,[e])}mS(){const f=g.be();var e=Qk(this);e=e?e.kK:this.kK;f&&e&&g.Xd(f,[e])}uC(){const f=Qk(this);JC(this.context.logger,f.o8.zH);const e=g.be();if(e&&f)if(this.Z.Y("web_infocards_teaser_show_logging_fix")){const B=[];f.fG&&B.push(f.fG);f.kK&&B.push(f.kK);
B.length>0&&g.sR(e,B)}else g.sR(e,[f.fG,f.kK])}EE(){const f=g.be(),e=Qk(this);f&&e&&g.Xd(f,[e.fG])}Q3(f){const e=Qk(this),B=g.be();this.C?f?(f=this.context.logger,JC(f,e.o8.Q0),f.Z.sendVideoStatsEngageEvent(4,void 0),B&&e.fG&&g.yL(B,e.fG)):(f=this.context.logger,JC(f,e.o8.Q0),f.Z.sendVideoStatsEngageEvent(4,void 0),B&&e.kK&&g.yL(B,e.kK)):(f=this.context.logger,JC(f,e.o8.Q0),f.Z.sendVideoStatsEngageEvent(4,void 0),B&&this.kK&&g.yL(B,this.kK))}};var whB=class extends CNH{constructor(f,e,B){super(f,e);this.annotation=B;this.isActive=!1}Cq(){super.Cq();VUe(this)}show(){super.show();const f=g.be();var e=this.annotation.data;f&&e&&(e=e.session_data)&&g.sR(f,[g.kv(e.itct)])}hide(){super.hide();const f=g.be();var e=this.annotation.data;f&&e&&(e=e.session_data)&&g.Xd(f,[g.kv(e.itct)])}};var Dbg=class extends whB{constructor(f,e,B){super(f,e,B);this.C=null;this.J=!1;this.G=null}show(){if(!this.isActive){super.show();if(!this.J){g.PW(this.V3(),"iv-branding");const f=this.annotation.data;this.C=this.createElement({L:"img",y9:["branding-img","iv-click-target"],O:{"aria-label":"Channel watermark",src:f.image_url,width:f.image_width,height:f.image_height}});g.sm(this.C,!1);const e=this.createElement({L:"button",y9:["branding-img-container","ytp-button"]});e.appendChild(this.C);this.V3().appendChild(e);
const B=this.annotation.Dw();B&&uV(this,e,B,this.annotation.id,f.session_data);this.J=!0}g.sm(this.V3(),!0);this.isActive=!0;if(this.C){try{lwB(this,this.C)}catch{}g.PW(this.context.Z.getRootNode(),"ytp-branding-shown");this.context.Z.getRootNode().style.setProperty("--branding-image-width",`${this.C.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.sm(this.V3(),!1),this.isActive=!1,g.$i(this.context.Z.getRootNode(),"ytp-branding-shown"))}destroy(){this.G&&(this.G.dispose(),this.G=
null);g.$i(this.context.Z.getRootNode(),"ytp-branding-shown");super.destroy()}};var $bB=class{constructor(f,e,B,n,r,L,d){this.C=f;this.J=e;this.Ta=B;this.videoData=n;this.logger=r;this.Z=L;this.G=d}};var Jsg=class extends whB{constructor(f,e,B){super(f,e,B);this.K=this.isCollapsed=this.N=!1;this.U=5E3;this.G=this.J=this.C=this.V=null;this.X=this.createElement({L:"div",y9:["iv-promo-contents"]});this.W=new g.T6(()=>{this.C.setAttribute("aria-hidden","true");g.sm(this.J,!1);g.sm(this.G,!0)},700,this);
g.A(this,this.W)}show(){this.isActive||(super.show(),this.N||(mbI(this),this.N=!0),g.sm(this.V3(),!0),g.Iv(function(){g.$i(this.V3(),"iv-promo-inactive")},100,this),this.V3().removeAttribute("aria-hidden"),this.isActive=!0,DN(this),uLe(this),FBB(this,this.U))}hide(){this.isActive&&(g.PW(this.V3(),"iv-promo-inactive"),this.isActive=!1,this.V3().setAttribute("aria-hidden","true"))}Fl(f,e,B,n,r,L){return this.isCollapsed?!1:super.Fl(f,e,B,n,r,L)}eI(f){this.K=!0;
T4(this,500,f)}cS(){this.K=!1;Ube(this)}Ed(f){f.stopPropagation();this.hide()}A(f){f.stopPropagation();DN(this);this.isCollapsed=!0;g.PW(this.V3(),"iv-promo-collapsed-no-delay");this.W.start()}destroy(){this.W.dispose();super.destroy()}};var v2x=class{constructor(f){this.Z=f}};g.cO("annotations_module",class extends g.zV{constructor(f){super(f);this.Ed=this.A=!1;this.loadNumber=0;this.U={};this.logger=new v2x(this.player);this.W=new g.ep(this);this.X=this.V=null;this.events=new g.ep(this);this.RM=this.K=this.C=null;this.Cq=[];g.A(this,this.W);this.W.D(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.W.D(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.W.D(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.W.D(this.player,"resize",B=>{this.publish("resize",B)});
this.W.D(this.player,"presentingplayerstatechange",B=>{this.publish("presentingplayerstatechange",B)});
this.subscribe("presentingplayerstatechange",this.eI,this);this.subscribe("resize",this.N,this);this.player.S().PS.subscribe("vast_info_card_add",this.cS,this);g.A(this,this.events);this.WS=this.createElement({L:"div",B:"video-custom-annotations"});this.G=new g.y({L:"div",y9:["ytp-player-content","ytp-iv-player-content"]});g.A(this,this.G);g.qX(this.player,this.G.element,4);this.G.hide();this.J=new g.y({L:"div",y9:["ytp-iv-video-content"]});g.A(this,this.J);f=this.createElement({L:"div",B:"video-annotations"});
f.appendChild(this.WS);this.J.element.appendChild(f);this.sL()?this.load():this.player.Y("web_fix_annotations")&&(this.V=()=>{this.loaded||this.HS()||!this.sL()||(huM(this),this.load())},this.player.addEventListener("videodatachange",this.V));
const e=this.createElement({L:"style"});(g.Jj("HEAD")[0]||document.body).appendChild(e);this.addOnDisposeCallback(()=>{g.tb(e)});
if(f=e.sheet){for(const B of tye)f.insertRule(B,0);for(const B of HHL)f.insertRule(B,0)}}gZ(f,e){if(!N0e(this.player.S().playerStyle))return null;switch(f){case "loadCustomAnnotationsXml":return(f=g.eF(e))&&G4(this,f),!0;case "removeCustomAnnotationById":return e&&this.C&&(mH(this.C,e),Bz(this.player)),!0}return null}getOptions(){return N0e(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}sL(){const f=this.player.getVideoData(),e=f.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return f.AF||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.Y("web_fix_annotations")?xbg(this)?e?.isWatermarkEnforced===!0?!0:e?.isAnnotationsEnabled??!1:!1:xbg(this)}N(){if(this.J){var f=this.player.AL().getVideoContentRect(!0);g.xC(this.J.element,f.width,f.height);g.Em(this.J.element,f.left,f.top)}if(this.C){var e=this.player.jh();f=this.C;e=e.width;g.h(f.V,"iv-drawer-small",e<=426);g.h(f.V,"iv-drawer-big",e>=1280)}}eI(f){WBg(this,f.state);f.state.C(2)&&(this.O4()&&this.fV()&&this.player.getPresentingPlayerType()!==
2&&this.Je(!1),this.e5(!1))}load(){super.load();WBg(this,this.player.getPlayerStateObject());this.loadNumber++;const f=this.player.getVideoData();PPV(this,f);g.qX(this.player,this.J.element,4);this.N();var e=g.S_(f);const B=f.jX();if(this.player.Y("web_fix_annotations")){if(e&&(e.featuredChannel&&erV(this,e.featuredChannel,e.annotationId||"branding",f.videoId||null,f.eventId||null),e=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,e?.isWatermarkEnforced&&!e?.isAnnotationsEnabled))return;
B&&xd(this,B)}else B&&xd(this,B),e&&e.featuredChannel&&erV(this,e.featuredChannel,e.annotationId||"branding",f.videoId||null,f.eventId||null);this.RM=g.x2("ytp-cards-button",this.player.getRootNode());f.y8()&&ysH(this,f)}onVideoDataChange(){}unload(){this.player.sK("annotations_module");for(const f of Object.keys(this.U))this.U[f].destroy();this.K=null;this.C&&(this.C.destroy(),this.C=null,Bz(this.player));this.A=!1;this.X&&(this.X.abort(),this.X=null);this.Ed=!1;this.U={};this.G.hide();super.unload();
this.J.detach();huM(this)}cS(f){f===this.player.getVideoData().videoId&&(this.loaded?iEx(this):this.load())}O4(){return this.C?.isAvailable()||this.Ed}fV(){return!!this.C&&this.C.J}Je(f,e=!1,B){this.O4();this.C&&(f?B?NN(this.C,B,e):NN(this.C,"YOUTUBE_DRAWER_AUTO_OPEN",e):g4(this.C))}e5(f,e){this.player.publish(f?"cardsteasershow":"cardsteaserhide",e)}bY(){this.player.S().PS.unsubscribe("vast_info_card_add",this.cS,this);g.$i(this.player.getRootNode(),g.y1.IV_DRAWER_OPEN);var f=this.Cq,e=g.ul;for(let B=
0,n=f.length;B<n;B++)e.lK(f[B]);this.Cq.length=0;super.bY()}createElement(f){f=new g.y(f);g.A(this,f);return f.element}});g.cO("creatorendscreen",doL);})(_yt_player);
