(function(g){var window=this;'use strict';var ZHL=async function(f,e,B){f.G=g.QY(e,B)},Wz=function(f){f.isActive()||f.start()},s4=function(f,e){return e?f.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Rru=function(f){return g.yQ(f)||f.Y("web_enable_caption_language_preference_stickiness")},K$g=function(f,e){const B=new g.op;
B.languageCode=f.languageCode;B.languageName=f.languageName;B.name=f.name;B.displayName=f.displayName;B.kind=f.kind;B.isDefault=!1;B.C=f.C;B.isTranslateable=f.isTranslateable;B.vssId=f.vssId;B.url=f.url;B.translationLanguage=e;f.xtags&&(B.xtags=f.xtags);f.captionId&&(B.captionId=f.captionId);return B},qEH=async function(f,e){f=f+"|"+e;
e=await g.f8();if(!e)throw g.uo("gct");return(await g.TH(e)).get("captions",f)},zrG=function(f,e,B){qEH(f,e).then(n=>{n&&B(n.trackData,new g.op(n.metadata))})},XJ=function(f){if(!am2.test(f))throw Error("'"+f+"' is not a valid hex color");
f.length==4&&(f=f.replace(phF,"#$1$1$2$2$3$3"));f=f.toLowerCase();f=parseInt(f.slice(1),16);return[f>>16,f>>8&255,f&255]},cjH=function(){var f={};
let e="suggest_correction"in g.wv?g.wv.suggest_correction:"Edit caption";e=e||"";for(let B in f){const n=()=>String(f[B]);
e=e.replace(new RegExp("\\$\\{"+B+"\\}","gi"),n);e=e.replace(new RegExp("\\$"+B,"gi"),n)}return e},yk=function(){return g.IB("yt-player-caption-display-settings")},YEg=function(f,e){let B=g.ax(f.segments,e);
B>=0||B<0&&(-B-1)%2===1||(B=-B-1,B>0&&e-f.segments[B-1]===1&&B<f.segments.length&&f.segments[B]-e===1?(g.LF(f.segments,B),g.LF(f.segments,B-1)):B>0&&e-f.segments[B-1]===1?f.segments[B-1]=e:B<f.segments.length&&f.segments[B]-e===1?f.segments[B]=e:(g.Rx(f.segments,B,0,e),g.Rx(f.segments,B+1,0,e)))},AjI=function(f){return f.C&&f.C.W?f.C.W+f.player.gA()<f.player.getCurrentTime():!1},jAe=function(f,e){if(f.policy.To&&f.player.F3()){var B=g.ar(e,f.policy,{});
B.set("pot",f.player.F3());B=B.Dw()}else B=g.ar(e,f.policy,{}).Dw();const n={format:"RAW",withCredentials:!0};if(f.policy.PS){n.method="POST";const d=e.V;d&&Object.keys(d).length>0?n.postBody=g.zy(d,g.zF):n.postBody=(0,g.iY)([120,0])}f.W&&(n.responseType="arraybuffer");let r=++f.Cq;const L=(0,g.T)();f.G=g.sV(B,n,3,100,-1,d=>{d.errorCode==="net.timeout"&&f.player.ri("capnt",{rn:r++})}).then(d=>{if(f.policy.Fw&&r%100===1){var t=(0,g.T)();
f.player.ri("caprsp",{rn:r,ms:t-L,kb:(d.xhr.responseText.length/1024).toFixed()})}a:{d=d.xhr;f.HS();if(f.J){var H=!(f.W?d.response:d.responseText)||d.status>=400;if(t=g.lkg(d)){d=g.ar(f.J,f.policy,{});f.J.xa(d,t);jAe(f,f.J);break a}H?f.player.ri("capfail",{status:d.status}):(g.cu("fcb_r",(0,g.T)(),f.player.getVideoData()?.Ed||""),t=f.J.T6[0],H=t.YA,f.K!=null&&f.U!==H&&(f.W?f.K(d.response,(t.startTime+f.player.gA())*1E3):f.K(d.responseText,(t.startTime+f.player.gA())*1E3),f.U=H))}f.J=null;f.G=null}}).wT(d=>
{f.J=null;
f.G=null;f.player.ri("capfail",{rn:r,status:d.xhr?.status})});
f.J=e;YEg(f.V,f.J.T6[0].YA)},OHM=function(f,e){return e!=null&&e in f.G.C?f.G.C[e]:null},o2g=function(f,e,B){const n=[];
for(const r in f.G.C){if(!f.G.C.hasOwnProperty(r))continue;const L=f.G.C[r];if(g.j9(L,B||null)){const d=L.info.captionTrack;d&&d.languageCode===e&&n.push(L)}}return n.length?n[0]:null},lmB=function(f,e){const B=[];
for(const r in f.G.C){if(!f.G.C.hasOwnProperty(r))continue;var n=f.G.C[r];if(g.j9(n,e||null)){let L=n.info.id,d=L,t=`.${L}`,H="",k="";if(n=n.info.captionTrack)L=n.languageCode,d=n.displayName,t=n.vssId,H=n.kind,k=n.id;else{{n=L;let C=g.Hkd.get(n);C==null&&(C=VyB[n]||VyB[n.replace(/-/g,"_")],g.Hkd.set(n,C));n=C}d=n||d}B.push(new g.op({id:r,languageCode:L,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:t,kind:H,captionId:k}))}}return B},ulx=function(f,e,B,n){let r=e/360*16;
e>=f&&(f=640,n>B*1.3&&(f=480),r=B/f*16);return r},F$H=function(f){let e=1+.25*(f.fontSizeIncrement||0);
if(f.offset===0||f.offset===2)e*=.8;return e},mox=function(f,e){let B="vertical-rl";
f.C.RE===1&&(B="vertical-lr");g.db&&(B=B==="vertical-lr"?"tb-lr":"tb-rl");g.uc(e,"-o-writing-mode",B);g.uc(e,"-webkit-writing-mode",B);g.uc(e,"writing-mode",B);g.uc(e,"text-orientation","upright");g.PW(e,"ytp-vertical-caption");f.G.params.Z0===3&&(g.uc(e,"text-orientation",""),g.uc(e,"transform","rotate(180deg)"))},UoT=function(f,e){const B={};
var n=e.background?e.background:f.C.o1.background;if(e.backgroundOpacity!=null||e.background){var r=e.backgroundOpacity!=null?e.backgroundOpacity:f.C.o1.backgroundOpacity;n=XJ(n);B.background="rgba("+n[0]+","+n[1]+","+n[2]+","+r+")";f.Mk&&(B["box-decoration-break"]="clone",B["border-radius"]=`${f.MC/8}px`)}if(e.fontSizeIncrement!=null||e.offset!=null)B["font-size"]=`${f.BS*F$H(e)}px`;n=1;r=e.color||f.C.o1.color;if(e.color||e.textOpacity!=null)r=XJ(r),n=e.textOpacity==null?f.C.o1.textOpacity:e.textOpacity,
r="rgba("+r[0]+","+r[1]+","+r[2]+","+n+")",B.color=r,B.fill=r;var L=e.charEdgeStyle;L===0&&(L=void 0);if(L){r=`rgba(34, 34, 34, ${n})`;let H=`rgba(204, 204, 204, ${n})`;e.xn&&(H=r=e.xn);const k=f.BS/16/2,C=Math.max(k,1);var d=Math.max(2*k,1),t=Math.max(3*k,1);const w=Math.max(5*k,1);n=[];switch(L){case 4:for(;t<=w;t+=k)n.push(`${d}px ${d}px ${t}px ${r}`);break;case 1:d=window.devicePixelRatio>=2?.5:1;for(L=C;L<=t;L+=d)n.push(`${L}px ${L}px ${r}`);break;case 2:n.push(`${C}px ${C}px ${H}`);n.push(`-${C}px -${C}px ${r}`);
break;case 3:for(t=0;t<5;t++)n.push(`0 0 ${d}px ${r}`)}B["text-shadow"]=n.join(", ")}r="";switch(e.fontFamily){case 1:r='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:r='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:r='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:r='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:r='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:r=g.Cs()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:r='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}r&&(B["font-family"]=r);r=e.offset;r==null&&(r=f.C.o1.offset);switch(r){case 0:B["vertical-align"]="sub";break;case 2:B["vertical-align"]="super"}e.fontFamily===7&&(B["font-variant"]="small-caps");e.bold&&(B["font-weight"]="bold");e.italic&&(B["font-style"]="italic");e.underline&&
(B["text-decoration"]="underline");e.Of&&(B.visibility="hidden");e.Si===1&&f.J&&(B["text-combine-upright"]="all",B["text-orientation"]="mixed",r=g.tq||g.oN,f.G.params.Z0===3?B.transform=r?"rotate(90deg)":"rotate(180deg)":r&&(B.transform="rotate(-90deg)"));if(e.textEmphasis===1||e.textEmphasis===2||e.textEmphasis===3||e.textEmphasis===4||e.textEmphasis===5)if(g.tq)B["font-weight"]="bold";else switch(B["text-emphasis-style"]="filled circle",B["text-emphasis-color"]="currentcolor",B["webkit-text-emphasis"]=
"filled circle",e.textEmphasis){case 4:case 3:B["text-emphasis-position"]="under left";B["webkit-text-emphasis-position"]="under left";break;case 5:case 2:B["text-emphasis-position"]="over right",B["webkit-text-emphasis-position"]="over right"}return B},Pz=function(f){f=f.split("px");
return f.length>0?(f=Number(f[0]))?f:0:0},g2g=function(f,e,B){f.WS=f.WS||!!B;
const n={};Object.assign(n,f.C.o1);Object.assign(n,B||e.C);Object.assign(n,f.EE.o1);(B=!f.X)&&NrG(f);let r=f.PS&&f.Lq&&g.MT(n,f.Lq)?f.PS:hre(f,n);const L=typeof e.text==="string",d=L?e.text.split("\n"):[e.text];for(let H=0;H<d.length;H++){var t=H>0||!e.append;const k=d[H];t&&!B?(NrG(f),r=hre(f,n)):t&&B&&(B=!1);k&&(r.appendChild(L?g.nC(k):k),L||k.tagName!=="RUBY"||k.childElementCount!==4||g.tq||!g.Um(k.children[2],"text-emphasis")||(t=f.J?"padding-right":"padding-top",g.Um(k.children[2],"text-emphasis-position")&&
(t=f.J?"padding-left":"padding-bottom"),g.IA?g.uc(r,t,"1em"):g.uc(r,t,"0.5em")))}f.Lq=n;f.PS=r;f.U.push(e)},NrG=function(f){f.X=g.BN("SPAN");
g.uc(f.X,{display:"block"});g.PW(f.X,"caption-visual-line");f.V.appendChild(f.X)},hre=function(f,e){const B=g.BN("SPAN");
g.uc(B,{display:"inline-block","white-space":"pre-wrap"});g.uc(B,UoT(f,e));B.classList.add("ytp-caption-segment");f.X.appendChild(B);B.previousElementSibling&&(g.uc(B.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.uc(B,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return B},E2B=function(f,e,B){if(f===255&&e===255||!f&&!e)return{W$:f,
N6:e,result:0};f=SEM[f];e=SEM[e];if(f&128){var n;if(n=!(e&128))n=e,n=B.H4()&&B.N6===n;if(n)return{W$:f,N6:e,result:1}}else if(e&128&&1<=f&&f<=31)return{W$:f,N6:e,result:2};return{W$:f,N6:e,result:3}},TrM=function(f,e,B,n){e===255&&B===255||!e&&!B?(++f.J===45&&f.reset(),f.V.G.clear(),f.W.G.clear()):(f.J=0,QAB(f.V,e,B,n))},Doe=function(f,e){f.C.sort((B,n)=>{const r=B.time-n.time;
return r===0?B.order-n.order:r});
for(const B of f.C)f.time=B.time,B.type===0?TrM(f,B.GB,B.bH,e):B.type===1&&f.G&496&&QAB(f.W,B.GB,B.bH,e);f.C.length=0},W$g=function(f,e){switch(f){case 0:return Jje[(e&127)-32];
case 1:return MyH[e&15];case 2:return Gee[e&31];case 3:return xoe[e&31]}return 0},Ik=function(f,e){if(f.style.type===3){var B=0,n=0,r=f.W.time+0,L="",d="",t=r;
for(var H=1;H<=15;++H){var k=!1;for(var C=n?n:1;C<=32;++C){var w=f.J[H][C];if(w.C!==0){B===0&&(B=H,n=C);k=String.fromCharCode(w.C);var v=w.timestamp;v<r&&(r=v);w.timestamp=t;d&&(L+=d,d="");L+=k;k=!0}if((w.C===0||C===32)&&k){d="\n";break}else if(n&&!k)break}if(B&&!k)break}L&&e.V(B,n,r,t,L)}else for(n=B=0,L=r=f.W.time+0,d=1;d<=15;++d)for(t="",H=1;H<=32;++H)if(C=f.J[d][H],w=C.C,w!==0&&(B===0&&(B=d,n=H),k=String.fromCharCode(w),v=C.timestamp,v<=r&&(r=v),t+=k,C.reset()),H===32||w===0)t&&e.V(B,n,r,L,t),
r=L,t="",n=B=0},$d=function(f){return f.J[f.row][f.G]},iV=function(f,e,B){e>=2&&f.G>1&&(--f.G,$d(f).C=0);
const n=$d(f);n.timestamp=f.W.time+0;n.C=W$g(e,B);f.G<32&&f.G++},sAV=function(f,e,B,n){for(let d=0;d<n;d++)for(let t=0;t<=32;t++){var r=f.J[e+d][t],L=f.J[B+d][t];
r.C=L.C;r.timestamp=L.timestamp}},fV=function(f,e,B){for(let n=0;n<B;n++)for(let r=0;r<=32;r++)f.J[e+n][r].reset()},ei=function(f){f.row=f.C>0?f.C:1;
f.G=1;fV(f,0,15)},Xhe=function(f){f.style.set(1);
f.C=f.V;f.C.C=0;f.C.style=f.style;f.J.mode=1<<f.C.V},Ba=function(f,e,B){const n=f.G;
let r=!1;switch(f.style.get()){case 4:case 1:case 2:f.style.get()===4&&n.C>0||(Ik(n,B),ei(f.G),ei(f.V),n.row=15,n.C=e,r=!0)}f.style.set(3);f.C=n;f.C.style=f.style;f.J.mode=1<<n.V;r?n.G=1:n.C!==e&&(n.C>e?(Ik(n,B),fV(n,n.row-n.C,e)):n.row<e&&(e=n.C),n.C=e)},yjg=function(f){f.style.set(4);
f.C=f.text;f.C.style=f.style;f.J.mode=1<<f.C.V},QAB=function(f,e,B,n){f.G.update();
e=E2B(e,B,f.G);switch(e.result){case 0:return;case 1:case 2:return}var r=e.W$;e=e.N6;if(32<=r||!r)f.C.mode&f.C.G&&(B=r,B&128&&(B=127),e&128&&(e=127),f=f.V.C,B&96&&iV(f,0,B),e&96&&iV(f,0,e),B!==0&&e!==0&&f.style.type===3&&Ik(f,n));else if(r&16)a:if(!f.G.matches(r,e)&&(B=f.G,B.W$=r,B.N6=e,B.state=2,B=r&8?f.U:f.J,f.V=B,f.C.mode=1<<(f.W<<2)+(B.W<<1)+(B.style.type===4?1:0),(f.C.mode|1<<(f.W<<2)+(B.W<<1)+(B.style.type!==4?1:0))&f.C.G))if(e&64){n=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(r&7)<<1|e>>5&1];
f=e&16?((e&14)>>1)*4:0;e=B.C;switch(B.style.get()){case 4:n=e.row;break;case 3:if(n!==e.row){if(n<e.C&&(n=e.C,n===e.row))break;var L=1+e.row-e.C;const d=1+n-e.C;sAV(e,d,L,e.C);B=L;r=e.C;d<L?(L=d+r-L,L>0&&(B+=L,r-=L)):(L=L+r-d,L>0&&(r-=L));fV(e,B,r)}}e.row=n;e.G=f+1}else switch(r&7){case 1:switch(e&112){case 32:iV(B.C,0,32);break a;case 48:e===57?(n=B.C,$d(n).C=0,n.G<32&&n.G++):iV(B.C,1,e&15)}break;case 2:e&32&&iV(B.C,2,e&31);break;case 3:e&32&&iV(B.C,3,e&31);break;case 4:case 5:if(32<=e&&e<=47)switch(e){case 32:Xhe(B);
break;case 33:n=B.C;n.G>1&&(--n.G,$d(n).C=0);break;case 36:n=B.C;f=$d(n);for(e=0;e<=15;e++)for(B=0;B<=32;B++)if(n.J[e][B]===f){for(;B<=32;B++)n.J[e][B].reset();break}break;case 37:Ba(B,2,n);break;case 38:Ba(B,3,n);break;case 39:Ba(B,4,n);break;case 40:iV(B.C,0,32);break;case 41:n=B;n.style.set(2);n.C=n.G;n.C.C=0;n.C.style=n.style;n.J.mode=1<<n.C.V;break;case 42:n=B;f=n.text;f.C=15;f.style.set(4);ei(f);yjg(n);break;case 43:yjg(B);break;case 44:f=B;e=f.G;switch(f.style.get()){case 1:case 2:case 3:Ik(e,
n)}fV(e,0,15);break;case 45:b:{e=B;f=e.C;switch(e.style.get()){default:case 2:case 1:break b;case 4:if(f.row<15){++f.row;f.G=1;break b}break;case 3:}f.C<2&&(f.C=2,f.row<f.C&&(f.row=f.C));e=f.row-f.C+1;Ik(f,n);sAV(f,e,e+1,f.C-1);fV(f,f.row,1)}break;case 46:fV(B.V,0,15);break;case 47:f=B,Ik(f.G,n),f.V.updateTime(f.J.time+0),n=f.V,f.V=f.G,f.G=n,Xhe(f)}break;case 7:switch(e){case 33:case 34:case 35:n=B.C,(n.G+=e&3)>32&&(n.G=32)}}},ImT=function(f,e,B,n,r,L,d){var t=L[0];
let H=d[t.getAttribute("p")];if(H.oM===1){var k=L[1],C=L[2];L=L[3];t.getAttribute("t");k.getAttribute("t");C.getAttribute("t");L.getAttribute("t");t.getAttribute("p");k.getAttribute("p");L.getAttribute("p");d=d[C.getAttribute("p")];t=PNB(t.textContent,k.textContent,C.textContent,L.textContent,d);return new nV(f,e,r,B,t,n,H)}switch(H.oM){case 9:case 10:H.textEmphasis=1;break;case 11:H.textEmphasis=2;break;case 12:H.textEmphasis=3;break;case 13:H.textEmphasis=4;break;case 14:H.textEmphasis=5}return new nV(f,
e,r,B,t.textContent||"",n,H)},PNB=function(f,e,B,n,r){var L=g.Cs();
const d=L?g.BN("DIV"):g.BN("RUBY"),t=g.BN("SPAN");t.textContent=f;d.appendChild(t);f=L?g.BN("DIV"):g.BN("RP");f.textContent=e;d.appendChild(f);e=L?g.BN("DIV"):g.BN("RT");e.textContent=B;d.appendChild(e);B=r.oM;if(B===10||B===11||B===12||B===13||B===14)if(g.uc(e,"text-emphasis-style","filled circle"),g.uc(e,"text-emphasis-color","currentcolor"),g.uc(e,"webkit-text-emphasis","filled circle"),r.oM===11||r.oM===13)g.uc(e,"webkit-text-emphasis-position","under left"),g.uc(e,"text-emphasis-position","under left");
B=!0;if(r.oM===4||r.oM===7||r.oM===12||r.oM===14)g.uc(d,"ruby-position","over"),g.uc(d,"-webkit-ruby-position","before");else if(r.oM===5||r.oM===6||r.oM===11||r.oM===13)g.uc(d,"ruby-position","under"),g.uc(d,"-webkit-ruby-position","after"),B=!1;r=L?g.BN("DIV"):g.BN("RP");r.textContent=n;d.appendChild(r);L&&(n=B,g.uc(d,{display:"inline-block",position:"relative"}),L=d.firstElementChild.nextElementSibling,g.uc(L,"display","none"),L=L.nextElementSibling,g.uc(L,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.uc(d.lastElementChild,"display","none"),n?(g.uc(d,"padding-top","0.6em"),g.uc(L,"top","0")):(g.uc(d,"padding-bottom","0.6em"),g.uc(L,"bottom","0")));return d},$oF=function(f){const e="_"+r9++;
return new LV(0,0x8000000000000,0,e,f)},d9=function(f,e){f=f.getAttribute(e);
if(f!=null)return Number(f)},tP=function(f,e){f=f.getAttribute(e);
if(f!=null)return f==="1"},Ha=function(f,e){f=d9(f,e);
return f!==void 0?f:null},CV=function(f,e){f=f.getAttribute(e);
if(f!=null)return kN.test(f),f},iHu=function(f,e){const B={},n=e.getAttribute("ws");
Object.assign(B,n?f.N[n]:f.V);f=Ha(e,"mh");f!=null&&(B.HN=f);f=Ha(e,"ju");f!=null&&(B.textAlign=f);f=Ha(e,"pd");f!=null&&(B.Z0=f);f=Ha(e,"sd");f!=null&&(B.RE=f);f=CV(e,"wfc");f!=null&&(B.windowColor=f);e=d9(e,"wfo");e!==void 0&&(B.windowOpacity=e/255);return B},fSV=function(f,e){const B={},n=e.getAttribute("wp");
n&&Object.assign(B,f.K[n]);f=Ha(e,"ap");f!=null&&(B.Kj=f);f=d9(e,"cc");f!=null&&(B.zL=f);f=d9(e,"ah");f!=null&&(B.CA=f);f=d9(e,"rc");f!=null&&(B.b4=f);e=d9(e,"av");e!=null&&(B.i8=e);return B},egV=function(f,e,B,n){let r={};
Object.assign(r,fSV(f,e));Object.assign(r,iHu(f,e));n?g.MT(r,f.V)?(n=f.W,r=f.V):n="_"+r9++:n=e.getAttribute("id")||"_"+r9++;f=d9(e,"t")+B;e=d9(e,"d")||0x8000000000000;if(r.Z0===2||r.Z0===3)B=r.b4,r.b4=r.zL,r.zL=B;return new LV(f,e,0,n,r)},w9=function(f){f=g.ch(Math.round(f),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-f.length)+f},Bwx=function(f,e,B,n,r){n===0&&(n=0x8000000000000);
const L={};e.wpWinPosId&&Object.assign(L,f.V.get(e.wpWinPosId));e.wsWinStyleId&&Object.assign(L,f.W.get(e.wsWinStyleId));f=e.rcRowCount;f!==void 0&&(L.b4=f);e=e.ccColCount;e!==void 0&&(L.zL=e);if(L.Z0===2||L.Z0===3)e=L.b4,L.b4=L.zL,L.zL=e;return new LV(B,n,0,r,L)},va=function(f){const e=f.byteOffset;
f.byteOffset+=1;return f.C.getUint8(e)},bk=function(f){const e=f.byteOffset;
f.byteOffset+=4;return f.C.getUint32(e)},LdH=function(f){if(typeof f==="string")return!1;
f=new nCM(f,0);return rbT(f)},rbT=function(f){if(!(f.byteOffset<f.C.byteLength)||bk(f)!==1380139777)return!1;
f.version=va(f);if(f.version>1)return!1;va(f);va(f);va(f);return!0},dVe=function(f,e){if(!e)return"";
f.J&&f.G.params.RE!==1&&(e*=-1);return`translate${f.J?"X":"Y"}(${e}px)`},tAx=function(f){f.cS=Array.from(f.element.getElementsByClassName("caption-visual-line"));
for(var e=f.G.params.b4,B=0,n=0,r=f.cS.length-1;B<e&&r>-1;){var L=f.cS[r];n+=f.J?L.offsetWidth:L.offsetHeight;B++;r--}f.N=n;e=Math;B=e.max;isNaN(f.eI)&&((n=f.C.zL)?(r=g.BN("SPAN"),g.kC(r,"\u2013".repeat(n)),g.uc(r,UoT(f,f.C.o1)),f.V.appendChild(r),f.eI=r.offsetWidth,f.V.removeChild(r)):f.eI=0);n=f.V;f.A=B.call(e,f.eI,f.Q3,(f.J?n.offsetHeight:n.offsetWidth)+1)},HCe=function(f,e){tAx(f);
var B=f.cS.reduce((n,r)=>(f.J?r.offsetWidth:r.offsetHeight)+n,0);
B=f.N-B;if(B!==f.uY){const n=B>0&&f.uY===0,r=B<f.uY;e||isNaN(B)||n||!r||(g.PW(f.element,"ytp-rollup-mode"),f.D(f.element,"transitionend",f.Fl));g.uc(f.V,"transform",dVe(f,B));f.uY=B}tAx(f)},CcG=function(f,e){f.C=(B,n)=>{if(B.info.J){var r=B;
if(f.rU.length>0){for(r=f.rU.shift();f.rU.length>0;)r=r.U(f.rU.shift());r=r.U(B)}if(r){B=r;try{var L=g.m6(B)*1E3}catch(b){L=B.info.startTime*1E3}try{var d=g.plH(B)*1E3}catch(b){d=B.info.duration*1E3}if(L<0||d<0)L<0&&(L=B.info.startTime*1E3),d<0&&(d=B.info.duration*1E3);B.info.startTime=L/1E3;B.info.V=L/1E3;B.info.duration=d/1E3;B.info.K=d/1E3;const {formatId:t,YA:H,startTimeMs:k,durationMs:C}=f.u0(r);L={formatId:t,startTimeMs:k,durationMs:C,Ie:H,qq:H};d=ktB(f.GD,L.startTimeMs);const w=(B=d>=0?f.GD[d]:
null)?B.startTimeMs+B.durationMs:0,v=L.startTimeMs+L.durationMs;!B||L.startTimeMs-w>f.G?f.GD.splice(d+1,0,L):(B.durationMs=Math.max(w,v)-B.startTimeMs,B.qq=Math.max(B.qq,L.qq));n(f.GD);L=g.lJ(r);n=f.J;L=L.buffer.slice(L.byteOffset,L.byteLength+L.byteOffset);r=r.info.V;n.Ed?n.K==null?g.Vj(n.logger,350058965,"Null loaded track meta data at captions data received"):e.v3(L,n.K,r*1E3):g.Vj(n.logger,350058965,"Null Representation at captions data received")}else g.Vj(f.logger,350058965,"Empty slice")}else f.rU.push(B)};
f.Z.addEventListener("sabrCaptionsDataLoaded",f.C)},ktB=function(f,e){f=g.ax(f,{startTimeMs:e},(B,n)=>B.startTimeMs-n.startTimeMs);
return f>=0?f:-f-2},wNe=function(f,e){if(!g.MbC(f)||f.C!=null&&g.AW(e,f.C)&&f.C.C.rawcc!=null)return!1;
e=!!f.C&&f.C.isManifestless&&Object.values(f.C.C).some(B=>g.j9(B,"386"));
f=!!f.C&&!f.C.isManifestless&&g.s5C(f.C);return e||f},vCe=function(f,e,B){const n=[];
for(const r in f.G.C){if(!f.G.C.hasOwnProperty(r))continue;const L=f.G.C[r];if(g.j9(L,B||null)){const d=L.info.captionTrack;d&&d.languageCode===e&&n.push(L)}}return n.length?n[0]:null},bCT=function(f,e){const B=[];
for(const r in f.G.C){if(!f.G.C.hasOwnProperty(r))continue;var n=f.G.C[r];if(g.j9(n,e||null)){let L=n.info.id,d=L,t=`.${L}`,H="",k="";if(n=n.info.captionTrack)L=n.languageCode,d=n.displayName,t=n.vssId,H=n.kind,k=n.id;B.push(new g.op({id:r,languageCode:L,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:t,kind:H,captionId:k}))}}return B},RgB=function(f){const e=ZCM.length;
if(f.byteLength<e)return!1;f=new Uint8Array(f,0,e);for(let B=0;B<e;B++)if(ZCM[B]!==f[B])return!1;return!0},Zz=function(f){f=f.split(":");
let e=0;for(const B of f)e=e*60+Number(B);return e*1E3},Kde=function(f,e,B,n){n=Object.assign({HN:0},n);
return new LV(f,e,B,"_"+r9++,n)},qmg=function(f,e,B,n,r,L,d,t,H){switch(d.tagName){case "b":t.bold=!0;
break;case "i":t.italic=!0;break;case "u":t.underline=!0}for(let C=0;C<d.childNodes.length;C++){var k=d.childNodes[C];if(k.nodeType===3)k=new nV(e,B,n,r.id,k.nodeValue,L||C>0,g.TL(t)?void 0:t),H.push(k),r.C.push(k);else{const w={};Object.assign(w,t);qmg(f,e,B,n,r,!0,k,w,H)}}},aSI=function(f,e,B){if(typeof e==="string"||LdH(e))return[{trackData:e,
V0:B}];if(typeof e==="string"&&e.substring(0,6)==="WEBVTT"||typeof e!=="string"&&RgB(e))return[{trackData:e,V0:B}];const n=new DataView(e);if(n.byteLength<=8||n.getUint32(4)!==1718909296)return[];var r=g.b00(n);if(f.fh&&r){var L=g.r$0(r),d=g.LjC(r);r=r.pj;L&&r&&f.fh.pv(r,L,d)}f=g.mF(n,1835295092);if(!f||!f.length||!f[0].size)return[];L=[];for(d=0;d<f.length;d++)r=f[d],r=new Uint8Array(e,r.dataOffset,r.size-(r.dataOffset-r.offset)),r=g.kq(r),L.push({trackData:r,V0:B+d*1E3});zge(n,L,B);return L=L.filter(t=>
!!t.trackData)},cbB=function(f,e,B){f.C||(f.C=new pNF);
f=f.C.J(e,B);Math.random()<.01&&g.Yv(Error("Deprecated subtitles format in web player: WebVTT"));return f},zge=function(f,e,B){var n=g.Vw(f,0,1836476516);
let r=9E4;n&&(r=g.ln(n)||9E4);n=0;const L=g.mF(f,1836019558);for(let t=0;t<L.length;t++){var d=L[t];t<e.length&&(d=g.Vw(f,d.dataOffset,1953653094))&&(d=g.Vw(f,d.dataOffset,1952867444))&&(d=g.FI(d)/r*1E3,t===0&&(n=d),e[t].V0=d-n+B||B*t*1E3)}},Ymx=function(f){const e={};
if(f=g.p3(f))e.lang=f,g.u65.test(f)&&(e.Z0=1);return e},Abe=function(f){const e=!!f.Z.aC()?.cS();
return f.J==="HLS"&&e?!0:f.BS&&e&&f.J!=="LIVE"&&f.J!=="SABR_LIVE"},KV=function(f,e,B=!1){const n=RX.o1;
f.W={};Object.assign(f.W,RX);f.W.o1={};Object.assign(f.W.o1,n);f.U={o1:{}};var r=e.backgroundOverride?f.U:f.W,L=e.background||n.background;kN.test(L);r.o1.background=L;r=e.colorOverride?f.U:f.W;L=e.color||n.color;kN.test(L);r.o1.color=L;r=e.windowColorOverride?f.U:f.W;L=e.windowColor||RX.windowColor;kN.test(L);r.windowColor=L;r=e.backgroundOpacityOverride?f.U:f.W;L=e.backgroundOpacity;L==null&&(L=n.backgroundOpacity);r.o1.backgroundOpacity=L;r=e.fontSizeIncrementOverride?f.U:f.W;L=e.fontSizeIncrement;
L==null&&(L=n.fontSizeIncrement);r.o1.fontSizeIncrement=L;L=e.fontStyleOverride?f.U:f.W;r=e.fontStyle;r==null&&(r=n.bold&&n.italic?3:n.bold?1:n.italic?2:0);L=L.o1;switch(r){case 1:L.bold=!0;delete L.italic;break;case 2:delete L.bold;L.italic=!0;break;case 3:L.bold=!0;L.italic=!0;break;default:delete L.bold,delete L.italic}r=e.textOpacityOverride?f.U:f.W;L=e.textOpacity;L==null&&(L=n.textOpacity);r.o1.textOpacity=L;r=e.windowOpacityOverride?f.U:f.W;L=e.windowOpacity;L==null&&(L=RX.windowOpacity);r.windowOpacity=
L;r=e.charEdgeStyleOverride?f.U:f.W;L=e.charEdgeStyle;L==null&&(L=n.charEdgeStyle);r.o1.charEdgeStyle=L;r=e.fontFamilyOverride?f.U:f.W;L=e.fontFamily;L==null&&(L=n.fontFamily);r.o1.fontFamily=L;f.loaded&&f.IA();B&&g.yT("yt-player-caption-display-settings",e,2592E3)},qF=function(f,e,B){e&&!f.Ed?(e=$oF({Z0:0,
lang:"en"}),f.Ed=[e,new nV(e.start,e.end-e.start,0,e.id,B??"Captions look like this")],f.player.AI(f.Ed)):!e&&f.Ed&&(jYV(f,f.Ed),f.Ed=null)},OCI=function(f){if(!f.Z.isInline())return g.IB("yt-player-sticky-caption")},z9=function(f){let e=void 0;
const B=g.ni().jI(65);if(g.yQ(f.Ta)&&B!=null){if(OCI(f)!=null)return!1;e=!B}return e},oCe=function(f){if(f.Ta.Dk===1||f.videoData.zQ===1||g.FQ(f.videoData,"yt:cc")==="alwayson")return!0;
let e;f.videoData.captionTracks.length&&(e=f.getAudioTrack().G);if(f.Ta.Dk===2){if(g.yQ(f.Ta))var B=OCI(f);else if(f.storage)try{B=f.storage.get("module-enabled")}catch(r){f.storage.remove("module-enabled")}else B=null;if(B!=null)return!!B}B=s4(f.player.getAudioTrack(),g.yQ(f.Ta));const n=g.FQ(f.videoData,"yt:cc");if(z9(f)===void 0){if(B==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return n?n==="on":!0;if(B==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return n==="on"}else return n==="on";return e==="ON"||
g.FQ(f.videoData,"yt:cc")==="on"},aX=function(f,e=!1){if(f.C&&!e||!f.videoData.captionTracks.length)return!1;
f=f.getAudioTrack();return!!f.C||f.G==="FORCED_ON"},VAe=function(f,e){if(f.C){var B=f.Z.aC().V3().textTracks,n=null;
f.J==="HLS"?n=f.C.getId():n=f.C.toString();for(let L=0;L<B.length;L++){var r=B[L];r.id===n&&(e?r.mode!=="showing"&&(r.mode="showing",r=f.C,f.Jq(r,!!r,pV(f)?"g":f.X?"m":"s")):r.mode==="showing"&&(r.mode="disabled"))}}},pV=function(f){const e=ca(f);
return!!e&&f.C===e},lSu=function(f,e){if(f.J==="HLS")return!1;
g.Tk(f.videoData)&&(e=!0);e||(e=f.J==="TTS"?!1:f.J==="INNERTUBE"?!1:!0);return e||f.Ta.Y("web_deprecate_always_includes_asr_setting")&&g.yQ(f.Ta)?!0:!!g.ni().jI(66)},ca=function(f){return f.N&&f.N.C},YN=function(f,e){if(!f.G)return null;
if(f.N&&f.N.V)return f.N.V;e=lSu(f,e);e=g.BO(f.G.C,e);let B=null;if(Rru(f.Ta)){var n=f.Z.isInline()?void 0:g.IB("yt-player-caption-sticky-language");var r=[n,f.videoData.captionsLanguagePreference,f.Ta.captionsLanguagePreference,g.FQ(f.videoData,"yt:cc_default_lang")];let t=!1;for(let H=0;H<r.length;H++){const k=r[H];if(k){t=!0;for(var L=0;L<e.length;L++)if(g.p3(e[L])===k)return e[L];for(L=0;L<e.length;L++)if(g.p3(e[L]).split("-")[0]===k.split("-")[0])return e[L]}}if(t&&f.G&&(r=f.G.N,r.length))for(var d of r)if(d.languageCode===
n){B=d;break}}else for(d=[f.videoData.captionsLanguagePreference,f.Ta.captionsLanguagePreference,g.FQ(f.videoData,"yt:cc_default_lang")],n=0;n<d.length;n++)for(r=0;r<e.length;r++)if(g.p3(e[r])===d[n])return e[r];d=null;f.N&&f.N.J&&(d=f.N.J);d||(d=e.find(t=>t.isDefault)||null);
d||(d=e[0]||ca(f));d&&B&&g.p3(d).split("-")[0]!==B.languageCode.split("-")[0]&&(d=K$g(d,B));return d},oX=function(f,e,B){f.loaded&&f.unload();
B!=null&&(f.X=B,f.X&&(g.yQ(f.Ta)?AP(f,!!e):ji(f,!!e)));e!==null||aX(f,!0)||f.Jq(e,!!e,f.X?"m":"s");f.C=e;aX(f)&&(f.C=ca(f));O6(f,f.C??void 0);f.load()},AP=function(f,e){f.Z.isInline()||g.yT("yt-player-sticky-caption",e,2592E3)},ji=function(f,e){if(f.storage)try{f.storage.set("module-enabled",e)}catch(B){}},O6=function(f,e){f.Ta.Y("html5_modify_caption_vss_logging")&&(f.videoData.o_=e)},FdB=function(f,e){var B=f.Cq[e.id];
B&&B.G!==e&&(B.dispose(),delete f.Cq[e.id],B=null);B||(B=uOe(f,e))&&(f.Cq[e.id]=B)},mVe=function(f,e){const B=e.windowId;
f.Z9[B]||(f.Z9[B]=[]);f.Z9[B].push(e)},uOe=function(f,e){const B=UVx(f);
if(!B)return null;var n=f.C?g.p3(f.C):null;n&&g.u65.test(n)&&(e.params.Z0=1);var r=f.tL.getPlayerSize();n=r.height*f.A.height;r=r.width*f.A.width;f.Ta.playerStyle!=="google-live"||f.W.isDefault||Object.assign(e.params,f.W);switch(e.params.HN!=null?e.params.HN:e.C.length>1?1:0){case 1:return new Nwg(e,f.W,f.U,B.width,B.height,r,n,f.Ta.experiments,f.MC.bind(f),f.Z);case 2:return new hge(e,f.W,f.U,B.width,B.height,r,n,f.Ta.experiments,f.MC.bind(f),f.Z);default:return new Vn(e,f.W,f.U,B.width,B.height,
r,n,f.Ta.experiments,f.MC.bind(f),f.Z)}},UVx=function(f){let e=f.tL.getVideoContentRect(!0).height,B=f.tL.getVideoContentRect(!0).width;
if(!e||!B)return null;e*=f.A.height;B*=f.A.width;return{width:B,height:e}},jYV=function(f,e){f.player.X6(e);
for(const B of e)g.d2(f.WS,B);Wz(f.PS)},gCu=function(f,e){if(!f.G)return{};
if(e){g.TL(e)||f.Bt(e.vss_id,"m");if(f.V&&f.J!=="HLS"||!g.jC(e))return;if(g.TL(e)){oX(f,null,!0);return}let n;var B=g.BO(f.G.C,!0);for(let r=0;r<B.length;r++){const L=B[r];L.languageCode!==e.languageCode||n&&(L.languageName!==e.languageName||(L.captionId||"")!==(e.captionId||"")||g.zH(L)!==e.displayName)||(n=e.translationLanguage?K$g(L,e.translationLanguage):L)}f.BU(e.position);!n||n===f.C&&f.loaded||(e=g.Pl(),B=g.p3(n),e.length&&B===e[e.length-1]||(e.push(B),g.yT("yt-player-caption-language-preferences",
e)),Rru(f.Ta)&&!f.Z.isInline()&&g.yT("yt-player-caption-sticky-language",B,2592E3),oX(f,n,!0))}else return f.loaded&&f.C&&!pV(f)?g.ap(f.C):{};return""};
g.NY.prototype.pv=g.B5(65,function(f,e,B){this.G.set(f,{f1:e,L0:B})});
g.h1.prototype.pv=g.B5(64,function(f,e,B){this.Ed.pv(f,e,B)});
g.a3.prototype.A=g.B5(63,function(){return!1});
g.a3.prototype.V=g.B5(62,function(){});
g.p4.prototype.V=g.B5(61,function(f,e,B){this.HS();e=this.U(f,e);const n=this.wi.S().Y("html5_report_captions_ctmp_qoe"),r=(0,g.T)();this.J();ZHL(this,e,{format:"RAW",onSuccess:L=>{this.G=null;if(n){var d=(L.responseText.length/1024).toFixed();const t=(0,g.T)();this.videoData.ri("capresp",{ms:t-r,kb:d})}d=L.getResponseHeader&&L.getResponseHeader("Content-Length")?Number(L.getResponseHeader("Content-Length")):0;B.v3(L.responseText,f,void 0,void 0,d)},
onError:n?L=>{this.videoData.ri("capfail",{status:L?.status??0})}:void 0,
withCredentials:!0})});
g.cH.prototype.V=g.B5(60,function(f,e,B){this.HS();e=this.U(f,e);this.J();this.G=g.QY(e,{format:"RAW",onSuccess:n=>{this.G=null;const r=n.getResponseHeader&&n.getResponseHeader("Content-Length")?Number(n.getResponseHeader("Content-Length")):0;B.v3(n.responseText,f,void 0,void 0,r)},
withCredentials:!0})});
g.Nc.prototype.X=g.B5(59,function(){const f=g.Ge(document,"track",void 0,this.C);for(let e=0;e<f.length;e++)g.tb(f[e])});
g.Se.prototype.X=g.B5(58,function(){this.mediaElement.X()});
g.Nc.prototype.eI=g.B5(57,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.Se.prototype.eI=g.B5(56,function(){return this.mediaElement.eI()});
g.Nc.prototype.cS=g.B5(55,function(){return!!this.C.textTracks});
g.Se.prototype.cS=g.B5(54,function(){return this.mediaElement.cS()});
g.Nc.prototype.Ed=g.B5(53,function(f){for(let e=0;e<f.length;e++)this.C.appendChild(f[e])});
g.Se.prototype.Ed=g.B5(52,function(f){this.mediaElement.Ed(f)});
g.sL.prototype.TQ=g.B5(40,function(f){return g.mO(this.app,{playerType:void 0}).TQ(f)});
g.fm.prototype.TQ=g.B5(39,function(f){return this.oA.aM.TQ(f)});
g.C4.prototype.TQ=g.B5(38,function(f){return this.QD().some(e=>e.namespace===f)});
g.ua.prototype.TQ=g.B5(37,function(){return!1});
g.sL.prototype.Bt=g.B5(35,function(f,e){this.app.Od().Bt(f,e)});
g.fm.prototype.Bt=g.B5(34,function(f,e){this.oA.Bt(f,e)});
g.d1.prototype.Bt=g.B5(33,function(f,e){f=[f,e];g.ot(this,g.uY(this.provider),"cfi",f)});
g.kT.prototype.Bt=g.B5(32,function(f,e){this.qoe&&this.qoe.Bt(f,e)});
g.dX.prototype.Bt=g.B5(31,function(f,e){this.Kh.Bt(f,e)});
g.ua.prototype.Bt=g.B5(30,function(){});
g.sL.prototype.Jq=g.B5(29,function(f,e,B){this.app.Od().Jq(f,e,B)});
g.fm.prototype.Jq=g.B5(28,function(f,e,B){this.oA.Jq(f,e,B)});
g.d1.prototype.Jq=g.B5(27,function(f,e,B){if(this.PS!==f||this.Ch!==e)e=e==="rawcc"?"":e,B=[f,e,this.PS,B],g.ot(this,g.uY(this.provider),"cfs",B),this.PS=f,this.Ch=e});
g.kT.prototype.Jq=g.B5(26,function(f,e,B){this.qoe&&this.qoe.Jq(f,e,B)});
g.dX.prototype.Jq=g.B5(25,function(f,e,B){this.Kh.Jq(f,e,B)});
g.ua.prototype.Jq=g.B5(24,function(){});
g.h9.prototype.vM=g.B5(3,function(f){return(f=this.J(f))?f.C:0});
g.EL.prototype.vM=g.B5(2,function(){return 0});
var phF=/#(.)(.)(.)/,am2=/^#(?:[0-9a-f]{3}){1,2}$/i,VyB={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},SmI={en:"English"},ECH=class extends g.a3{constructor(f){super(f);this.G=new Set}W(f){var e=this.wi.aC();if(e&&e.V3()){e=e.V3().textTracks;for(const B of e)B.kind==="subtitles"&&!this.G.has(B.language)&&B.language&&(g.YZ(this.C,new g.op({languageCode:B.language,languageName:B.language,kind:B.kind,id:B.id,displayName:SmI[B.label]||B.label,vss_id:`.${B.language}`})),this.G.add(B.language))}g.BO(this.C).length>
0&&f.xf()}},QYI=class{constructor(){this.segments=[]}contains(f){f=g.ax(this.segments,f);return f>=0||f<0&&(-f-1)%2===1}length(){return this.segments.length/2}},TwT=class extends g.$0{constructor(f,e,B,n,r,L){super();this.policy=f;this.player=e;this.vS=B;this.K=n;this.W=r;this.A=L;this.V=new QYI;this.U=-1;this.G=this.J=this.C=null;this.Cq=0;this.X=new g.T6(this.Ed,1E3,this);this.events=new g.ep(this);g.A(this,this.X);g.A(this,this.events);this.events.D(e,"SEEK_COMPLETE",this.N);this.N();this.Ed()}bY(){super.bY();
this.G&&this.G.cancel()}N(){this.seekTo(this.player.getCurrentTime())}seekTo(f){f-=this.player.gA();const e=this.C;this.C=g.QG(this.vS.U(f).T6);e!==this.C&&this.A&&this.A()}reset(){this.V=new QYI;this.U=-1;this.G&&(this.G.cancel(),this.G=null)}Ed(){this.HS();var f;if(f=this.C!=null)f=this.C,f=f.vS.V(f);if(f&&!this.G&&!(this.C&&this.C.startTime-this.player.getCurrentTime()>30)){f=this.C;f=f.vS.PS(f);const r=f.T6[0];if(this.player.getVideoData()?.enableServerStitchedDai){var e=this.player.OX();if(e){var B=
r.vS.info.id;const L=r.YA;var n=f.T6[0].V;if(this.policy.PS){if(e=g.kyC(e,n,L,B,3))f.V=e}else if(B=e.zi(n,L,B,3))if(n=2,e.RP.has(L)?n=0:g.ri(e,L)&&(n=1),e=n,e===0)B&&(f.C=new g.Qv(B));else if(e===2){this.X.start();AjI(this)&&this.seekTo(this.player.getCurrentTime());return}}}r.vS.index.kZ(r.YA)?(this.V.contains(f.T6[0].YA)||jAe(this,f),this.C=g.QG(f.T6)):AjI(this)&&this.seekTo(this.player.getCurrentTime())}this.X.start()}},DVT=class extends g.a3{constructor(f,e){super(e);this.G=f;this.Z=e;this.K=
null;this.Ed=!1;this.logger=new g.or("caps");this.Cq=g.AW(this.Z,this.G)}V(f,e,B){this.J();e=OHM(this,f.getId());e||(e=f.languageCode,e=this.G.isManifestless?o2g(this,e,"386"):o2g(this,e));if(e){var n=(e.index.vM(e.index.Ma())-e.index.getStartTime(e.index.Ma()))*1E3,r=new g.i2m(this.Z.S());this.K=new TwT(r,this.Z,e,(L,d)=>{B.v3(L,f,d,n)},this.Cq||g.TF(e.info),()=>{this.K&&this.K.reset();
this.Ed=!0})}}A(){const f=this.Ed;
this.Ed=!1;return f}W(f){var e=this.Z.S().Y("html5_fallback_if_rawcc_missing");const B=this.G.C.rawcc!=null;if(!this.Cq||!B&&e)e=this.G.isManifestless?lmB(this,"386"):lmB(this);else{if(!B){g.Vj(this.logger,386248249,"rawcc used but unavailable");return}e=[new g.op({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.op({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const n of e)g.YZ(this.C,
n);f.xf()}J(){this.K&&(this.K.dispose(),this.K=null)}U(){return""}},kN=/^#(?:[0-9a-f]{3}){1,2}$/i;var JbH=["left","right","center","justify"];var Vn=class extends g.y{constructor(f,e,B,n,r,L,d,t,H,k){const C=k.isInline()&&!0,w={};Object.assign(w,e);Object.assign(w,f.params);Object.assign(w,B);const v={};Object.assign(v,e.o1);f.params.o1&&Object.assign(v,f.params.o1);Object.assign(v,B.o1);C&&(w.windowOpacity=.6,v.backgroundOpacity=0);w.o1=v;const b=w.Z0===1,K=[{L:"span",B:"captions-text",O:{style:"word-wrap: normal; display: block;"}}];(t=t.SI("caption_edit_on_hover")&&k.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand)&&
K.unshift({L:"button",B:"caption-edit",O:{tabindex:"0","aria-label":cjH()},j:[{L:"svg",O:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{L:"path",O:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({L:"div",B:"caption-window",O:{id:`${"caption-window"}-${f.id}`,dir:b?"rtl":"ltr",tabindex:"0",lang:w.lang},j:K});this.U=
[];this.WS=!1;this.G=f;this.Lq=this.PS=null;this.hF=L;this.Ys=d;this.X=null;this.maxWidth=L*.96;this.maxHeight=d*.96;this.C=w;this.EE=B;this.Cq=e;this.V=this.JL("captions-text");this.Mk=this.V.style.getPropertyValue("box-decoration-break")!==""||this.V.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.BS=ulx(n,r,L,d);this.lC=H;t&&(this.W=this.JL("caption-edit"),this.D(this.W,"click",()=>{this.lC()}));
this.type=0;this.MC=this.BS*F$H(v);this.IA=C;f=new g.rI(this.element,!0);g.A(this,f);f.subscribe("dragstart",this.UE,this);f.subscribe("dragmove",this.sE,this);f.subscribe("dragend",this.Wd,this);this.qC=this.kA=this.xA=this.tL=0;f="";this.C.windowOpacity&&(f=XJ(this.C.windowColor),f="rgba("+f[0]+","+f[1]+","+f[2]+","+this.C.windowOpacity+")");e={"background-color":f,display:this.C.isVisible===!1?"none":"","text-align":JbH[this.C.textAlign]};this.Mk&&(e["border-radius"]=f?`${this.MC/8}px`:"");(this.J=
this.G.params.Z0===2||this.G.params.Z0===3)&&mox(this,this.element);g.uc(this.element,e);C&&this.element.parentElement?.style.setProperty("--caption-window-color",f);switch(this.C.Kj){case 0:case 1:case 2:g.PW(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.PW(this.element,"ytp-caption-window-bottom")}}UE(f,e){this.kA=f;this.qC=e;const B=g.Gt(this.element,this.element.parentElement);this.tL=f-B.x;this.xA=e-B.y}sE(f,e){if(f!==this.kA||e!==this.qC){g.yC(this.element,"ytp-dragging")||
g.PW(this.element,"ytp-dragging");var B=g.WN(this.element);f=f-this.tL-.02*this.hF;var n=e-this.xA-.02*this.Ys,r=(f+B.width/2)/this.maxWidth*3;r=Math.floor(g.ch(r,0,2));var L=(n+B.height/2)/this.maxHeight*3;L=Math.floor(g.ch(L,0,2));e=r+L*3;f=(f+r/2*B.width)/this.maxWidth;f=g.ch(f,0,1)*100;B=(n+L/2*B.height)/this.maxHeight;B=g.ch(B,0,1)*100;this.G.params.Kj=e;this.G.params.i8=B;this.G.params.CA=f;this.G.params.isDefault=!1;this.C.Kj=e;this.C.i8=B;this.C.CA=f;this.C.isDefault=!1;this.Cq.Kj=e;this.Cq.i8=
B;this.Cq.CA=f;this.Cq.isDefault=!1;this.uC()}}Wd(){g.$i(this.element,"ytp-dragging")}uC(){this.K(this.U)}K(f){var e=this.IA?0:Math.min(this.G6(),this.maxWidth),B=this.Ch(),n=this.IA;if(n){var r=getComputedStyle(this.V.parentNode);r=Pz(r.borderLeftWidth)+Pz(r.borderRightWidth)+Pz(r.paddingLeft)+Pz(r.paddingRight)}else r=0;const L=r;r="";this.G.params.Z0===3&&(r="rotate(180deg)");var d=n?`calc(${"96%"} - ${L}px)`:"96%";g.uc(this.element,{top:0,left:0,right:"",bottom:"",width:e?`${e}px`:"",height:B?
`${B}px`:"","max-width":d,"max-height":d,margin:"",transform:""});this.Z9(f);r={transform:r,top:"",left:"",width:e?`${e}px`:"",height:B?`${B}px`:"","max-width":"","max-height":""};var t=this.C.CA*.96+2;d=this.C.Kj;switch(d){case 0:case 3:case 6:(n=this.C.o1.fontSizeIncrement)&&n>0&&this.C.Z0!==2&&this.C.Z0!==3&&(t=Math.max(t/(1+n*2),2));r.left=`${t}%`;break;case 1:case 4:case 7:r.left=`${t}%`;t=this.V.offsetWidth;e||t?(e=e||t+1,r.width=`${e}px`,r["margin-left"]=n?`${e/-2-L/2}px`:`${e/-2}px`):r.transform+=
" translateX(-50%)";break;case 2:case 5:case 8:r.right=`${100-t}%`}n=this.C.i8*.96+2;switch(d){case 0:case 1:case 2:r.top=`${n}%`;break;case 3:case 4:case 5:r.top=`${n}%`;(B=B||this.element.clientHeight)?(r.height=`${B}px`,r["margin-top"]=`${B/-2}px`):r.transform+=" translateY(-50%)";break;case 6:case 7:case 8:r.bottom=`${100-n}%`}g.uc(this.element,r);if(this.W){B=this.V.offsetHeight;n=1;for(e=0;e<f.length;e++)r=f[e],typeof r.text==="string"&&(n+=r.text.split("\n").length-1,r.append||e===0||n++);
B/=n;this.W.style.height=`${B}px`;this.W.style.width=`${B}px`;this.element.style.paddingLeft=`${B+5}px`;this.element.style.paddingRight=`${B+5}px`;f=Number(this.element.style.marginLeft.replace("px",""))-B-5;B=Number(this.element.style.marginRight.replace("px",""))-B-5;this.element.style.marginLeft=`${f}px`;this.element.style.marginRight=`${B}px`}}Z9(f){let e;for(e=0;e<f.length&&f[e]===this.U[e];e++);if(this.WS||this.U.length>e)e=0,this.WS=!1,this.U=[],this.X=this.Lq=this.PS=null,g.LC(this.V);for(;e<
f.length;e++)g2g(this,f[e])}G6(){return 0}Ch(){return 0}toString(){return super.toString()}};var GtT=class{constructor(){this.J=this.time=this.mode=this.G=0;this.V=new MAI(this);this.W=new MAI(this);this.C=[];this.clear()}clear(){this.J=this.time=this.mode=0;this.C=[];this.reset()}reset(){this.mode=0;this.V.reset(0);this.W.reset(1)}},SEM=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],xVu=class{constructor(){this.type=0}set(f){this.type=f}get(){return this.type}},Wdu=class{constructor(){this.state=this.N6=this.W$=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}H4(){return this.state!==0}matches(f,e){return this.H4()&&f===this.W$&&e===this.N6}},sYB=class{constructor(){this.timestamp=this.C=0}reset(){this.timestamp=
this.C=0}},lk=class{constructor(f){this.W=f;this.J=[];this.C=this.G=this.row=0;this.style=new xVu;this.V=0;for(f=0;f<=15;f++){this.J[f]=[];for(let e=0;e<=32;e++)this.J[f][e]=new sYB}}updateTime(f){for(let e=1;e<=15;++e)for(let B=1;B<=32;++B)this.J[e][B].timestamp=f}debugString(){let f="\n";for(let e=1;e<=15;++e){for(let B=1;B<=32;++B){const n=this.J[e][B];f=n.C===0?f+"_":f+String.fromCharCode(n.C)}f+="\n"}return f}reset(f){for(let e=0;e<=15;e++)for(let B=0;B<=32;B++)this.J[e][B].reset();this.V=f;
this.C=0;this.G=this.row=1}},Jje=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],MyH=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Gee=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],xoe=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],XNu=class{constructor(f){this.J=f;this.W=0;this.style=new xVu;this.U=new lk(this.J);this.X=new lk(this.J);this.text=new lk(this.J);this.G=this.U;this.V=this.X;this.C=this.G}reset(f,e){this.W=e;this.style.set(2);this.G=this.U;this.V=this.X;this.C=this.G;const B=(f<<2)+(e<<1);this.U.reset(B);this.X.reset(B);
this.text.reset((f<<2)+(e<<1)+1)}},MAI=class{constructor(f){this.C=f;this.W=0;this.J=new XNu(this.C);this.U=new XNu(this.C);this.G=new Wdu;this.V=this.J}reset(f){this.W=f;this.G.clear();this.V=this.J;this.J.reset(f,0);this.U.reset(f,1)}};var ybM=class{V(){}};var nV=class extends g.VD{constructor(f,e,B,n,r,L=!1,d=null){super(f,f+e,{priority:B,namespace:"captions"});this.windowId=n;this.text=r;this.append=L;this.C=d}toString(){return super.toString()}};var uk=class extends g.$0{reset(){}};var LV=class extends g.VD{constructor(f,e,B,n,r){super(f,f+e,{priority:B,namespace:"captions"});this.id=n;this.params=r;this.C=[]}toString(){return super.toString()}},r9=0;var Pc2=class extends uk{constructor(f){super();this.V=f;this.pens={};this.K={};this.N={};this.W="_"+r9++;this.X={};this.G=this.C=null;this.U=!0}reset(){this.X={};this.G=this.C=null;this.U=!0}J(f,e){f=f.firstChild;f.getAttribute("format");e=e||0;Number.isFinite(e);f=Array.from(f.childNodes);for(var B of f)if(B.nodeType===1)switch(B.tagName){case "head":var n=B;break;case "body":var r=B}if(n){n=Array.from(n.childNodes);for(var L of n)if(L.nodeType===1)switch(L.tagName){case "pen":B=L.getAttribute("id");
n=this.pens;f={};var d=L.getAttribute("p");d&&Object.assign(f,this.pens[d]);d=tP(L,"b");d!=null&&(f.bold=d);d=tP(L,"i");d!=null&&(f.italic=d);d=tP(L,"u");d!=null&&(f.underline=d);d=Ha(L,"et");d!=null&&(f.charEdgeStyle=d);d=Ha(L,"of");d!=null&&(f.offset=d);d=CV(L,"bc");d!=null&&(f.background=d);d=CV(L,"ec");d!=null&&(f.xn=d);d=CV(L,"fc");d!=null&&(f.color=d);d=Ha(L,"fs");d!=null&&d!==0&&(f.fontFamily=d);d=d9(L,"sz");d!==void 0&&(f.fontSizeIncrement=d/100-1);d=d9(L,"bo");d!==void 0&&(f.backgroundOpacity=
d/255);d=d9(L,"fo");d!==void 0&&(f.textOpacity=d/255);d=Ha(L,"rb");d!=null&&d!==10&&d!==0&&(f.oM=d>10?d-1:d);d=Ha(L,"hg");d!=null&&(f.Si=d);n[B]=f;break;case "ws":n=L.getAttribute("id");this.N[n]=iHu(this,L);break;case "wp":n=L.getAttribute("id"),this.K[n]=fSV(this,L)}}if(r){L=[];r=Array.from(r.childNodes);for(Y of r)if(Y.nodeType===1)switch(Y.tagName){case "w":this.C=egV(this,Y,e,!1);(r=this.X[this.C.id])&&r.end>this.C.start&&(r.end=this.C.start);this.X[this.C.id]=this.C;L.push(this.C);break;case "p":var t=
Y;f=e;r=[];n=t.getAttribute("w")||this.W;B=!!tP(t,"a");f=(d9(t,"t")||0)+f;d=d9(t,"d")||5E3;B||(!this.U&&this.G&&this.G.windowId===n&&this.G.end>f&&(this.G.end=f),this.G&&this.G.text==="\n"&&(this.G.text=""));const l=B?6:5;var H=t.getAttribute("p");H=H?this.pens[H]:null;const m=Array.from(t.childNodes);m.length&&(this.U=t.getAttribute("d")!=null);for(t=0;t<m.length;t++){var k=m[t],C=void 0;t>0&&(B=!0);let F;k.nodeType===1&&(F=k);if(F&&F.tagName==="s"){if((k=(k=F.getAttribute("p"))?this.pens[k]:null)&&
k.oM&&(k.oM===1?(k=m.slice(t,t+4),k.length===4&&(C=ImT(f,d,n,B,l,k,this.pens),t+=3)):C=ImT(f,d,n,B,l,[F],this.pens)),!C){var w=F;C=f;k=d;var v=n,b=B;const N=w.textContent?w.textContent:"";var K=w.getAttribute("p");K=K?this.pens[K]:null;w=d9(w,"t")||0;C=new nV(C+w,k-w,l,v,N,b,K)}}else C=new nV(f,d,l,n,k.textContent||"",B,H);r.push(C);this.G=C}if(r.length>0){r[0].windowId===this.W&&(this.C=egV(this,Y,e,!0),L.push(this.C));for(const F of r)F.windowId=this.C.id,this.C.C.push(F),L.push(F)}}var Y=L}else Y=
[];return Y}};var ISe=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),$VI=class extends uk{constructor(f){super();this.U=f;this.C=new Map;this.V=new Map;this.W=new Map;this.G=new Map}reset(){this.G.clear()}J(f,e){f=JSON.parse(f);if(!f)return[];if(f.pens){var B=f.pens,n=0;for(var r of B){B={};var L=r.pParentId;L&&Object.assign(B,this.C.get(L));r.bAttr&&(B.bold=!0);r.iAttr&&(B.italic=!0);r.uAttr&&(B.underline=!0);L=r.ofOffset;L!=null&&(B.offset=L);r.szPenSize!==void 0&&(B.fontSizeIncrement=r.szPenSize/100-1);
L=r.etEdgeType;L!=null&&(B.charEdgeStyle=L);r.ecEdgeColor!==void 0&&(B.xn=w9(r.ecEdgeColor));L=r.fsFontStyle;L!=null&&L!==0&&(B.fontFamily=L);r.fcForeColor!==void 0&&(B.color=w9(r.fcForeColor));r.foForeAlpha!==void 0&&(B.textOpacity=r.foForeAlpha/255);r.bcBackColor!==void 0&&(B.background=w9(r.bcBackColor));r.boBackAlpha!==void 0&&(B.backgroundOpacity=r.boBackAlpha/255);(L=r.rbRuby)&&L!==10&&(B.oM=L>10?L-1:L,B.textEmphasis=ISe.get(B.oM));r.hgHorizGroup&&(B.Si=r.hgHorizGroup);this.C.set(n++,B)}}if(f.wsWinStyles){n=
f.wsWinStyles;r=0;for(var d of n)n={},(B=d.wsParentId)?Object.assign(n,this.W.get(B)):Object.assign(n,this.U),d.mhModeHint!==void 0&&(n.HN=d.mhModeHint),d.juJustifCode!==void 0&&(n.textAlign=d.juJustifCode),d.pdPrintDir!==void 0&&(n.Z0=d.pdPrintDir),d.sdScrollDir!==void 0&&(n.RE=d.sdScrollDir),d.wfcWinFillColor!==void 0&&(n.windowColor=w9(d.wfcWinFillColor)),d.wfoWinFillAlpha!==void 0&&(n.windowOpacity=d.wfoWinFillAlpha/255),this.W.set(r++,n)}if(f.wpWinPositions){r=f.wpWinPositions;d=0;for(var t of r)r=
{},(n=t.wpParentId)&&Object.assign(r,this.V.get(n)),t.ahHorPos!==void 0&&(r.CA=t.ahHorPos),t.apPoint!==void 0&&(r.Kj=t.apPoint),t.avVerPos!==void 0&&(r.i8=t.avVerPos),t.ccCols!==void 0&&(r.zL=t.ccCols),t.rcRows!==void 0&&(r.b4=t.rcRows),this.V.set(d++,r)}if(f.events){f=f.events;t=[];for(const E of f)if(d=(E.tStartMs||0)+e,r=E.dDurationMs||0,E.id)n=String(E.id),f=Bwx(this,E,d,r,n),t.push(f),this.G.set(n,f);else{E.wWinId?n=E.wWinId.toString():(n="_"+r9++,f=Bwx(this,E,d,r,n),t.push(f),this.G.set(n,f));
f=t;var H=E;r===0&&(r=5E3);B=this.G.get(n);const Lw=(L=!!H.aAppend)?6:5,d6=H.segs;let TO=null;H.pPenId&&(TO=this.C.get(H.pPenId));for(H=0;H<d6.length;H++){var k=d6[H],C=k.utf8;if(C){var w=k.tOffsetMs||0;let AY=null;k.pPenId&&(AY=this.C.get(k.pPenId));if((B.params.HN!=null?B.params.HN:B.C.length>1?1:0)===2&&L&&C==="\n")continue;k=null;var v=[],b;if(b=AY&&AY.oM===1)a:{b=d6;var K=H;if(K+3>=b.length||!b[K+1].pPenId||!b[K+2].pPenId||!b[K+3].pPenId){b=!1;break a}var Y=b[K+1].pPenId;(Y=this.C.get(Y))&&Y.oM&&
Y.oM===2?(Y=b[K+2].pPenId,Y=this.C.get(Y),!Y||!Y.oM||Y.oM<3?b=!1:(Y=b[K+3].pPenId,b=(Y=this.C.get(Y))&&Y.oM&&Y.oM===2?!0:!1)):b=!1}if(b)w=d6[H+1].utf8,k=d6[H+3].utf8,b=d6[H+2].utf8,K=this.C.get(d6[H+2].pPenId),C=PNB(C,w,b,k,K),k=new nV(d,r,Lw,n,C,L,AY),H+=3;else{if(C.indexOf("<")>-1){v=AY;b=TO;K=d;Y=r;var l=w,m=Lw,F=L;const Dl=[];var N=g.eF(`<html>${C}</html>`);if(!N.getElementsByTagName("parsererror").length&&N.firstChild?.childNodes.length)for(const W5 of N.firstChild.childNodes){N=W5.textContent?.replace(/\n/g,
"")??"";if(W5.nodeType===3&&(!N||N.match(/^ *$/)!=null))continue;const lP={};Object.assign(lP,v||b);switch(W5?.tagName){case "b":lP.bold=!0;break;case "i":lP.italic=!0;break;case "u":lP.underline=!0}Dl.push(new nV(K+l,Y-l,m,B.id,N,F,lP))}v=Dl}v.length||(v=[new nV(d+w,r-w,Lw,B.id,C,L,AY||TO)])}if(v.length)for(const Dl of v)f.push(Dl),B.C.push(Dl);else k&&(f.push(k),B.C.push(k))}L=!0}}e=t}else e=[];return e}};var iC2=class extends g.a3{constructor(f,e,B){super(f);this.videoData=e;this.audioTrack=B;this.N=e.A$}V(f,e,B){zrG(this.videoData.videoId,f.vssId,B.v3)}W(f){if(this.audioTrack)for(const e of this.audioTrack.captionTracks)g.YZ(this.C,e);f.xf()}};var Nwg=class extends Vn{constructor(f,e,B,n,r,L,d,t,H,k){super(f,e,B,n,r,L,d,t,H,k);this.type=1}Z9(f){const e=this.G.C;super.Z9(f);let B,n;for(f=f.length;f<e.length;f++){const r=e[f];let L;n&&r.C===B?L=n:(L={},Object.assign(L,r.C),Object.assign(L,fOe),B=r.C,n=L);g2g(this,r,L)}}},fOe={Of:!0};var nCM=class extends ybM{constructor(f,e){super();this.trackData=f;this.U=e;this.version=this.W=this.J=this.byteOffset=0;this.G=[];this.C=new DataView(this.trackData)}V(f,e,B,n,r){if(B<n){const L="_"+r9++;B=B/1E3-this.U;n=n/1E3-this.U;f=new LV(B,n-B,5,L,{textAlign:0,Kj:0,CA:e*2.5,i8:f*5.33});r=new nV(B,n-B,5,L,r);this.G.push(f);this.G.push(r)}}},eVB=class extends uk{constructor(f,e){super();this.G=f;this.V=e;this.track=this.V.languageName==="CC3"?4:0;this.C=new GtT;this.C.G=1<<this.track}J(f){f=
new nCM(f,this.G);if(rbT(f)){for(;f.byteOffset<f.C.byteLength;)for(f.version===0?f.J=bk(f)*(1E3/45):f.version===1&&(f.J=bk(f)*4294967296+bk(f)),f.W=va(f);f.W>0;f.W--){var e=va(f);const B=va(f),n=va(f);e&4&&(e&3)===this.track&&(this.track===0||this.track===1)&&(e=this.C,e.C.push({time:f.J,type:this.track,GB:B,bH:n,order:e.C.length}))}Doe(this.C,f);return f.G}return[]}reset(){this.C.clear()}};var hge=class extends Vn{constructor(f,e,B,n,r,L,d,t,H,k){super(f,e,B,n,r,L,d,t,H,k);this.type=2;this.cS=[];this.A=this.N=this.uY=0;this.eI=NaN;this.Q3=0;this.mS=null;this.hE=new g.T6(this.Fl,433,this);this.W&&(k.createClientVe(this.W,this,167342),this.D(this.W,"click",()=>{k.logClick(this.W)}),f=new g.rI(this.element,!0),g.A(this,f),f.subscribe("hoverstart",()=>{k.logVisibility(this.W,!0)},this));
g.PW(this.element,"ytp-caption-window-rollup");g.A(this,this.hE);g.uc(this.element,"overflow","hidden")}uC(){g.G6(this.hE)}Fl(){this.element.removeEventListener("transitionend",this.Fl,!1);g.$i(this.element,"ytp-rollup-mode");this.K(this.mS,!0)}Ch(){return this.J?this.A:this.N}G6(){return this.J?this.N:this.A}K(f,e){this.mS=f;if(this.G.params.b4){var B=0;for(let n=0;n<this.U.length&&B<f.length;n++)this.U[n]===f[B]&&B++;B>0&&B<f.length&&(f=this.U.concat(f.slice(B)));this.Q3=this.A;this.N=this.A=0;
super.K(f);HCe(this,e)}super.K(f)}};var BPe=class{constructor(f,e,B,n){this.Z=f;this.J=e;this.logger=B;this.sA=n;this.GD=[];this.rU=[];this.C=null;this.aX={i5l:()=>this.C,
tR:()=>this.GD};
f=g.tS(this.Z.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.G=f>0?f:10}unload(){this.C!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.C),this.C=null);this.GD=[];this.Z.publish("sabrCaptionsBufferedRangesUpdated",this.GD)}u0(f){return{formatId:g.Jk(f.info.vS.info,this.sA),YA:f.info.YA+(this.sA?0:1),startTimeMs:f.info.V*1E3,durationMs:f.info.K*1E3}}};var n_g=class extends g.a3{constructor(f,e){super(e);this.G=f;this.Z=e;this.logger=new g.or("caps");this.K=this.Ed=null;this.Cq=new BPe(this.Z,this,this.logger,this.G.sA)}V(f,e,B){this.J();e=f.getId();e=e!=null&&e in this.G.C?this.G.C[e]:null;e||(e=f.languageCode,e=this.G.isManifestless?vCe(this,e,"386"):vCe(this,e));e&&(this.K=f,this.Ed=e,CcG(this.Cq,B),this.Z.publish("sabrCaptionsTrackChanged",g.Jk(e.info,this.G.sA)))}W(f){var e=this.G.isManifestless?bCT(this,"386"):bCT(this);for(const B of e)g.YZ(this.C,
B);f.xf()}J(){this.K&&(this.K=this.Ed=null,this.Cq.unload(),this.Z.publish("sabrCaptionsTrackChanged",null))}U(){return""}};var ZCM="WEBVTT".split("").map(f=>f.charCodeAt(0)),pNF=class extends uk{constructor(){super()}J(f,e){f instanceof ArrayBuffer&&(f=g.kq(new Uint8Array(f)));
const B=[];f=f.split(rGe);for(let K=1;K<f.length;K++){var n=f[K],r=e;if(n!==""&&!L3H.test(n)){var L=F2.exec(n);if(L&&L.length>=4){var d=Zz(L[1]),t=Zz(L[2])-d;d+=r;var H=(L=L[3])?L.split(" "):[];L={};var k=null;var C="";var w=null,v="";for(const Y of H){H=Y.split(":");if(H.length!==2)continue;var b=H[1];switch(H[0]){case "line":H=b.split(",");H[0].endsWith("%")&&(k=H[0],L.i8=Number.parseInt(k,10),H.length===2&&(C=H[1].trim()));break;case "position":H=b.split(",");w=H[0];L.CA=Number.parseInt(w,10);
H.length===2&&(v=H[1].trim());break;case "align":switch(b){case "start":L.textAlign=0;break;case "middle":L.textAlign=2;break;case "end":L.textAlign=1}}}k||C||(C="end");if(!w)switch(L.textAlign){case 0:L.CA=0;break;case 1:L.CA=100;break;case 2:L.CA=50}if(L.textAlign!=null){k=0;switch(C){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(v){case "line-left":k+=0;break;case "center":k+=1;break;case "line-right":k+=2;break;default:switch(L.textAlign){case 0:k+=0;break;case 2:k+=1;break;
case 1:k+=2}}C=k<0||k>8?7:k;L.Kj=C}n=n.substring(F2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=L;L=n;n={};if(L.indexOf("<")<0&&L.indexOf("&")<0)r=Kde(d,t,5,v),t=new nV(d,t,5,r.id,L,!1,g.TL(n)?void 0:n),B.push(r),B.push(t),r.C.push(t);else for(C=L.split(daF),C.length===1?(L=5,v=Kde(d,t,L,v)):(k=L=6,v=Object.assign({zL:32},v),v=new LV(d,t,k,"_"+r9++,v)),B.push(v),k=d,w=0;w<C.length;w++)if(H=C[w],w%2===0){b=g.eF(`<html>${H}</html>`);let Y;b.getElementsByTagName("parsererror").length?(Y=b.createElement("span"),
Y.appendChild(b.createTextNode(H))):Y=b.firstChild;qmg(this,k,t-(k-d),L,v,w>0,Y,n,B)}else k=Zz(H)+r}F2.lastIndex=0}}return B}},L3H=/^NOTE/,rGe=/(?:\r\n|\r|\n){2,}/,F2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),daF=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var tWM=class extends g.$0{constructor(f,e){super();this.Z=f;this.Ta=e;this.C=null;this.fh=this.Z.OX();this.logger=new g.or("caps")}clear(){this.C&&this.C.dispose();this.C=null}reset(){this.C&&this.C.reset()}bY(){super.bY();this.clear()}};var RX={windowColor:"#080808",windowOpacity:0,textAlign:2,Kj:7,CA:50,i8:100,isDefault:!0,o1:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.cO("captions",class extends g.zV{constructor(f){super(f);this.Z=f;this.WS=[];this.Cq={};this.Z9={};this.X=!1;this.J="NONE";this.G=this.N=this.Ed=this.uY=this.kA=null;this.xA={xf:()=>{this.xf()},
v3:(n,r,L,d,t=0)=>{const H=Number(this.videoData.S().JE().C.jI(g.fqk)??0);t>0&&H>0&&this.videoData.lengthSeconds>0&&t/this.videoData.lengthSeconds>H?this.Z.ri("tts",{dropcap:t}):this.v3(n,r,L,d)}};
this.C=null;this.Ta=this.Z.S();this.videoData=this.Z.getVideoData();this.tL=this.Z.AL();this.W={o1:{}};this.U={o1:{}};this.videoData.Q3()?this.J="OFFLINE":g.wgM(this.videoData,this.Z)?this.J="HLS":wNe(this.videoData,this.Z)?this.J="SABR_LIVE":g.vKO(this.videoData,this.Z)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.Yp&&(this.J="TTS");this.BS=this.Ta.controlsType==="3";this.Fl=new tWM(this.Z,this.Ta);this.cS=new g.ep(this);this.K=new g.y({L:"div",B:"ytp-caption-window-container",
O:{id:"ytp-caption-window-container"}});this.A={top:0,right:0,bottom:0,left:0,width:1,height:1};let e=null;const B=g.Sh("yt-html5-player-modules::subtitlesModuleData");B&&(e=new g.Ah(B));this.storage=e;this.qC=!!f.aC()?.eI();this.V=Abe(this);this.eI=!this.V&&this.BS&&this.qC&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.A(this,this.Fl);this.V?this.Lq=this.PS=null:(this.PS=new g.SV(this.G6,void 0,this),g.A(this,this.PS),this.Lq=new g.T6(this.Mk,2E3,this),g.A(this,this.Lq));g.A(this,this.cS);g.qX(this.player,
this.K.element,4);g.A(this,this.K);this.V||this.cS.D(f,"resize",this.IA);(this.Ch=g.JF(this.Ta)&&!g.S4()&&!this.Z.isFullscreen()&&!this.V&&!this.eI)&&this.cS.D(f,"resize",this.Q3);this.cS.D(f,"onPlaybackAudioChange",this.Yp);this.cS.D(f,g.kk("captions"),n=>{this.onCueRangeEnter(n)});
this.cS.D(f,g.Ca("captions"),n=>{this.onCueRangeExit(n)});
KV(this,yk()||{});g.id(this.player,"onCaptionsModuleAvailable");this.J==="HLS"&&this.V&&(f=this.Z.aC().V3(),this.qC&&this.cS.D(f.textTracks,"addtrack",this.uC))}bY(){if(this.V||this.eI){const f=this.Z.aC();f&&!f.HS()&&f.X()}else qF(this,!1);super.bY()}Tw(){return this.Ta.Y("html5_honor_caption_availabilities_in_audio_track")&&this.J!=="LIVE"&&this.J!=="SABR_LIVE"}sL(){if(this.BS)return this.V||this.eI;if(this.J==="HLS")return this.V;var f=this.getAudioTrack();if(this.Tw()){if(!f.captionTracks.length)return!1;
if(!this.G)return!0}f=s4(f,g.yQ(this.Ta));return f==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:f==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?aX(this):z9(this)||aX(this)?!0:oCe(this)}load(){super.load();this.N=this.getAudioTrack();if(this.G)this.C&&(this.Fl.clear(),this.V?VAe(this,!0):this.player.getPresentingPlayerType()!==3&&this.G.V(this.C,"json3",this.xA),this.J!=="HLS"&&this.V||this.eI||pV(this)||g.id(this.player,"captionschanged",g.ap(this.C)));else{let f;this.J==="OFFLINE"?f=new iC2(this.player,this.videoData,
this.getAudioTrack()):this.J==="SABR_LIVE"?f=new n_g(this.videoData.C,this.player):this.J==="HLS"?f=new ECH(this.player):this.J==="LIVE"?f=new DVT(this.videoData.C,this.player):this.J==="INNERTUBE"?f=new g.p4(this.player,this.videoData,this.getAudioTrack()):f=new g.cH(this.player,this.videoData.Yp,this.videoData.videoId,g.W4C(this.videoData),this.videoData.pz,this.videoData.eventId);this.G=f;g.A(this,this.G);this.G.W(this.xA)}}unload(){this.V&&this.C?VAe(this,!1):(this.Lq&&this.Lq.M9(),this.player.sK("captions"),
this.WS=[],this.G&&this.G.J(),this.Fl.clear(),this.Ed&&this.player.AI(this.Ed),this.IA());super.unload();this.player.Rm();g.id(this.player,"captionschanged",{})}create(){this.sL()&&this.load();var f;a:{if(this.Ta.Y("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(f=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const e of f)if(e.kind==="asr"&&e.languageCode===
"en"){f=!0;break a}f=!1}f&&this.Z.publish("showpromotooltip",this.K.element)}xf(){var f=s4(this.player.getAudioTrack(),g.yQ(this.Ta));var e=f==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?YN(this,this.X):f==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&aX(this)?ca(this):z9(this)||this.X||oCe(this)?YN(this,this.X):aX(this)?ca(this):null;if(this.J!=="HLS"&&this.V||this.eI){const B=g.BO(this.G.C,!0);f=[];for(let n=0;n<B.length;n++){const r=B[n],L=g.BN("TRACK");L.setAttribute("kind","subtitles");L.setAttribute("label",
g.zH(r));L.setAttribute("srclang",g.p3(r));L.setAttribute("id",r.toString());this.eI||L.setAttribute("src",this.G.U(r,"vtt"));r===e&&L.setAttribute("default","1");f.push(L)}e=this.Z.aC();e.Ed(f);f=e.V3();this.qC&&this.cS.D(f.textTracks,"change",this.hE)}else!this.C&&e&&oX(this,e),g.id(this.player,"onCaptionsTrackListChanged"),g.f_(this.player,"onApiChange")}getTrackById(f){const e=g.BO(this.G.C,!0);for(let B=0;B<e.length;B++)if(e[B].toString()===f)return e[B];return null}hE(){const f=this.Z.aC().V3().textTracks;
let e=null;for(let B=0;B<f.length;B++)f[B].mode==="showing"&&(e=this.getTrackById(f[B].id));(this.loaded?this.C:null)!==e&&oX(this,e,!0)}uC(){this.G?.W(this.xA)}wm(){!this.C&&this.V||this.unload()}v3(f,e,B,n){if(f){O6(this,this.C??void 0);this.G.A()&&(this.WS=[],this.Z.sK("captions"),Wz(this.PS),this.Fl.reset());a:{var r=this.Fl;n=n||0;B=aSI(r,f,B||0);f=[];try{for(const m of B){const F=m.trackData,N=m.V0,E=r.Ta.Y("safari_live_drm_captions_fix");if(typeof F!=="string"){B=f;var L=B.concat;if(E&&RgB(F))var d=
cbB(r,F,N);else{var t=r,H=e,k=F,C=N,w=n;if(!LdH(k))throw Error("Invalid binary caption track data");t.C||(t.C=new eVB(w,H));d=t.C.J(k,C)}var v=L.call(B,d)}else{if(F.substring(0,6)==="WEBVTT")var b=f.concat(cbB(r,F,N));else{B=f;var K=B.concat;b:{H=r;t=e;if(F[0]==="{")try{H.C||(H.C=new $VI(Ymx(t)));var Y=H.C.J(F,N);break b}catch(TO){g.J(TO);Y=[];break b}const Lw=g.eF(F);if(!Lw||!Lw.firstChild){const TO=Error("Invalid caption track data");TO.params=F;throw TO;}if(Lw.firstChild.tagName==="timedtext"){if(Number(Lw.firstChild.getAttribute("format"))===
3){k=Lw;H.C||(H.C=new Pc2(Ymx(t)));Y=H.C.J(k,N);break b}const TO=Error("Unsupported subtitles format in web player (Format2)");TO.params=F;throw TO;}if(Lw.firstChild.tagName==="transcript"){const TO=Error("Unsupported subtitles format in web player (Format1)");TO.params=F;throw TO;}const d6=Error("Invalid caption track data");d6.params=F;throw d6;}b=K.call(B,Y)}v=b}f=v}var l=f;break a}catch(m){g.Vj(r.logger,187101178,`Captions parsing failed: ${m.message}. `);r.clear();l=[];break a}l=void 0}e=l;e.length>
0&&(l=this.C,this.Jq(l,!!l,pV(this)?"g":this.X?"m":"s"));this.player.AI(e,void 0,this.J==="LIVE"||this.J==="SABR_LIVE");!this.X||this.eI||pV(this)||g.IM(this.Ta)||g.DH(this.Ta)||g.TT(this.Ta)||this.Ta.Cq==="shortspage"||this.player.isInline()||(this.Lq.M9(),e=$oF({Kj:0,CA:5,i8:5,b4:2,textAlign:0,Z0:0,lang:"en"}),this.uY=[e],l=["Click "," for settings"],this.kA||(r=new g.af(g.zT()),g.A(this,r),this.kA=r.element),r=e.end-e.start,(v=g.zH(this.C))&&this.uY.push(new nV(e.start,r,0,e.id,v)),this.uY.push(new nV(e.start,
r,0,e.id,l[0]),new nV(e.start,r,0,e.id,this.kA,!0),new nV(e.start,r,0,e.id,l[1],!0)),this.player.AI(this.uY),this.Lq.M0());!this.X||this.eI||pV(this)||(g.yQ(this.Ta)?AP(this,!0):ji(this,!0),this.N&&(this.N.V=this.C),this.player.Rm());this.X=!1}}onCueRangeEnter(f){this.WS.push(f);Wz(this.PS)}onCueRangeExit(f){g.d2(this.WS,f);this.G instanceof DVT&&this.G.Cq&&this.player.X6([f]);Wz(this.PS)}getCaptionWindowContainerId(){return this.K.element.id}Mk(){jYV(this,this.uY);this.uY=null}G6(){if(!this.Ch||
!this.V){this.PS.stop();g.DV(this.Z9);this.WS.sort(g.HP);var f=this.WS;if(this.Ed){const e=g.GO(f,function(B){return this.Ed.indexOf(B)===-1},this);
e.length&&(f=e)}for(const e of f)e instanceof LV?FdB(this,e):mVe(this,e);for(const [e,B]of Object.entries(this.Cq)){const n=e,r=B;this.Z9[n]?(r.element.parentNode||(r instanceof hge||r instanceof Nwg||g.lH(this.Cq,(L,d)=>{d!==n&&L.G.params.Kj===r.G.params.Kj&&L.G.params.CA===r.G.params.CA&&L.G.params.i8===r.G.params.i8&&(L.dispose(),delete this.Cq[d]);return d===n},this),this.K.element.appendChild(r.element)),r.K(this.Z9[n])):(r.dispose(),delete this.Cq[n])}}}YP(){KV(this,{},!0);
g.id(this.player,"captionssettingschanged")}ZH(){var f=RX.o1;f={background:f.background,backgroundOpacity:f.backgroundOpacity,charEdgeStyle:f.charEdgeStyle,color:f.color,fontFamily:f.fontFamily,fontSizeIncrement:f.fontSizeIncrement,fontStyle:f.bold&&f.italic?3:f.bold?1:f.italic?2:0,textOpacity:f.textOpacity,windowColor:RX.windowColor,windowOpacity:RX.windowOpacity};const e=yk()||{};e.background!=null&&(f.background=e.background);e.backgroundOverride!=null&&(f.backgroundOverride=e.backgroundOverride);
e.backgroundOpacity!=null&&(f.backgroundOpacity=e.backgroundOpacity);e.backgroundOpacityOverride!=null&&(f.backgroundOpacityOverride=e.backgroundOpacityOverride);e.charEdgeStyle!=null&&(f.charEdgeStyle=e.charEdgeStyle);e.charEdgeStyleOverride!=null&&(f.charEdgeStyleOverride=e.charEdgeStyleOverride);e.color!=null&&(f.color=e.color);e.colorOverride!=null&&(f.colorOverride=e.colorOverride);e.fontFamily!=null&&(f.fontFamily=e.fontFamily);e.fontFamilyOverride!=null&&(f.fontFamilyOverride=e.fontFamilyOverride);
e.fontSizeIncrement!=null&&(f.fontSizeIncrement=e.fontSizeIncrement);e.fontSizeIncrementOverride!=null&&(f.fontSizeIncrementOverride=e.fontSizeIncrementOverride);e.fontStyle!=null&&(f.fontStyle=e.fontStyle);e.fontStyleOverride!=null&&(f.fontStyleOverride=e.fontStyleOverride);e.textOpacity!=null&&(f.textOpacity=e.textOpacity);e.textOpacityOverride!=null&&(f.textOpacityOverride=e.textOpacityOverride);e.windowColor!=null&&(f.windowColor=e.windowColor);e.windowColorOverride!=null&&(f.windowColorOverride=
e.windowColorOverride);e.windowOpacity!=null&&(f.windowOpacity=e.windowOpacity);e.windowOpacityOverride!=null&&(f.windowOpacityOverride=e.windowOpacityOverride);return f}Yl(f,e){const B={};Object.assign(B,yk());Object.assign(B,f);KV(this,B,e);g.id(this.player,"captionssettingschanged")}IA(){!this.V&&this.loaded&&(g.OM(this.Cq,function(f,e){f.dispose();delete this.Cq[e]},this),this.G6())}gZ(f,e){switch(f){case "fontSize":if(isNaN(e))break;
f=g.ch(e,-2,4);this.Yl({fontSizeIncrement:f});return f;case "reload":e&&!this.V&&oX(this,this.C,!0);break;case "stickyLoading":e!==void 0&&this.Ta.K&&(g.yQ(this.Ta)?AP(this,!!e):ji(this,!!e));break;case "track":return gCu(this,e);case "tracklist":return this.G?g.xg(g.BO(this.G.C,!(!e||!e.includeAsr)),B=>g.ap(B)):[];
case "translationLanguages":return this.G?this.G.N.map(B=>Object.assign({},B)):[];
case "sampleSubtitles":this.V||e===void 0||qF(this,!!e);break;case "sampleSubtitlesCustomized":this.V||qF(this,!!e,e);break;case "recommendedTranslationLanguages":return g.Pl();case "defaultTranslationSourceTrackIndices":return this.G?this.G.cS:[]}}getOptions(){const f="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Ta.K&&f.push("stickyLoading");return f}dS(){let f=this.C;if(this.Z.TQ("captions")){if(this.Ta.Y("html5_modify_caption_vss_logging"))return(f=this.videoData.o_??
null)?{cc:g.m6k(f)}:{};if(f){let e=f.vssId;f.translationLanguage&&e&&(e=`t${e}.${g.p3(f)}`);return{cc:e}}}return{}}QS(){this.isSubtitlesOn()?(g.yQ(this.Ta)?AP(this,!1):ji(this,!1),O6(this),oX(this,null,!0)):this.b5()}b5(){const f=pV(this)||!this.C?YN(this,!0):this.C;f&&this.Bt(f.vssId,"m");this.isSubtitlesOn()||oX(this,pV(this)||!this.C?YN(this,!0):this.C,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.C&&!pV(this)}Yp(){const f=pV(this);aX(this,f)?oX(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.Tw()&&(this.X=!1,this.C=null,this.G&&(this.G.dispose(),this.G=null)),this.sL()&&(f?oX(this,YN(this,!1),!1):this.load()))}BU(f){f&&(this.A={top:f.top,right:f.right,bottom:f.bottom,left:f.left,width:1-f.left-f.right,height:1-f.top-f.bottom},this.K.element.style.top=`${this.A.top*100}%`,this.K.element.style.left=`${this.A.left*100}%`,this.K.element.style.width=`${this.A.width*100}%`,this.K.element.style.height=`${this.A.height*100}%`,this.K.element.style.position="absolute",
f=UVx(this))&&(this.K.element.style.width=`${f.width}px`,this.K.element.style.height=`${f.height}px`)}onVideoDataChange(f,e){f==="newdata"&&(this.videoData=e,this.loaded&&this.unload(),this.X=!1,this.C=null,this.G&&(this.G.dispose(),this.G=null,g.id(this.player,"captionschanged",{})),this.sL()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Q3(){const f=this.Z.aC();f&&!f.HS()&&f.X();this.Z.isFullscreen()?(this.V=this.BS=!0,this.loaded&&this.xf()):(this.BS=this.Ta.controlsType==="3",
this.V=Abe(this));oX(this,this.C)}MC(){const f=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;f&&g.yW(this.player,"innertubeCommand",f)}Jq(f,e,B){const n=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let r="";f&&(r=f.vssId,r=r.replace(n,""));let L="";f&&f.getId()&&(L=f.getId()||"");f&&f.getXtags()&&(f=f.getXtags(),f=f.replace(n,""),L=L.concat(`;${f}`));this.J==="HLS"&&(L="");this.Z.Jq(e?r:"",e?L:"",B)}Bt(f,e){f=(f||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");f.length>0&&this.Z.Bt(f,e)}});})(_yt_player);
